#pragma once

#include <cstdint>
#include <groov/groov.hpp>

/* Intel groov for STM32G441xx MCU, using CM4 cpu */
/* Generated by svd2groov */

namespace mcu {

using dbgmcu_t = groov::group<
  "DBGMCU",
  groov::mmio_bus<>,
  groov::reg<"IDCODE",
             std::uint32_t,
             0xe004'2000 + 0u,
             groov::read_only<groov::w::replace>,
             groov::field<"DEV_ID",
                          std::uint_fast16_t,
                          15u,
                          0u,
                          groov::read_only<groov::w::replace>>,
             groov::field<"REV_ID",
                          std::uint_fast16_t,
                          31u,
                          16u,
                          groov::read_only<groov::w::replace>>>,
  groov::reg<
    "CR",
    std::uint32_t,
    0xe004'2000 + 0x4u,
    groov::w::replace,
    groov::field<"DBG_SLEEP", bool, 0u, 0u, groov::w::replace>,
    groov::field<"DBG_STOP", bool, 1u, 1u, groov::w::replace>,
    groov::field<"DBG_STANDBY", bool, 2u, 2u, groov::w::replace>,
    groov::field<"TRACE_IOEN", bool, 5u, 5u, groov::w::replace>,
    groov::field<"TRACE_MODE", std::uint_fast8_t, 7u, 6u, groov::w::replace>>,
  groov::reg<
    "APB1L_FZ",
    std::uint32_t,
    0xe004'2000 + 0x8u,
    groov::w::replace,
    groov::field<"DBG_TIMER2_STOP", bool, 0u, 0u, groov::w::replace>,
    groov::field<"DBG_TIM3_STOP", bool, 1u, 1u, groov::w::replace>,
    groov::field<"DBG_TIM4_STOP", bool, 2u, 2u, groov::w::replace>,
    groov::field<"DBG_TIM5_STOP", bool, 3u, 3u, groov::w::replace>,
    groov::field<"DBG_TIMER6_STOP", bool, 4u, 4u, groov::w::replace>,
    groov::field<"DBG_TIM7_STOP", bool, 5u, 5u, groov::w::replace>,
    groov::field<"DBG_RTC_STOP", bool, 10u, 10u, groov::w::replace>,
    groov::field<"DBG_WWDG_STOP", bool, 11u, 11u, groov::w::replace>,
    groov::field<"DBG_IWDG_STOP", bool, 12u, 12u, groov::w::replace>,
    groov::field<"DBG_I2C1_STOP", bool, 21u, 21u, groov::w::replace>,
    groov::field<"DBG_I2C2_STOP", bool, 22u, 22u, groov::w::replace>,
    groov::field<"DBG_I2C3_STOP", bool, 30u, 30u, groov::w::replace>,
    groov::field<"DBG_LPTIMER_STOP", bool, 31u, 31u, groov::w::replace>>,
  groov::reg<"APB1H_FZ",
             std::uint32_t,
             0xe004'2000 + 0xcu,
             groov::w::replace,
             groov::field<"DBG_I2C4_STOP", bool, 1u, 1u, groov::w::replace>>,
  groov::reg<
    "APB2_FZ",
    std::uint32_t,
    0xe004'2000 + 0x10u,
    groov::w::replace,
    groov::field<"DBG_TIM1_STOP", bool, 11u, 11u, groov::w::replace>,
    groov::field<"DBG_TIM8_STOP", bool, 13u, 13u, groov::w::replace>,
    groov::field<"DBG_TIM15_STOP", bool, 16u, 16u, groov::w::replace>,
    groov::field<"DBG_TIM16_STOP", bool, 17u, 17u, groov::w::replace>,
    groov::field<"DBG_TIM17_STOP", bool, 18u, 18u, groov::w::replace>,
    groov::field<"DBG_TIM20_STOP", bool, 20u, 20u, groov::w::replace>,
    groov::field<"DBG_HRTIM0_STOP", bool, 26u, 26u, groov::w::replace>,
    groov::field<"DBG_HRTIM1_STOP", bool, 27u, 27u, groov::w::replace>,
    groov::field<"DBG_HRTIM2_STOP", bool, 28u, 28u, groov::w::replace>,
    groov::field<"DBG_HRTIM3_STOP", bool, 29u, 29u, groov::w::replace>>>;
constexpr auto dbgmcu = dbgmcu_t{};

} // namespace mcu
