/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace fmc {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bcr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 21, access::ro>,
               groov::field<"cclken", bool, 20, 20>,
               groov::field<"cburstrw", bool, 19, 19>,
               groov::field<"reserved2", std::uint8_t, 18, 16, access::ro>,
               groov::field<"asyncwait", bool, 15, 15>,
               groov::field<"extmod", bool, 14, 14>,
               groov::field<"waiten", bool, 13, 13>,
               groov::field<"wren", bool, 12, 12>,
               groov::field<"waitcfg", bool, 11, 11>,
               groov::field<"reserved1", bool, 10, 10, access::ro>,
               groov::field<"waitpol", bool, 9, 9>,
               groov::field<"bursten", bool, 8, 8>,
               groov::field<"reserved0", bool, 7, 7, access::ro>,
               groov::field<"faccen", bool, 6, 6>,
               groov::field<"mwid", std::uint8_t, 5, 4>,
               groov::field<"mtyp", std::uint8_t, 3, 2>,
               groov::field<"muxen", bool, 1, 1>,
               groov::field<"mbken", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using btr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"busturn", std::uint8_t, 19, 16>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bcr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 20, access::ro>,
               groov::field<"cburstrw", bool, 19, 19>,
               groov::field<"reserved1", std::uint8_t, 18, 16, access::ro>,
               groov::field<"asyncwait", bool, 15, 15>,
               groov::field<"extmod", bool, 14, 14>,
               groov::field<"waiten", bool, 13, 13>,
               groov::field<"wren", bool, 12, 12>,
               groov::field<"waitcfg", bool, 11, 11>,
               groov::field<"wrapmod", bool, 10, 10>,
               groov::field<"waitpol", bool, 9, 9>,
               groov::field<"bursten", bool, 8, 8>,
               groov::field<"reserved0", bool, 7, 7, access::ro>,
               groov::field<"faccen", bool, 6, 6>,
               groov::field<"mwid", std::uint8_t, 5, 4>,
               groov::field<"mtyp", std::uint8_t, 3, 2>,
               groov::field<"muxen", bool, 1, 1>,
               groov::field<"mbken", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using btr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"busturn", std::uint8_t, 19, 16>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bcr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 20, access::ro>,
               groov::field<"cburstrw", bool, 19, 19>,
               groov::field<"reserved1", std::uint8_t, 18, 16, access::ro>,
               groov::field<"asyncwait", bool, 15, 15>,
               groov::field<"extmod", bool, 14, 14>,
               groov::field<"waiten", bool, 13, 13>,
               groov::field<"wren", bool, 12, 12>,
               groov::field<"waitcfg", bool, 11, 11>,
               groov::field<"wrapmod", bool, 10, 10>,
               groov::field<"waitpol", bool, 9, 9>,
               groov::field<"bursten", bool, 8, 8>,
               groov::field<"reserved0", bool, 7, 7, access::ro>,
               groov::field<"faccen", bool, 6, 6>,
               groov::field<"mwid", std::uint8_t, 5, 4>,
               groov::field<"mtyp", std::uint8_t, 3, 2>,
               groov::field<"muxen", bool, 1, 1>,
               groov::field<"mbken", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using btr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"busturn", std::uint8_t, 19, 16>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bcr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 20, access::ro>,
               groov::field<"cburstrw", bool, 19, 19>,
               groov::field<"reserved1", std::uint8_t, 18, 16, access::ro>,
               groov::field<"asyncwait", bool, 15, 15>,
               groov::field<"extmod", bool, 14, 14>,
               groov::field<"waiten", bool, 13, 13>,
               groov::field<"wren", bool, 12, 12>,
               groov::field<"waitcfg", bool, 11, 11>,
               groov::field<"wrapmod", bool, 10, 10>,
               groov::field<"waitpol", bool, 9, 9>,
               groov::field<"bursten", bool, 8, 8>,
               groov::field<"reserved0", bool, 7, 7, access::ro>,
               groov::field<"faccen", bool, 6, 6>,
               groov::field<"mwid", std::uint8_t, 5, 4>,
               groov::field<"mtyp", std::uint8_t, 3, 2>,
               groov::field<"muxen", bool, 1, 1>,
               groov::field<"mbken", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using btr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"busturn", std::uint8_t, 19, 16>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pcr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 20, access::ro>,
               groov::field<"eccps", std::uint8_t, 19, 17>,
               groov::field<"tar", std::uint8_t, 16, 13>,
               groov::field<"tclr", std::uint8_t, 12, 9>,
               groov::field<"reserved1", std::uint8_t, 8, 7, access::ro>,
               groov::field<"eccen", bool, 6, 6>,
               groov::field<"pwid", std::uint8_t, 5, 4>,
               groov::field<"ptyp", bool, 3, 3>,
               groov::field<"pbken", bool, 2, 2>,
               groov::field<"pwaiten", bool, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 7, access::ro>,
               groov::field<"fempt", bool, 6, 6, access::ro>,
               groov::field<"ifen", bool, 5, 5>,
               groov::field<"ilen", bool, 4, 4>,
               groov::field<"iren", bool, 3, 3>,
               groov::field<"ifs", bool, 2, 2>,
               groov::field<"ils", bool, 1, 1>,
               groov::field<"irs", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pmem2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"memhizx", std::uint8_t, 31, 24>,
               groov::field<"memholdx", std::uint8_t, 23, 16>,
               groov::field<"memwaitx", std::uint8_t, 15, 8>,
               groov::field<"memsetx", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using patt2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"atthizx", std::uint8_t, 31, 24>,
               groov::field<"attholdx", std::uint8_t, 23, 16>,
               groov::field<"attwaitx", std::uint8_t, 15, 8>,
               groov::field<"attsetx", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using eccr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"eccx", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pcr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 20, access::ro>,
               groov::field<"eccps", std::uint8_t, 19, 17>,
               groov::field<"tar", std::uint8_t, 16, 13>,
               groov::field<"tclr", std::uint8_t, 12, 9>,
               groov::field<"reserved1", std::uint8_t, 8, 7, access::ro>,
               groov::field<"eccen", bool, 6, 6>,
               groov::field<"pwid", std::uint8_t, 5, 4>,
               groov::field<"ptyp", bool, 3, 3>,
               groov::field<"pbken", bool, 2, 2>,
               groov::field<"pwaiten", bool, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 7, access::ro>,
               groov::field<"fempt", bool, 6, 6, access::ro>,
               groov::field<"ifen", bool, 5, 5>,
               groov::field<"ilen", bool, 4, 4>,
               groov::field<"iren", bool, 3, 3>,
               groov::field<"ifs", bool, 2, 2>,
               groov::field<"ils", bool, 1, 1>,
               groov::field<"irs", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pmem3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"memhizx", std::uint8_t, 31, 24>,
               groov::field<"memholdx", std::uint8_t, 23, 16>,
               groov::field<"memwaitx", std::uint8_t, 15, 8>,
               groov::field<"memsetx", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using patt3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"atthizx", std::uint8_t, 31, 24>,
               groov::field<"attholdx", std::uint8_t, 23, 16>,
               groov::field<"attwaitx", std::uint8_t, 15, 8>,
               groov::field<"attsetx", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using eccr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"eccx", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pcr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 20, access::ro>,
               groov::field<"eccps", std::uint8_t, 19, 17>,
               groov::field<"tar", std::uint8_t, 16, 13>,
               groov::field<"tclr", std::uint8_t, 12, 9>,
               groov::field<"reserved1", std::uint8_t, 8, 7, access::ro>,
               groov::field<"eccen", bool, 6, 6>,
               groov::field<"pwid", std::uint8_t, 5, 4>,
               groov::field<"ptyp", bool, 3, 3>,
               groov::field<"pbken", bool, 2, 2>,
               groov::field<"pwaiten", bool, 1, 1>,
               groov::field<"reserved0", bool, 0, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 7, access::ro>,
               groov::field<"fempt", bool, 6, 6, access::ro>,
               groov::field<"ifen", bool, 5, 5>,
               groov::field<"ilen", bool, 4, 4>,
               groov::field<"iren", bool, 3, 3>,
               groov::field<"ifs", bool, 2, 2>,
               groov::field<"ils", bool, 1, 1>,
               groov::field<"irs", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pmem4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"memhizx", std::uint8_t, 31, 24>,
               groov::field<"memholdx", std::uint8_t, 23, 16>,
               groov::field<"memwaitx", std::uint8_t, 15, 8>,
               groov::field<"memsetx", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using patt4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"atthizx", std::uint8_t, 31, 24>,
               groov::field<"attholdx", std::uint8_t, 23, 16>,
               groov::field<"attwaitx", std::uint8_t, 15, 8>,
               groov::field<"attsetx", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pio4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"iohizx", std::uint8_t, 31, 24>,
               groov::field<"ioholdx", std::uint8_t, 23, 16>,
               groov::field<"iowaitx", std::uint8_t, 15, 8>,
               groov::field<"iosetx", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bwtr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"reserved0", std::uint8_t, 19, 16, access::ro>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bwtr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"reserved0", std::uint8_t, 19, 16, access::ro>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bwtr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"reserved0", std::uint8_t, 19, 16, access::ro>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using bwtr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint8_t, 31, 30, access::ro>,
               groov::field<"accmod", std::uint8_t, 29, 28>,
               groov::field<"datlat", std::uint8_t, 27, 24>,
               groov::field<"clkdiv", std::uint8_t, 23, 20>,
               groov::field<"reserved0", std::uint8_t, 19, 16, access::ro>,
               groov::field<"datast", std::uint8_t, 15, 8>,
               groov::field<"addhld", std::uint8_t, 7, 4>,
               groov::field<"addset", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sdcr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 15, access::ro>,
               groov::field<"rpipe", std::uint8_t, 14, 13>,
               groov::field<"rburst", bool, 12, 12>,
               groov::field<"sdclk", std::uint8_t, 11, 10>,
               groov::field<"wp", bool, 9, 9>,
               groov::field<"cas", std::uint8_t, 8, 7>,
               groov::field<"nb", bool, 6, 6>,
               groov::field<"mwid", std::uint8_t, 5, 4>,
               groov::field<"nr", std::uint8_t, 3, 2>,
               groov::field<"nc", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sdcr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 15, access::ro>,
               groov::field<"rpipe", std::uint8_t, 14, 13>,
               groov::field<"rburst", bool, 12, 12>,
               groov::field<"sdclk", std::uint8_t, 11, 10>,
               groov::field<"wp", bool, 9, 9>,
               groov::field<"cas", std::uint8_t, 8, 7>,
               groov::field<"nb", bool, 6, 6>,
               groov::field<"mwid", std::uint8_t, 5, 4>,
               groov::field<"nr", std::uint8_t, 3, 2>,
               groov::field<"nc", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sdtr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 28, access::ro>,
               groov::field<"trcd", std::uint8_t, 27, 24>,
               groov::field<"trp", std::uint8_t, 23, 20>,
               groov::field<"twr", std::uint8_t, 19, 16>,
               groov::field<"trc", std::uint8_t, 15, 12>,
               groov::field<"tras", std::uint8_t, 11, 8>,
               groov::field<"txsr", std::uint8_t, 7, 4>,
               groov::field<"tmrd", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sdtr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint8_t, 31, 28, access::ro>,
               groov::field<"trcd", std::uint8_t, 27, 24>,
               groov::field<"trp", std::uint8_t, 23, 20>,
               groov::field<"twr", std::uint8_t, 19, 16>,
               groov::field<"trc", std::uint8_t, 15, 12>,
               groov::field<"tras", std::uint8_t, 11, 8>,
               groov::field<"txsr", std::uint8_t, 7, 4>,
               groov::field<"tmrd", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sdcmr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 22, access::ro>,
               groov::field<"mrd", std::uint16_t, 21, 9>,
               groov::field<"nrfs", std::uint8_t, 8, 5>,
               groov::field<"ctb1", bool, 4, 4, access::wo>,
               groov::field<"ctb2", bool, 3, 3, access::wo>,
               groov::field<"mode", std::uint8_t, 2, 0, access::wo>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sdrtr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 15, access::ro>,
               groov::field<"reie", bool, 14, 14>,
               groov::field<"count", std::uint16_t, 13, 1>,
               groov::field<"cre", bool, 0, 0, access::wo>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sdsr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"reserved0", std::uint32_t, 31, 6>,
               groov::field<"busy", bool, 5, 5>,
               groov::field<"modes2", std::uint8_t, 4, 3>,
               groov::field<"modes1", std::uint8_t, 2, 1>,
               groov::field<"re", bool, 0, 0>>;

} // namespace fmc
