/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace pwr {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_cr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 6, access::ro>,
               groov::field<"fpd_slp", bool, 5, 5>,
               groov::field<"reserved0", bool, 4, 4, access::ro>,
               groov::field<"fpd_stop", bool, 3, 3>,
               groov::field<"lpms", std::uint8_t, 2, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_cr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 16, access::ro>,
               groov::field<"eiwul", bool, 15, 15>,
               groov::field<"reserved2", std::uint8_t, 14, 11, access::ro>,
               groov::field<"apc", bool, 10, 10>,
               groov::field<"reserved1", std::uint8_t, 9, 6, access::ro>,
               groov::field<"ewup6", bool, 5, 5>,
               groov::field<"reserved0", bool, 4, 4, access::ro>,
               groov::field<"ewup4", bool, 3, 3>,
               groov::field<"ewup3", bool, 2, 2>,
               groov::field<"ewup2", bool, 1, 1>,
               groov::field<"ewup1", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_cr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 6, access::ro>,
               groov::field<"wp6", bool, 5, 5>,
               groov::field<"reserved0", bool, 4, 4, access::ro>,
               groov::field<"wp4", bool, 3, 3>,
               groov::field<"wp3", bool, 2, 2>,
               groov::field<"wp2", bool, 1, 1>,
               groov::field<"wp1", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_sr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved3", std::uint16_t, 31, 16, access::ro>,
               groov::field<"wufi", bool, 15, 15, access::ro>,
               groov::field<"reserved2", std::uint8_t, 14, 9, access::ro>,
               groov::field<"sbf", bool, 8, 8, access::ro>,
               groov::field<"reserved1", std::uint8_t, 7, 6, access::ro>,
               groov::field<"wuf6", bool, 5, 5, access::ro>,
               groov::field<"reserved0", bool, 4, 4, access::ro>,
               groov::field<"wuf4", bool, 3, 3, access::ro>,
               groov::field<"wuf3", bool, 2, 2, access::ro>,
               groov::field<"wuf2", bool, 1, 1, access::ro>,
               groov::field<"wuf1", bool, 0, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_sr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint32_t, 31, 8, access::ro>,
               groov::field<"flash_rdy", bool, 7, 7, access::ro>,
               groov::field<"reserved0", std::uint8_t, 6, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_scr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint32_t, 31, 9, access::ro>,
               groov::field<"csbf", bool, 8, 8, access::wo>,
               groov::field<"reserved1", std::uint8_t, 7, 6, access::ro>,
               groov::field<"cwuf6", bool, 5, 5, access::wo>,
               groov::field<"reserved0", bool, 4, 4, access::ro>,
               groov::field<"cwuf4", bool, 3, 3, access::wo>,
               groov::field<"cwuf3", bool, 2, 2, access::wo>,
               groov::field<"cwuf2", bool, 1, 1, access::wo>,
               groov::field<"cwuf1", bool, 0, 0, access::wo>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pucra_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"pu15", bool, 15, 15>,
               groov::field<"pu14", bool, 14, 14>,
               groov::field<"pu13", bool, 13, 13>,
               groov::field<"pu12", bool, 12, 12>,
               groov::field<"pu11", bool, 11, 11>,
               groov::field<"pu10", bool, 10, 10>,
               groov::field<"pu9", bool, 9, 9>,
               groov::field<"pu8", bool, 8, 8>,
               groov::field<"pu7", bool, 7, 7>,
               groov::field<"pu6", bool, 6, 6>,
               groov::field<"pu5", bool, 5, 5>,
               groov::field<"pu4", bool, 4, 4>,
               groov::field<"pu3", bool, 3, 3>,
               groov::field<"pu2", bool, 2, 2>,
               groov::field<"pu1", bool, 1, 1>,
               groov::field<"pu0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pdcra_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"pd15", bool, 15, 15>,
               groov::field<"pd14", bool, 14, 14>,
               groov::field<"pd13", bool, 13, 13>,
               groov::field<"pd12", bool, 12, 12>,
               groov::field<"pd11", bool, 11, 11>,
               groov::field<"pd10", bool, 10, 10>,
               groov::field<"pd9", bool, 9, 9>,
               groov::field<"pd8", bool, 8, 8>,
               groov::field<"pd7", bool, 7, 7>,
               groov::field<"pd6", bool, 6, 6>,
               groov::field<"pd5", bool, 5, 5>,
               groov::field<"pd4", bool, 4, 4>,
               groov::field<"pd3", bool, 3, 3>,
               groov::field<"pd2", bool, 2, 2>,
               groov::field<"pd1", bool, 1, 1>,
               groov::field<"pd0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pucrb_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"pu15", bool, 15, 15>,
               groov::field<"pu14", bool, 14, 14>,
               groov::field<"pu13", bool, 13, 13>,
               groov::field<"pu12", bool, 12, 12>,
               groov::field<"pu11", bool, 11, 11>,
               groov::field<"pu10", bool, 10, 10>,
               groov::field<"pu9", bool, 9, 9>,
               groov::field<"pu8", bool, 8, 8>,
               groov::field<"pu7", bool, 7, 7>,
               groov::field<"pu6", bool, 6, 6>,
               groov::field<"pu5", bool, 5, 5>,
               groov::field<"pu4", bool, 4, 4>,
               groov::field<"pu3", bool, 3, 3>,
               groov::field<"pu2", bool, 2, 2>,
               groov::field<"pu1", bool, 1, 1>,
               groov::field<"pu0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pdcrb_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"pd15", bool, 15, 15>,
               groov::field<"pd14", bool, 14, 14>,
               groov::field<"pd13", bool, 13, 13>,
               groov::field<"pd12", bool, 12, 12>,
               groov::field<"pd11", bool, 11, 11>,
               groov::field<"pd10", bool, 10, 10>,
               groov::field<"pd9", bool, 9, 9>,
               groov::field<"pd8", bool, 8, 8>,
               groov::field<"pd7", bool, 7, 7>,
               groov::field<"pd6", bool, 6, 6>,
               groov::field<"pd5", bool, 5, 5>,
               groov::field<"pd4", bool, 4, 4>,
               groov::field<"pd3", bool, 3, 3>,
               groov::field<"pd2", bool, 2, 2>,
               groov::field<"pd1", bool, 1, 1>,
               groov::field<"pd0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pucrc_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 16, access::ro>,
               groov::field<"pu15", bool, 15, 15>,
               groov::field<"pu14", bool, 14, 14>,
               groov::field<"pu13", bool, 13, 13>,
               groov::field<"reserved1", std::uint8_t, 12, 8, access::ro>,
               groov::field<"pu7", bool, 7, 7>,
               groov::field<"pu6", bool, 6, 6>,
               groov::field<"reserved0", std::uint8_t, 5, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pdcrc_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 16, access::ro>,
               groov::field<"pd15", bool, 15, 15>,
               groov::field<"pd14", bool, 14, 14>,
               groov::field<"pd13", bool, 13, 13>,
               groov::field<"reserved1", std::uint8_t, 12, 8, access::ro>,
               groov::field<"pd7", bool, 7, 7>,
               groov::field<"pd6", bool, 6, 6>,
               groov::field<"reserved0", std::uint8_t, 5, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pucrd_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 4, access::ro>,
               groov::field<"pu3", bool, 3, 3>,
               groov::field<"pu2", bool, 2, 2>,
               groov::field<"pu1", bool, 1, 1>,
               groov::field<"pu0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pdcrd_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 4, access::ro>,
               groov::field<"pd3", bool, 3, 3>,
               groov::field<"pd2", bool, 2, 2>,
               groov::field<"pd1", bool, 1, 1>,
               groov::field<"pd0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pucrf_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, access::ro>,
               groov::field<"pu2", bool, 2, 2>,
               groov::field<"pu1", bool, 1, 1>,
               groov::field<"pu0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pwr_pdcrf_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 3, access::ro>,
               groov::field<"pd2", bool, 2, 2>,
               groov::field<"pd1", bool, 1, 1>,
               groov::field<"pd0", bool, 0, 0>>;

} // namespace pwr
