/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32h750x/registers/bdma.hpp>

namespace stm32::stm32h750x {

namespace bdma {
  using bdma_isr_tt = regs::bdma_bdma_isr_v1_tt;
  using bdma_ifcr_tt = regs::bdma_bdma_ifcr_v1_tt;
  using bdma_ccr1_tt = regs::bdma_bdma_ccr1_v1_tt;
  using bdma_cndtr1_tt = regs::bdma_bdma_cndtr1_v1_tt;
  using bdma_cpar1_tt = regs::bdma_bdma_cpar1_v1_tt;
  using bdma_cmar1_tt = regs::bdma_bdma_cmar1_v1_tt;
  using bdma_ccr2_tt = regs::bdma_bdma_ccr2_v1_tt;
  using bdma_cndtr2_tt = regs::bdma_bdma_cndtr2_v1_tt;
  using bdma_cpar2_tt = regs::bdma_bdma_cpar2_v1_tt;
  using bdma_cmar2_tt = regs::bdma_bdma_cmar2_v1_tt;
  using bdma_ccr3_tt = regs::bdma_bdma_ccr3_v1_tt;
  using bdma_cndtr3_tt = regs::bdma_bdma_cndtr3_v1_tt;
  using bdma_cpar3_tt = regs::bdma_bdma_cpar3_v1_tt;
  using bdma_cmar3_tt = regs::bdma_bdma_cmar3_v1_tt;
  using bdma_ccr4_tt = regs::bdma_bdma_ccr4_v1_tt;
  using bdma_cndtr4_tt = regs::bdma_bdma_cndtr4_v1_tt;
  using bdma_cpar4_tt = regs::bdma_bdma_cpar4_v1_tt;
  using bdma_cmar4_tt = regs::bdma_bdma_cmar4_v1_tt;
  using bdma_ccr5_tt = regs::bdma_bdma_ccr5_v1_tt;
  using bdma_cndtr5_tt = regs::bdma_bdma_cndtr5_v1_tt;
  using bdma_cpar5_tt = regs::bdma_bdma_cpar5_v1_tt;
  using bdma_cmar5_tt = regs::bdma_bdma_cmar5_v1_tt;
  using bdma_ccr6_tt = regs::bdma_bdma_ccr6_v1_tt;
  using bdma_cndtr6_tt = regs::bdma_bdma_cndtr6_v1_tt;
  using bdma_cpar6_tt = regs::bdma_bdma_cpar6_v1_tt;
  using bdma_cmar6_tt = regs::bdma_bdma_cmar6_v1_tt;
  using bdma_ccr7_tt = regs::bdma_bdma_ccr7_v1_tt;
  using bdma_cndtr7_tt = regs::bdma_bdma_cndtr7_v1_tt;
  using bdma_cpar7_tt = regs::bdma_bdma_cpar7_v1_tt;
  using bdma_cmar7_tt = regs::bdma_bdma_cmar7_v1_tt;
  using bdma_ccr8_tt = regs::bdma_bdma_ccr8_v1_tt;
  using bdma_cndtr8_tt = regs::bdma_bdma_cndtr8_v1_tt;
  using bdma_cpar8_tt = regs::bdma_bdma_cpar8_v1_tt;
  using bdma_cmar8_tt = regs::bdma_bdma_cmar8_v1_tt;

  template <std::uint32_t baseaddress>
  using bdma_t =
    groov::group<"bdma",
                 groov::mmio_bus<>,
                 bdma_isr_tt<"bdma_isr", baseaddress, 0x0>,
                 bdma_ifcr_tt<"bdma_ifcr", baseaddress, 0x4>,
                 bdma_ccr1_tt<"bdma_ccr1", baseaddress, 0x8>,
                 bdma_cndtr1_tt<"bdma_cndtr1", baseaddress, 0xc>,
                 bdma_cpar1_tt<"bdma_cpar1", baseaddress, 0x10>,
                 bdma_cmar1_tt<"bdma_cmar1", baseaddress, 0x14>,
                 bdma_ccr2_tt<"bdma_ccr2", baseaddress, 0x1c>,
                 bdma_cndtr2_tt<"bdma_cndtr2", baseaddress, 0x20>,
                 bdma_cpar2_tt<"bdma_cpar2", baseaddress, 0x24>,
                 bdma_cmar2_tt<"bdma_cmar2", baseaddress, 0x28>,
                 bdma_ccr3_tt<"bdma_ccr3", baseaddress, 0x30>,
                 bdma_cndtr3_tt<"bdma_cndtr3", baseaddress, 0x34>,
                 bdma_cpar3_tt<"bdma_cpar3", baseaddress, 0x38>,
                 bdma_cmar3_tt<"bdma_cmar3", baseaddress, 0x3c>,
                 bdma_ccr4_tt<"bdma_ccr4", baseaddress, 0x44>,
                 bdma_cndtr4_tt<"bdma_cndtr4", baseaddress, 0x48>,
                 bdma_cpar4_tt<"bdma_cpar4", baseaddress, 0x4c>,
                 bdma_cmar4_tt<"bdma_cmar4", baseaddress, 0x50>,
                 bdma_ccr5_tt<"bdma_ccr5", baseaddress, 0x58>,
                 bdma_cndtr5_tt<"bdma_cndtr5", baseaddress, 0x5c>,
                 bdma_cpar5_tt<"bdma_cpar5", baseaddress, 0x60>,
                 bdma_cmar5_tt<"bdma_cmar5", baseaddress, 0x64>,
                 bdma_ccr6_tt<"bdma_ccr6", baseaddress, 0x6c>,
                 bdma_cndtr6_tt<"bdma_cndtr6", baseaddress, 0x70>,
                 bdma_cpar6_tt<"bdma_cpar6", baseaddress, 0x74>,
                 bdma_cmar6_tt<"bdma_cmar6", baseaddress, 0x78>,
                 bdma_ccr7_tt<"bdma_ccr7", baseaddress, 0x80>,
                 bdma_cndtr7_tt<"bdma_cndtr7", baseaddress, 0x84>,
                 bdma_cpar7_tt<"bdma_cpar7", baseaddress, 0x88>,
                 bdma_cmar7_tt<"bdma_cmar7", baseaddress, 0x8c>,
                 bdma_ccr8_tt<"bdma_ccr8", baseaddress, 0x94>,
                 bdma_cndtr8_tt<"bdma_cndtr8", baseaddress, 0x98>,
                 bdma_cpar8_tt<"bdma_cpar8", baseaddress, 0x9c>,
                 bdma_cmar8_tt<"bdma_cmar8", baseaddress, 0xa0>>;

} // namespace bdma

} // namespace stm32::stm32h750x
