/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace sec_cordic {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using csr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"rrdy", bool, 31, 31, access::ro>,
               groov::field<"reserved1", std::uint8_t, 30, 23, access::ro>,
               groov::field<"argsize", bool, 22, 22>,
               groov::field<"ressize", bool, 21, 21>,
               groov::field<"nargs", bool, 20, 20>,
               groov::field<"nres", bool, 19, 19>,
               groov::field<"dmawen", bool, 18, 18>,
               groov::field<"dmaren", bool, 17, 17>,
               groov::field<"ien", bool, 16, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 11, access::ro>,
               groov::field<"scale", std::uint8_t, 10, 8>,
               groov::field<"precision", std::uint8_t, 7, 4>,
               groov::field<"func", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using wdata_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::wo,
               groov::field<"arg", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using rdata_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"res", std::uint32_t, 31, 0>>;

} // namespace sec_cordic
