/* File autogenerated with
 * svd2groov, version: 0.1.0, branch: dev, hash: ce7ae6e
 */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace dsi {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vr_tt = groov::reg<name,
                               std::uint32_t,
                               baseaddress + offset,
                               access::ro,
                               groov::field<"VERSION", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_cr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 1, access::ro>,
               groov::field<"EN", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_ccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"TOCKDIV", std::uint8_t, 15, 8>,
               groov::field<"TXECKDIV", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lvcidr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 2, access::ro>,
               groov::field<"VCID", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lcolcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint32_t, 31, 9, access::ro>,
               groov::field<"LPE", bool, 8, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 4, access::ro>,
               groov::field<"COLC", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lpcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 3, access::ro>,
               groov::field<"HSP", bool, 2, 2>,
               groov::field<"VSP", bool, 1, 1>,
               groov::field<"DEP", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lpmcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint8_t, 31, 24, access::ro>,
               groov::field<"LPSIZE", std::uint8_t, 23, 16>,
               groov::field<"RESERVED0", std::uint8_t, 15, 8, access::ro>,
               groov::field<"VLPSIZE", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_pcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 5, access::ro>,
               groov::field<"CRCRXE", bool, 4, 4>,
               groov::field<"ECCRXE", bool, 3, 3>,
               groov::field<"BTAE", bool, 2, 2>,
               groov::field<"ETRXE", bool, 1, 1>,
               groov::field<"ETTXE", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_gvcidr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 2, access::ro>,
               groov::field<"VCID", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_mcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 1, access::ro>,
               groov::field<"CMDM", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vmcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED3", std::uint8_t, 31, 25, access::ro>,
               groov::field<"PGO", bool, 24, 24>,
               groov::field<"RESERVED2", std::uint8_t, 23, 21, access::ro>,
               groov::field<"PGM", bool, 20, 20>,
               groov::field<"RESERVED1", std::uint8_t, 19, 17, access::ro>,
               groov::field<"PGE", bool, 16, 16>,
               groov::field<"LPCE", bool, 15, 15>,
               groov::field<"FBTAAE", bool, 14, 14>,
               groov::field<"LPHFPE", bool, 13, 13>,
               groov::field<"LPHBPE", bool, 12, 12>,
               groov::field<"LPVAE", bool, 11, 11>,
               groov::field<"LPVFPE", bool, 10, 10>,
               groov::field<"LPVBPE", bool, 9, 9>,
               groov::field<"LPVSAE", bool, 8, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 2, access::ro>,
               groov::field<"VMT", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vpcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 14, access::ro>,
               groov::field<"VPSIZE", std::uint16_t, 13, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 13, access::ro>,
               groov::field<"NUMC", std::uint16_t, 12, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vnpcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 13, access::ro>,
               groov::field<"NPSIZE", std::uint16_t, 12, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vhsacr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 12, access::ro>,
               groov::field<"HSA", std::uint16_t, 11, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vhbpcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 12, access::ro>,
               groov::field<"HBP", std::uint16_t, 11, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vlcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 15, access::ro>,
               groov::field<"HLINE", std::uint16_t, 14, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvsacr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 10, access::ro>,
               groov::field<"VSA", std::uint16_t, 9, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvbpcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 10, access::ro>,
               groov::field<"VBP", std::uint16_t, 9, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvfpcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 10, access::ro>,
               groov::field<"VFP", std::uint16_t, 9, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvacr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 14, access::ro>,
               groov::field<"VA", std::uint16_t, 13, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"CMDSIZE", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_cmcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED3", std::uint8_t, 31, 25, access::ro>,
               groov::field<"MRDPS", bool, 24, 24>,
               groov::field<"RESERVED2", std::uint8_t, 23, 20, access::ro>,
               groov::field<"DLWTX", bool, 19, 19>,
               groov::field<"DSR0TX", bool, 18, 18>,
               groov::field<"DSW1TX", bool, 17, 17>,
               groov::field<"DSW0TX", bool, 16, 16>,
               groov::field<"RESERVED1", bool, 15, 15, access::ro>,
               groov::field<"GLWTX", bool, 14, 14>,
               groov::field<"GSR2TX", bool, 13, 13>,
               groov::field<"GSR1TX", bool, 12, 12>,
               groov::field<"GSR0TX", bool, 11, 11>,
               groov::field<"GSW2TX", bool, 10, 10>,
               groov::field<"GSW1TX", bool, 9, 9>,
               groov::field<"GSW0TX", bool, 8, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 2, access::ro>,
               groov::field<"ARE", bool, 1, 1>,
               groov::field<"TEARE", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_ghcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint8_t, 31, 24, access::ro>,
               groov::field<"WCMSB", std::uint8_t, 23, 16>,
               groov::field<"WCLSB", std::uint8_t, 15, 8>,
               groov::field<"VCID", std::uint8_t, 7, 6>,
               groov::field<"DT", std::uint8_t, 5, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_gpdr_tt = groov::reg<name,
                                 std::uint32_t,
                                 baseaddress + offset,
                                 access::rw,
                                 groov::field<"DATA4", std::uint8_t, 31, 24>,
                                 groov::field<"DATA3", std::uint8_t, 23, 16>,
                                 groov::field<"DATA2", std::uint8_t, 15, 8>,
                                 groov::field<"DATA1", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_gpsr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 7>,
               groov::field<"RCB", bool, 6, 6>,
               groov::field<"PRDFF", bool, 5, 5>,
               groov::field<"PRDFE", bool, 4, 4>,
               groov::field<"PWRFF", bool, 3, 3>,
               groov::field<"PWRFE", bool, 2, 2>,
               groov::field<"CMDFF", bool, 1, 1>,
               groov::field<"CMDFE", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_tccr0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"HSTX_TOCNT", std::uint16_t, 31, 16>,
               groov::field<"LPRX_TOCNT", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_tccr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"HSRD_TOCNT", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_tccr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"LPRD_TOCNT", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_tccr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint8_t, 31, 25, access::ro>,
               groov::field<"PM", bool, 24, 24>,
               groov::field<"RESERVED0", std::uint8_t, 23, 16, access::ro>,
               groov::field<"HSWR_TOCNT", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_tccr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"LSWR_TOCNT", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_tccr5_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint16_t, 31, 16, access::ro>,
               groov::field<"BTA_TOCNT", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_clcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 2, access::ro>,
               groov::field<"ACR", bool, 1, 1>,
               groov::field<"DPCC", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_cltcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint8_t, 31, 26, access::ro>,
               groov::field<"HS2LP_TIME", std::uint16_t, 25, 16>,
               groov::field<"RESERVED0", std::uint8_t, 15, 10, access::ro>,
               groov::field<"LP2HS_TIME", std::uint16_t, 9, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_dltcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"HS2LP_TIME", std::uint8_t, 31, 24>,
               groov::field<"LP2HS_TIME", std::uint8_t, 23, 16>,
               groov::field<"RESERVED0", bool, 15, 15, access::ro>,
               groov::field<"MRD_TIME", std::uint16_t, 14, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_pctlr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint32_t, 31, 3, access::ro>,
               groov::field<"CKE", bool, 2, 2>,
               groov::field<"DEN", bool, 1, 1>,
               groov::field<"RESERVED0", bool, 0, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_pconfr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint16_t, 31, 16, access::ro>,
               groov::field<"SW_TIME", std::uint8_t, 15, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 2, access::ro>,
               groov::field<"NL", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_pucr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 4, access::ro>,
               groov::field<"UEDL", bool, 3, 3>,
               groov::field<"URDL", bool, 2, 2>,
               groov::field<"UECL", bool, 1, 1>,
               groov::field<"URCL", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_pttcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 4, access::ro>,
               groov::field<"TX_TRIG", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_psr_tt = groov::reg<name,
                                std::uint32_t,
                                baseaddress + offset,
                                access::ro,
                                groov::field<"RESERVED1", std::uint32_t, 31, 9>,
                                groov::field<"UAN1", bool, 8, 8>,
                                groov::field<"PSS1", bool, 7, 7>,
                                groov::field<"RUE0", bool, 6, 6>,
                                groov::field<"UAN0", bool, 5, 5>,
                                groov::field<"PSS0", bool, 4, 4>,
                                groov::field<"UANC", bool, 3, 3>,
                                groov::field<"PSSC", bool, 2, 2>,
                                groov::field<"PD", bool, 1, 1>,
                                groov::field<"RESERVED0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_isr0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint16_t, 31, 21>,
               groov::field<"PE4", bool, 20, 20>,
               groov::field<"PE3", bool, 19, 19>,
               groov::field<"PE2", bool, 18, 18>,
               groov::field<"PE1", bool, 17, 17>,
               groov::field<"PE0", bool, 16, 16>,
               groov::field<"AE15", bool, 15, 15>,
               groov::field<"AE14", bool, 14, 14>,
               groov::field<"AE13", bool, 13, 13>,
               groov::field<"AE12", bool, 12, 12>,
               groov::field<"AE11", bool, 11, 11>,
               groov::field<"AE10", bool, 10, 10>,
               groov::field<"AE9", bool, 9, 9>,
               groov::field<"AE8", bool, 8, 8>,
               groov::field<"AE7", bool, 7, 7>,
               groov::field<"AE6", bool, 6, 6>,
               groov::field<"AE5", bool, 5, 5>,
               groov::field<"AE4", bool, 4, 4>,
               groov::field<"AE3", bool, 3, 3>,
               groov::field<"AE2", bool, 2, 2>,
               groov::field<"AE1", bool, 1, 1>,
               groov::field<"AE0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_isr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 13>,
               groov::field<"GPRXE", bool, 12, 12>,
               groov::field<"GPRDE", bool, 11, 11>,
               groov::field<"GPTXE", bool, 10, 10>,
               groov::field<"GPWRE", bool, 9, 9>,
               groov::field<"GCWRE", bool, 8, 8>,
               groov::field<"LPWRE", bool, 7, 7>,
               groov::field<"EOTPE", bool, 6, 6>,
               groov::field<"PSE", bool, 5, 5>,
               groov::field<"CRCE", bool, 4, 4>,
               groov::field<"ECCME", bool, 3, 3>,
               groov::field<"ECCSE", bool, 2, 2>,
               groov::field<"TOLPRX", bool, 1, 1>,
               groov::field<"TOHSTX", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_ier0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint16_t, 31, 21, access::ro>,
               groov::field<"PE4IE", bool, 20, 20>,
               groov::field<"PE3IE", bool, 19, 19>,
               groov::field<"PE2IE", bool, 18, 18>,
               groov::field<"PE1IE", bool, 17, 17>,
               groov::field<"PE0IE", bool, 16, 16>,
               groov::field<"AE15IE", bool, 15, 15>,
               groov::field<"AE14IE", bool, 14, 14>,
               groov::field<"AE13IE", bool, 13, 13>,
               groov::field<"AE12IE", bool, 12, 12>,
               groov::field<"AE11IE", bool, 11, 11>,
               groov::field<"AE10IE", bool, 10, 10>,
               groov::field<"AE9IE", bool, 9, 9>,
               groov::field<"AE8IE", bool, 8, 8>,
               groov::field<"AE7IE", bool, 7, 7>,
               groov::field<"AE6IE", bool, 6, 6>,
               groov::field<"AE5IE", bool, 5, 5>,
               groov::field<"AE4IE", bool, 4, 4>,
               groov::field<"AE3IE", bool, 3, 3>,
               groov::field<"AE2IE", bool, 2, 2>,
               groov::field<"AE1IE", bool, 1, 1>,
               groov::field<"AE0IE", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_ier1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 13, access::ro>,
               groov::field<"GPRXEIE", bool, 12, 12>,
               groov::field<"GPRDEIE", bool, 11, 11>,
               groov::field<"GPTXEIE", bool, 10, 10>,
               groov::field<"GPWREIE", bool, 9, 9>,
               groov::field<"GCWREIE", bool, 8, 8>,
               groov::field<"LPWREIE", bool, 7, 7>,
               groov::field<"EOTPEIE", bool, 6, 6>,
               groov::field<"PSEIE", bool, 5, 5>,
               groov::field<"CRCEIE", bool, 4, 4>,
               groov::field<"ECCMEIE", bool, 3, 3>,
               groov::field<"ECCSEIE", bool, 2, 2>,
               groov::field<"TOLPRXIE", bool, 1, 1>,
               groov::field<"TOHSTXIE", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_fir0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::wo,
               groov::field<"RESERVED0", std::uint16_t, 31, 21, access::ro>,
               groov::field<"FPE4", bool, 20, 20>,
               groov::field<"FPE3", bool, 19, 19>,
               groov::field<"FPE2", bool, 18, 18>,
               groov::field<"FPE1", bool, 17, 17>,
               groov::field<"FPE0", bool, 16, 16>,
               groov::field<"FAE15", bool, 15, 15>,
               groov::field<"FAE14", bool, 14, 14>,
               groov::field<"FAE13", bool, 13, 13>,
               groov::field<"FAE12", bool, 12, 12>,
               groov::field<"FAE11", bool, 11, 11>,
               groov::field<"FAE10", bool, 10, 10>,
               groov::field<"FAE9", bool, 9, 9>,
               groov::field<"FAE8", bool, 8, 8>,
               groov::field<"FAE7", bool, 7, 7>,
               groov::field<"FAE6", bool, 6, 6>,
               groov::field<"FAE5", bool, 5, 5>,
               groov::field<"FAE4", bool, 4, 4>,
               groov::field<"FAE3", bool, 3, 3>,
               groov::field<"FAE2", bool, 2, 2>,
               groov::field<"FAE1", bool, 1, 1>,
               groov::field<"FAE0", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_fir1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::wo,
               groov::field<"RESERVED0", std::uint32_t, 31, 13, access::ro>,
               groov::field<"FGPRXE", bool, 12, 12>,
               groov::field<"FGPRDE", bool, 11, 11>,
               groov::field<"FGPTXE", bool, 10, 10>,
               groov::field<"FGPWRE", bool, 9, 9>,
               groov::field<"FGCWRE", bool, 8, 8>,
               groov::field<"FLPWRE", bool, 7, 7>,
               groov::field<"FEOTPE", bool, 6, 6>,
               groov::field<"FPSE", bool, 5, 5>,
               groov::field<"FCRCE", bool, 4, 4>,
               groov::field<"FECCME", bool, 3, 3>,
               groov::field<"FECCSE", bool, 2, 2>,
               groov::field<"FTOLPRX", bool, 1, 1>,
               groov::field<"FTOHSTX", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vscr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint32_t, 31, 9, access::ro>,
               groov::field<"UR", bool, 8, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 1, access::ro>,
               groov::field<"EN", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lcvcidr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 2>,
               groov::field<"VCID", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lcccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED1", std::uint32_t, 31, 9>,
               groov::field<"LPE", bool, 8, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 4>,
               groov::field<"COLC", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_lpmccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED1", std::uint8_t, 31, 24>,
               groov::field<"LPSIZE", std::uint8_t, 23, 16>,
               groov::field<"RESERVED0", std::uint8_t, 15, 8>,
               groov::field<"VLPSIZE", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vmccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 10>,
               groov::field<"LPCE", bool, 9, 9>,
               groov::field<"FBTAAE", bool, 8, 8>,
               groov::field<"LPHFE", bool, 7, 7>,
               groov::field<"LPHBPE", bool, 6, 6>,
               groov::field<"LPVAE", bool, 5, 5>,
               groov::field<"LPVFPE", bool, 4, 4>,
               groov::field<"LPVBPE", bool, 3, 3>,
               groov::field<"LPVSAE", bool, 2, 2>,
               groov::field<"VMT", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vpccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 14>,
               groov::field<"VPSIZE", std::uint16_t, 13, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vcccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 13>,
               groov::field<"NUMC", std::uint16_t, 12, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vnpccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 13>,
               groov::field<"NPSIZE", std::uint16_t, 12, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vhsaccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 12>,
               groov::field<"HSA", std::uint16_t, 11, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vhbpccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 12>,
               groov::field<"HBP", std::uint16_t, 11, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vlccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 15>,
               groov::field<"HLINE", std::uint16_t, 14, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvsaccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 10>,
               groov::field<"VSA", std::uint16_t, 9, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvbpccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 10>,
               groov::field<"VBP", std::uint16_t, 9, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvfpccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 10>,
               groov::field<"VFP", std::uint16_t, 9, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_vvaccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED0", std::uint32_t, 31, 14>,
               groov::field<"VA", std::uint16_t, 13, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wcfgr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 8, access::ro>,
               groov::field<"VSPOL", bool, 7, 7>,
               groov::field<"AR", bool, 6, 6>,
               groov::field<"TEPOL", bool, 5, 5>,
               groov::field<"TESRC", bool, 4, 4>,
               groov::field<"COLMUX", std::uint8_t, 3, 1>,
               groov::field<"DSIM", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 4, access::ro>,
               groov::field<"DSIEN", bool, 3, 3>,
               groov::field<"LTDCEN", bool, 2, 2>,
               groov::field<"SHTDN", bool, 1, 1>,
               groov::field<"COLM", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wier_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED2", std::uint32_t, 31, 14, access::ro>,
               groov::field<"RRIE", bool, 13, 13>,
               groov::field<"RESERVED1", std::uint8_t, 12, 11, access::ro>,
               groov::field<"PLLUIE", bool, 10, 10>,
               groov::field<"PLLLIE", bool, 9, 9>,
               groov::field<"RESERVED0", std::uint8_t, 8, 2, access::ro>,
               groov::field<"ERIE", bool, 1, 1>,
               groov::field<"TEIE", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wisr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"RESERVED2", std::uint32_t, 31, 14>,
               groov::field<"RRIF", bool, 13, 13>,
               groov::field<"RRS", bool, 12, 12>,
               groov::field<"RESERVED1", bool, 11, 11>,
               groov::field<"PLLUIF", bool, 10, 10>,
               groov::field<"PLLLIF", bool, 9, 9>,
               groov::field<"PLLLS", bool, 8, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 3>,
               groov::field<"BUSY", bool, 2, 2>,
               groov::field<"ERIF", bool, 1, 1>,
               groov::field<"TEIF", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wifcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED2", std::uint32_t, 31, 14, access::ro>,
               groov::field<"CRRIF", bool, 13, 13>,
               groov::field<"RESERVED1", std::uint8_t, 12, 11, access::ro>,
               groov::field<"CPLLUIF", bool, 10, 10>,
               groov::field<"CPLLLIF", bool, 9, 9>,
               groov::field<"RESERVED0", std::uint8_t, 8, 2, access::ro>,
               groov::field<"CERIF", bool, 1, 1>,
               groov::field<"CTEIF", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wpcr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED2", std::uint8_t, 31, 28, access::ro>,
               groov::field<"TCLKPOSTEN", bool, 27, 27>,
               groov::field<"TLPXCEN", bool, 26, 26>,
               groov::field<"THSEXITEN", bool, 25, 25>,
               groov::field<"TLPXDEN", bool, 24, 24>,
               groov::field<"THSZEROEN", bool, 23, 23>,
               groov::field<"THSTRAILEN", bool, 22, 22>,
               groov::field<"THSPREPEN", bool, 21, 21>,
               groov::field<"TCLKZEROEN", bool, 20, 20>,
               groov::field<"TCLKPREPEN", bool, 19, 19>,
               groov::field<"PDEN", bool, 18, 18>,
               groov::field<"RESERVED1", bool, 17, 17, access::ro>,
               groov::field<"TDDL", bool, 16, 16>,
               groov::field<"RESERVED0", bool, 15, 15, access::ro>,
               groov::field<"CDOFFDL", bool, 14, 14>,
               groov::field<"FTXSMDL", bool, 13, 13>,
               groov::field<"FTXSMCL", bool, 12, 12>,
               groov::field<"HSIDL1", bool, 11, 11>,
               groov::field<"HSIDL0", bool, 10, 10>,
               groov::field<"HSICL", bool, 9, 9>,
               groov::field<"SWDL1", bool, 8, 8>,
               groov::field<"SWDL0", bool, 7, 7>,
               groov::field<"SWCL", bool, 6, 6>,
               groov::field<"UIX4", std::uint8_t, 5, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wpcr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED5", std::uint8_t, 31, 27, access::ro>,
               groov::field<"LPRXFT", std::uint8_t, 26, 25>,
               groov::field<"RESERVED4", std::uint8_t, 24, 23, access::ro>,
               groov::field<"FLPRXLPM", bool, 22, 22>,
               groov::field<"RESERVED3", std::uint8_t, 21, 20, access::ro>,
               groov::field<"HSTXSRCDL", std::uint8_t, 19, 18>,
               groov::field<"HSTXSRCCL", std::uint8_t, 17, 16>,
               groov::field<"RESERVED2", std::uint8_t, 15, 13, access::ro>,
               groov::field<"SDCC", bool, 12, 12>,
               groov::field<"RESERVED1", std::uint8_t, 11, 10, access::ro>,
               groov::field<"LPSRDL", std::uint8_t, 9, 8>,
               groov::field<"LPSRCL", std::uint8_t, 7, 6>,
               groov::field<"RESERVED0", std::uint8_t, 5, 4, access::ro>,
               groov::field<"HSTXDLL", std::uint8_t, 3, 2>,
               groov::field<"HSTXDCL", std::uint8_t, 1, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wpcr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"THSTRAIL", std::uint8_t, 31, 24>,
               groov::field<"THSPREP", std::uint8_t, 23, 16>,
               groov::field<"TCLKZEO", std::uint8_t, 15, 8>,
               groov::field<"TCLKPREP", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wpcr4_tt = groov::reg<name,
                                  std::uint32_t,
                                  baseaddress + offset,
                                  access::rw,
                                  groov::field<"TLPXC", std::uint8_t, 31, 24>,
                                  groov::field<"THSEXIT", std::uint8_t, 23, 16>,
                                  groov::field<"TLPXD", std::uint8_t, 15, 8>,
                                  groov::field<"THSZERO", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wpcr5_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 8, access::ro>,
               groov::field<"THSZERO", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using dsi_wrpcr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED4", std::uint8_t, 31, 25, access::ro>,
               groov::field<"REGEN", bool, 24, 24>,
               groov::field<"RESERVED3", std::uint8_t, 23, 18, access::ro>,
               groov::field<"ODF", std::uint8_t, 17, 16>,
               groov::field<"RESERVED2", bool, 15, 15, access::ro>,
               groov::field<"IDF", std::uint8_t, 14, 11>,
               groov::field<"RESERVED1", std::uint8_t, 10, 9, access::ro>,
               groov::field<"NDIV", std::uint8_t, 8, 2>,
               groov::field<"RESERVED0", bool, 1, 1, access::ro>,
               groov::field<"PLLEN", bool, 0, 0>>;

} // namespace dsi
