/* File autogenerated with
 * svd2groov, version: 0.1.0, branch: dev, hash: ce7ae6e
 */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace pwr {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED1", std::uint16_t, 31, 20, access::ro>,
               groov::field<"UDEN", std::uint8_t, 19, 18>,
               groov::field<"ODSWEN", bool, 17, 17>,
               groov::field<"ODEN", bool, 16, 16>,
               groov::field<"VOS", std::uint8_t, 15, 14>,
               groov::field<"ADCDC1", bool, 13, 13>,
               groov::field<"RESERVED0", bool, 12, 12, access::ro>,
               groov::field<"MRLVDS", bool, 11, 11>,
               groov::field<"LPLVDS", bool, 10, 10>,
               groov::field<"FPDS", bool, 9, 9>,
               groov::field<"DBP", bool, 8, 8>,
               groov::field<"PLS", std::uint8_t, 7, 5>,
               groov::field<"PVDE", bool, 4, 4>,
               groov::field<"CSBF", bool, 3, 3>,
               groov::field<"CWUF", bool, 2, 2>,
               groov::field<"PDDS", bool, 1, 1>,
               groov::field<"LPDS", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using csr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED3", std::uint16_t, 31, 20, access::ro>,
               groov::field<"UDRDY", std::uint8_t, 19, 18>,
               groov::field<"ODSWRDY", bool, 17, 17, access::ro>,
               groov::field<"ODRDY", bool, 16, 16, access::ro>,
               groov::field<"RESERVED2", bool, 15, 15, access::ro>,
               groov::field<"VOSRDY", bool, 14, 14>,
               groov::field<"RESERVED1", std::uint8_t, 13, 10, access::ro>,
               groov::field<"BRE", bool, 9, 9>,
               groov::field<"EWUP", bool, 8, 8>,
               groov::field<"RESERVED0", std::uint8_t, 7, 4, access::ro>,
               groov::field<"BRR", bool, 3, 3, access::ro>,
               groov::field<"PVDO", bool, 2, 2, access::ro>,
               groov::field<"SBF", bool, 1, 1, access::ro>,
               groov::field<"WUF", bool, 0, 0, access::ro>>;

} // namespace pwr
