/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace flash {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using acr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 19, access::ro>,
               groov::field<"dbg_swen", bool, 18, 18>,
               groov::field<"reserved1", std::uint8_t, 17, 15, access::ro>,
               groov::field<"sleep_pd", bool, 14, 14>,
               groov::field<"run_pd", bool, 13, 13>,
               groov::field<"dcrst", bool, 12, 12>,
               groov::field<"icrst", bool, 11, 11>,
               groov::field<"dcen", bool, 10, 10>,
               groov::field<"icen", bool, 9, 9>,
               groov::field<"prften", bool, 8, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 4, access::ro>,
               groov::field<"latency", std::uint8_t, 3, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pdkeyr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::wo,
               groov::field<"pdkeyr", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using keyr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::wo,
               groov::field<"keyr", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using optkeyr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::wo,
               groov::field<"optkeyr", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved2", std::uint16_t, 31, 17, access::ro>,
               groov::field<"bsy", bool, 16, 16, access::ro>,
               groov::field<"optverr", bool, 15, 15>,
               groov::field<"rderr", bool, 14, 14>,
               groov::field<"reserved1", std::uint8_t, 13, 10, access::ro>,
               groov::field<"fasterr", bool, 9, 9>,
               groov::field<"miserr", bool, 8, 8>,
               groov::field<"pgserr", bool, 7, 7>,
               groov::field<"sizerr", bool, 6, 6>,
               groov::field<"pgaerr", bool, 5, 5>,
               groov::field<"wrperr", bool, 4, 4>,
               groov::field<"progerr", bool, 3, 3>,
               groov::field<"reserved0", bool, 2, 2, access::ro>,
               groov::field<"operr", bool, 1, 1>,
               groov::field<"eop", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using cr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"lock", bool, 31, 31>,
               groov::field<"optlock", bool, 30, 30>,
               groov::field<"reserved2", bool, 29, 29, access::ro>,
               groov::field<"sec_prot1", bool, 28, 28>,
               groov::field<"obl_launch", bool, 27, 27>,
               groov::field<"rderrie", bool, 26, 26>,
               groov::field<"errie", bool, 25, 25>,
               groov::field<"eopie", bool, 24, 24>,
               groov::field<"reserved1", std::uint8_t, 23, 19, access::ro>,
               groov::field<"fstpg", bool, 18, 18>,
               groov::field<"optstrt", bool, 17, 17>,
               groov::field<"strt", bool, 16, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 10, access::ro>,
               groov::field<"pnb", std::uint8_t, 9, 3>,
               groov::field<"mer1", bool, 2, 2>,
               groov::field<"per", bool, 1, 1>,
               groov::field<"pg", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using eccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"eccd", bool, 31, 31>,
               groov::field<"eccc", bool, 30, 30>,
               groov::field<"eccd2", bool, 29, 29>,
               groov::field<"eccc2", bool, 28, 28>,
               groov::field<"reserved2", std::uint8_t, 27, 25, access::ro>,
               groov::field<"eccie", bool, 24, 24>,
               groov::field<"reserved1", bool, 23, 23, access::ro>,
               groov::field<"sysf_ecc", bool, 22, 22, access::ro>,
               groov::field<"bk_ecc", bool, 21, 21, access::ro>,
               groov::field<"reserved0", std::uint8_t, 20, 19, access::ro>,
               groov::field<"addr_ecc", std::uint32_t, 18, 0, access::ro>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using optr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved3", bool, 31, 31, access::ro>,
               groov::field<"irhen", bool, 30, 30>,
               groov::field<"nrst_mode", std::uint8_t, 29, 28>,
               groov::field<"nboot0", bool, 27, 27>,
               groov::field<"nswboot0", bool, 26, 26>,
               groov::field<"ccmsram_rst", bool, 25, 25>,
               groov::field<"sram2_pe", bool, 24, 24>,
               groov::field<"nboot1", bool, 23, 23>,
               groov::field<"dbank", bool, 22, 22>,
               groov::field<"reserved2", bool, 21, 21, access::ro>,
               groov::field<"bfb2", bool, 20, 20>,
               groov::field<"wwdg_sw", bool, 19, 19>,
               groov::field<"iwdg_stdby", bool, 18, 18>,
               groov::field<"iwdg_stop", bool, 17, 17>,
               groov::field<"iwdg_sw", bool, 16, 16>,
               groov::field<"reserved1", bool, 15, 15, access::ro>,
               groov::field<"nrst_shdw", bool, 14, 14>,
               groov::field<"nrst_stdby", bool, 13, 13>,
               groov::field<"nrst_stop", bool, 12, 12>,
               groov::field<"reserved0", bool, 11, 11, access::ro>,
               groov::field<"bor_lev", std::uint8_t, 10, 8>,
               groov::field<"rdp", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pcrop1sr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved0", std::uint32_t, 31, 15, access::ro>,
               groov::field<"pcrop1_strt", std::uint16_t, 14, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using pcrop1er_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"pcrop_rdp", bool, 31, 31>,
               groov::field<"reserved0", std::uint16_t, 30, 15, access::ro>,
               groov::field<"pcrop1_end", std::uint16_t, 14, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using wrp1ar_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 23, access::ro>,
               groov::field<"wrp1a_end", std::uint8_t, 22, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 7, access::ro>,
               groov::field<"wrp1a_strt", std::uint8_t, 6, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using wrp1br_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 23, access::ro>,
               groov::field<"wrp1b_end", std::uint8_t, 22, 16>,
               groov::field<"reserved0", std::uint16_t, 15, 7, access::ro>,
               groov::field<"wrp1b_strt", std::uint8_t, 6, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using sec1r_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved1", std::uint16_t, 31, 17, access::ro>,
               groov::field<"boot_lock", bool, 16, 16>,
               groov::field<"reserved0", std::uint8_t, 15, 8, access::ro>,
               groov::field<"sec_size1", std::uint8_t, 7, 0>>;

} // namespace flash
