#pragma once

#include <cstdint>
#include <groov/groov.hpp>

/* Intel groov for STM32C011 MCU, using CM0 cpu */
/* Generated by svd2groov */

namespace mcu {

using tim14_t = groov::group<
  "TIM14",
  groov::mmio_bus<>,
  groov::reg<"TIM14_CR1",
             std::uint32_t,
             0x4000'2000 + 0u,
             groov::w::replace,
             groov::field<"CEN", bool, 0u, 0u, groov::w::replace>,
             groov::field<"UDIS", bool, 1u, 1u, groov::w::replace>,
             groov::field<"URS", bool, 2u, 2u, groov::w::replace>,
             groov::field<"OPM", bool, 3u, 3u, groov::w::replace>,
             groov::field<"ARPE", bool, 7u, 7u, groov::w::replace>,
             groov::field<"CKD", std::uint_fast8_t, 9u, 8u, groov::w::replace>,
             groov::field<"UIFREMAP", bool, 11u, 11u, groov::w::replace>>,
  groov::reg<"TIM14_DIER",
             std::uint32_t,
             0x4000'2000 + 0xcu,
             groov::w::replace,
             groov::field<"UIE", bool, 0u, 0u, groov::w::replace>,
             groov::field<"CC1IE", bool, 1u, 1u, groov::w::replace>>,
  groov::reg<"TIM14_SR",
             std::uint32_t,
             0x4000'2000 + 0x10u,
             groov::w::replace,
             groov::field<"UIF", bool, 0u, 0u, groov::w::replace>,
             groov::field<"CC1IF", bool, 1u, 1u, groov::w::replace>,
             groov::field<"CC1OF", bool, 9u, 9u, groov::w::replace>>,
  groov::reg<"TIM14_EGR",
             std::uint32_t,
             0x4000'2000 + 0x14u,
             groov::w::replace,
             groov::field<"UG", bool, 0u, 0u, groov::w::replace>,
             groov::field<"CC1G", bool, 1u, 1u, groov::w::replace>>,
  groov::reg<
    "TIM14_CCMR1_input",
    std::uint32_t,
    0x4000'2000 + 0x18u,
    groov::w::replace,
    groov::field<"CC1S", std::uint_fast8_t, 1u, 0u, groov::w::replace>,
    groov::field<"IC1PSC", std::uint_fast8_t, 3u, 2u, groov::w::replace>,
    groov::field<"IC1F", std::uint_fast8_t, 7u, 4u, groov::w::replace>>,
  groov::reg<
    "TIM14_CCMR1_output",
    std::uint32_t,
    0x4000'2000 + 0x18u,
    groov::w::replace,
    groov::field<"CC1S", std::uint_fast8_t, 1u, 0u, groov::w::replace>,
    groov::field<"OC1FE", bool, 2u, 2u, groov::w::replace>,
    groov::field<"OC1PE", bool, 3u, 3u, groov::w::replace>,
    groov::field<"OC1M1", std::uint_fast8_t, 6u, 4u, groov::w::replace>,
    groov::field<"OC1M2", bool, 16u, 16u, groov::w::replace>>,
  groov::reg<"TIM14_CCER",
             std::uint32_t,
             0x4000'2000 + 0x20u,
             groov::w::replace,
             groov::field<"CC1E", bool, 0u, 0u, groov::w::replace>,
             groov::field<"CC1P", bool, 1u, 1u, groov::w::replace>,
             groov::field<"CC1NP", bool, 3u, 3u, groov::w::replace>>,
  groov::reg<
    "TIM14_CNT",
    std::uint32_t,
    0x4000'2000 + 0x24u,
    groov::w::replace,
    groov::field<"CNT", std::uint_fast16_t, 15u, 0u, groov::w::replace>,
    groov::field<"UIFCPY", bool, 31u, 31u, groov::w::replace>>,
  groov::reg<
    "TIM14_PSC",
    std::uint32_t,
    0x4000'2000 + 0x28u,
    groov::w::replace,
    groov::field<"PSC", std::uint_fast16_t, 15u, 0u, groov::w::replace>>,
  groov::reg<
    "TIM14_ARR",
    std::uint32_t,
    0x4000'2000 + 0x2cu,
    groov::w::replace,
    groov::field<"ARR", std::uint_fast16_t, 15u, 0u, groov::w::replace>>,
  groov::reg<
    "TIM14_CCR1",
    std::uint32_t,
    0x4000'2000 + 0x34u,
    groov::w::replace,
    groov::field<"CCR1", std::uint_fast16_t, 15u, 0u, groov::w::replace>>,
  groov::reg<
    "TIM14_TISEL",
    std::uint32_t,
    0x4000'2000 + 0x68u,
    groov::w::replace,
    groov::field<"TI1SEL", std::uint_fast8_t, 3u, 0u, groov::w::replace>>>;
constexpr auto tim14 = tim14_t{};

} // namespace mcu
