/* File autogenerated with svd2groov_multi */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>

namespace stm32::registers {

// AC peripheral register templates
// Total unique registers: 5

// ac_abfsr_v1: ABFSR (version 1)
// Used by: AC.ABFSR@stm32f722, AC.ABFSR@stm32f723, AC.ABFSR@stm32f730, AC.ABFSR@stm32f732, AC.ABFSR@stm32f733, ... +29 more
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ac_abfsr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             access::rw,
             groov::field<"reserved1", std::uint32_t, 31, 10, access::ro>,
             groov::field<"aximtype", std::uint8_t, 9, 8>,
             groov::field<"reserved0", std::uint8_t, 7, 5, access::ro>,
             groov::field<"eppb", bool, 4, 4>,
             groov::field<"axim", bool, 3, 3>,
             groov::field<"ahbp", bool, 2, 2>,
             groov::field<"dtcm", bool, 1, 1>,
             groov::field<"itcm", bool, 0, 0>>;

// ac_ahbpcr_v1: AHBPCR (version 1)
// Used by: AC.AHBPCR@stm32f722, AC.AHBPCR@stm32f723, AC.AHBPCR@stm32f730, AC.AHBPCR@stm32f732, AC.AHBPCR@stm32f733, ... +29 more
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ac_ahbpcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             access::rw,
             groov::field<"reserved0", std::uint32_t, 31, 4, access::ro>,
             groov::field<"sz", std::uint8_t, 3, 1>,
             groov::field<"en", bool, 0, 0>>;

// ac_ahbscr_v1: AHBSCR (version 1)
// Used by: AC.AHBSCR@stm32f722, AC.AHBSCR@stm32f723, AC.AHBSCR@stm32f730, AC.AHBSCR@stm32f732, AC.AHBSCR@stm32f733, ... +29 more
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ac_ahbscr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             access::rw,
             groov::field<"reserved0", std::uint16_t, 31, 16, access::ro>,
             groov::field<"initcount", std::uint8_t, 15, 11>,
             groov::field<"tpri", std::uint16_t, 10, 2>,
             groov::field<"ctl", std::uint8_t, 1, 0>>;

// ac_cacr_v1: CACR (version 1)
// Used by: AC.CACR@stm32f722, AC.CACR@stm32f723, AC.CACR@stm32f730, AC.CACR@stm32f732, AC.CACR@stm32f733, ... +29 more
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ac_cacr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             access::rw,
             groov::field<"reserved0", std::uint32_t, 31, 3, access::ro>,
             groov::field<"forcewt", bool, 2, 2>,
             groov::field<"eccen", bool, 1, 1>,
             groov::field<"siwt", bool, 0, 0>>;

// ac_dtcmcr_v1: DTCMCR (version 1)
// Used by: AC.DTCMCR@stm32f722, AC.DTCMCR@stm32f723, AC.DTCMCR@stm32f730, AC.DTCMCR@stm32f732, AC.DTCMCR@stm32f733, ... +29 more
template <stdx::ct_string name,
          std::uint32_t   baseaddress,
          std::uint32_t   offset>
using ac_dtcmcr_v1_tt =
  groov::reg<name,
             std::uint32_t,
             baseaddress + offset,
             access::rw,
             groov::field<"reserved0", std::uint32_t, 31, 7, access::ro>,
             groov::field<"sz", std::uint8_t, 6, 3>,
             groov::field<"reten", bool, 2, 2>,
             groov::field<"rmw", bool, 1, 1>,
             groov::field<"en", bool, 0, 0>>;

} // namespace stm32::registers
