/* File autogenerated with svd2groov for stm32f100 */
#pragma once

#include <cstdint>
#include <groov/groov.hpp>
#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
#include <stm32/stm32f100/registers/adc.hpp>
#include <stm32/stm32f100/registers/afio.hpp>
#include <stm32/stm32f100/registers/bkp.hpp>
#include <stm32/stm32f100/registers/cec.hpp>
#include <stm32/stm32f100/registers/crc.hpp>
#include <stm32/stm32f100/registers/dac.hpp>
#include <stm32/stm32f100/registers/dbg.hpp>
#include <stm32/stm32f100/registers/dma.hpp>
#include <stm32/stm32f100/registers/exti.hpp>
#include <stm32/stm32f100/registers/flash.hpp>
#include <stm32/stm32f100/registers/fsmc.hpp>
#include <stm32/stm32f100/registers/gpio.hpp>
#include <stm32/stm32f100/registers/i2c.hpp>
#include <stm32/stm32f100/registers/iwdg.hpp>
#include <stm32/stm32f100/registers/pwr.hpp>
#include <stm32/stm32f100/registers/rcc.hpp>
#include <stm32/stm32f100/registers/rtc.hpp>
#include <stm32/stm32f100/registers/spi.hpp>
#include <stm32/stm32f100/registers/tim.hpp>
#include <stm32/stm32f100/registers/usart.hpp>
#include <stm32/stm32f100/registers/wwdg.hpp>

namespace stm32 {

namespace fsmc {
  constexpr std::uint32_t FSMC_BASE = 0xa000'0000;

  using bcr1_tt = regs::fsmc_bcr1_v1_tt;
  using btr1_tt = regs::fsmc_btr1_v1_tt;
  using bcr2_tt = regs::fsmc_bcr2_v1_tt;
  using btr2_tt = regs::fsmc_btr2_v1_tt;
  using bcr3_tt = regs::fsmc_bcr3_v1_tt;
  using btr3_tt = regs::fsmc_btr3_v1_tt;
  using bcr4_tt = regs::fsmc_bcr4_v1_tt;
  using btr4_tt = regs::fsmc_btr4_v1_tt;
  using bwtr1_tt = regs::fsmc_bwtr1_v1_tt;
  using bwtr2_tt = regs::fsmc_bwtr2_v1_tt;
  using bwtr3_tt = regs::fsmc_bwtr3_v1_tt;
  using bwtr4_tt = regs::fsmc_bwtr4_v1_tt;

  template <std::uint32_t baseaddress>
  using fsmc_t =
    groov::group<"fsmc",
                 groov::mmio_bus<>,
                 bcr1_tt<"bcr1", baseaddress, 0x0>,
                 btr1_tt<"btr1", baseaddress, 0x4>,
                 bcr2_tt<"bcr2", baseaddress, 0x8>,
                 btr2_tt<"btr2", baseaddress, 0xc>,
                 bcr3_tt<"bcr3", baseaddress, 0x10>,
                 btr3_tt<"btr3", baseaddress, 0x14>,
                 bcr4_tt<"bcr4", baseaddress, 0x18>,
                 btr4_tt<"btr4", baseaddress, 0x1c>,
                 bwtr1_tt<"bwtr1", baseaddress, 0x104>,
                 bwtr2_tt<"bwtr2", baseaddress, 0x10c>,
                 bwtr3_tt<"bwtr3", baseaddress, 0x114>,
                 bwtr4_tt<"bwtr4", baseaddress, 0x11c>>;

} // namespace fsmc

constexpr auto fsmc = fsmc::fsmc_t<fsmc::FSMC_BASE>{};

namespace pwr {
  constexpr std::uint32_t PWR_BASE = 0x4000'7000;

  using cr_tt = regs::pwr_cr_v1_tt;
  using csr_tt = regs::pwr_csr_v1_tt;

  template <std::uint32_t baseaddress>
  using pwr_t =
    groov::group<"pwr",
                 groov::mmio_bus<>,
                 cr_tt<"cr", baseaddress, 0x0>,
                 csr_tt<"csr", baseaddress, 0x4>>;

} // namespace pwr

constexpr auto pwr = pwr::pwr_t<pwr::PWR_BASE>{};

namespace rcc {
  constexpr std::uint32_t RCC_BASE = 0x4002'1000;

  using cr_tt = regs::rcc_cr_v1_tt;
  using cfgr_tt = regs::rcc_cfgr_v1_tt;
  using cir_tt = regs::rcc_cir_v1_tt;
  using apb2rstr_tt = regs::rcc_apb2rstr_v1_tt;
  using apb1rstr_tt = regs::rcc_apb1rstr_v1_tt;
  using ahbenr_tt = regs::rcc_ahbenr_v1_tt;
  using apb2enr_tt = regs::rcc_apb2enr_v1_tt;
  using apb1enr_tt = regs::rcc_apb1enr_v1_tt;
  using bdcr_tt = regs::rcc_bdcr_v1_tt;
  using csr_tt = regs::rcc_csr_v1_tt;
  using cfgr2_tt = regs::rcc_cfgr2_v1_tt;

  template <std::uint32_t baseaddress>
  using rcc_t =
    groov::group<"rcc",
                 groov::mmio_bus<>,
                 cr_tt<"cr", baseaddress, 0x0>,
                 cfgr_tt<"cfgr", baseaddress, 0x4>,
                 cir_tt<"cir", baseaddress, 0x8>,
                 apb2rstr_tt<"apb2rstr", baseaddress, 0xc>,
                 apb1rstr_tt<"apb1rstr", baseaddress, 0x10>,
                 ahbenr_tt<"ahbenr", baseaddress, 0x14>,
                 apb2enr_tt<"apb2enr", baseaddress, 0x18>,
                 apb1enr_tt<"apb1enr", baseaddress, 0x1c>,
                 bdcr_tt<"bdcr", baseaddress, 0x20>,
                 csr_tt<"csr", baseaddress, 0x24>,
                 cfgr2_tt<"cfgr2", baseaddress, 0x2c>>;

} // namespace rcc

constexpr auto rcc = rcc::rcc_t<rcc::RCC_BASE>{};

namespace gpioa {
  constexpr std::uint32_t GPIOA_BASE = 0x4001'0800;

  using crl_tt = regs::gpio_crl_v1_tt;
  using crh_tt = regs::gpio_crh_v1_tt;
  using idr_tt = regs::gpio_idr_v1_tt;
  using odr_tt = regs::gpio_odr_v1_tt;
  using bsrr_tt = regs::gpio_bsrr_v1_tt;
  using brr_tt = regs::gpio_brr_v1_tt;
  using lckr_tt = regs::gpio_lckr_v1_tt;

  template <std::uint32_t baseaddress>
  using gpioa_t =
    groov::group<"gpioa",
                 groov::mmio_bus<>,
                 crl_tt<"crl", baseaddress, 0x0>,
                 crh_tt<"crh", baseaddress, 0x4>,
                 idr_tt<"idr", baseaddress, 0x8>,
                 odr_tt<"odr", baseaddress, 0xc>,
                 bsrr_tt<"bsrr", baseaddress, 0x10>,
                 brr_tt<"brr", baseaddress, 0x14>,
                 lckr_tt<"lckr", baseaddress, 0x18>>;

} // namespace gpioa

constexpr auto gpioa = gpioa::gpioa_t<gpioa::GPIOA_BASE>{};

namespace afio {
  constexpr std::uint32_t AFIO_BASE = 0x4001'0000;

  using evcr_tt = regs::afio_evcr_v1_tt;
  using mapr_tt = regs::afio_mapr_v1_tt;
  using exticr1_tt = regs::afio_exticr1_v1_tt;
  using exticr2_tt = regs::afio_exticr2_v1_tt;
  using exticr3_tt = regs::afio_exticr3_v1_tt;
  using exticr4_tt = regs::afio_exticr4_v1_tt;
  using mapr2_tt = regs::afio_mapr2_v1_tt;

  template <std::uint32_t baseaddress>
  using afio_t =
    groov::group<"afio",
                 groov::mmio_bus<>,
                 evcr_tt<"evcr", baseaddress, 0x0>,
                 mapr_tt<"mapr", baseaddress, 0x4>,
                 exticr1_tt<"exticr1", baseaddress, 0x8>,
                 exticr2_tt<"exticr2", baseaddress, 0xc>,
                 exticr3_tt<"exticr3", baseaddress, 0x10>,
                 exticr4_tt<"exticr4", baseaddress, 0x14>,
                 mapr2_tt<"mapr2", baseaddress, 0x1c>>;

} // namespace afio

constexpr auto afio = afio::afio_t<afio::AFIO_BASE>{};

namespace exti {
  constexpr std::uint32_t EXTI_BASE = 0x4001'0400;

  using imr_tt = regs::exti_imr_v1_tt;
  using emr_tt = regs::exti_emr_v1_tt;
  using rtsr_tt = regs::exti_rtsr_v1_tt;
  using ftsr_tt = regs::exti_ftsr_v1_tt;
  using swier_tt = regs::exti_swier_v1_tt;
  using pr_tt = regs::exti_pr_v1_tt;

  template <std::uint32_t baseaddress>
  using exti_t =
    groov::group<"exti",
                 groov::mmio_bus<>,
                 imr_tt<"imr", baseaddress, 0x0>,
                 emr_tt<"emr", baseaddress, 0x4>,
                 rtsr_tt<"rtsr", baseaddress, 0x8>,
                 ftsr_tt<"ftsr", baseaddress, 0xc>,
                 swier_tt<"swier", baseaddress, 0x10>,
                 pr_tt<"pr", baseaddress, 0x14>>;

} // namespace exti

constexpr auto exti = exti::exti_t<exti::EXTI_BASE>{};

namespace dma1 {
  constexpr std::uint32_t DMA1_BASE = 0x4002'0000;

  using isr_tt = regs::dma_isr_v1_tt;
  using ifcr_tt = regs::dma_ifcr_v1_tt;
  using ccr1_tt = regs::dma_ccr1_v1_tt;
  using cndtr1_tt = regs::dma_cndtr1_v1_tt;
  using cpar1_tt = regs::dma_cpar1_v1_tt;
  using cmar1_tt = regs::dma_cmar1_v1_tt;
  using ccr2_tt = regs::dma_ccr2_v1_tt;
  using cndtr2_tt = regs::dma_cndtr2_v1_tt;
  using cpar2_tt = regs::dma_cpar2_v1_tt;
  using cmar2_tt = regs::dma_cmar2_v1_tt;
  using ccr3_tt = regs::dma_ccr3_v1_tt;
  using cndtr3_tt = regs::dma_cndtr3_v1_tt;
  using cpar3_tt = regs::dma_cpar3_v1_tt;
  using cmar3_tt = regs::dma_cmar3_v1_tt;
  using ccr4_tt = regs::dma_ccr4_v1_tt;
  using cndtr4_tt = regs::dma_cndtr4_v1_tt;
  using cpar4_tt = regs::dma_cpar4_v1_tt;
  using cmar4_tt = regs::dma_cmar4_v1_tt;
  using ccr5_tt = regs::dma_ccr5_v1_tt;
  using cndtr5_tt = regs::dma_cndtr5_v1_tt;
  using cpar5_tt = regs::dma_cpar5_v1_tt;
  using cmar5_tt = regs::dma_cmar5_v1_tt;
  using ccr6_tt = regs::dma_ccr6_v1_tt;
  using cndtr6_tt = regs::dma_cndtr6_v1_tt;
  using cpar6_tt = regs::dma_cpar6_v1_tt;
  using cmar6_tt = regs::dma_cmar6_v1_tt;
  using ccr7_tt = regs::dma_ccr7_v1_tt;
  using cndtr7_tt = regs::dma_cndtr7_v1_tt;
  using cpar7_tt = regs::dma_cpar7_v1_tt;
  using cmar7_tt = regs::dma_cmar7_v1_tt;

  template <std::uint32_t baseaddress>
  using dma1_t =
    groov::group<"dma1",
                 groov::mmio_bus<>,
                 isr_tt<"isr", baseaddress, 0x0>,
                 ifcr_tt<"ifcr", baseaddress, 0x4>,
                 ccr1_tt<"ccr1", baseaddress, 0x8>,
                 cndtr1_tt<"cndtr1", baseaddress, 0xc>,
                 cpar1_tt<"cpar1", baseaddress, 0x10>,
                 cmar1_tt<"cmar1", baseaddress, 0x14>,
                 ccr2_tt<"ccr2", baseaddress, 0x1c>,
                 cndtr2_tt<"cndtr2", baseaddress, 0x20>,
                 cpar2_tt<"cpar2", baseaddress, 0x24>,
                 cmar2_tt<"cmar2", baseaddress, 0x28>,
                 ccr3_tt<"ccr3", baseaddress, 0x30>,
                 cndtr3_tt<"cndtr3", baseaddress, 0x34>,
                 cpar3_tt<"cpar3", baseaddress, 0x38>,
                 cmar3_tt<"cmar3", baseaddress, 0x3c>,
                 ccr4_tt<"ccr4", baseaddress, 0x44>,
                 cndtr4_tt<"cndtr4", baseaddress, 0x48>,
                 cpar4_tt<"cpar4", baseaddress, 0x4c>,
                 cmar4_tt<"cmar4", baseaddress, 0x50>,
                 ccr5_tt<"ccr5", baseaddress, 0x58>,
                 cndtr5_tt<"cndtr5", baseaddress, 0x5c>,
                 cpar5_tt<"cpar5", baseaddress, 0x60>,
                 cmar5_tt<"cmar5", baseaddress, 0x64>,
                 ccr6_tt<"ccr6", baseaddress, 0x6c>,
                 cndtr6_tt<"cndtr6", baseaddress, 0x70>,
                 cpar6_tt<"cpar6", baseaddress, 0x74>,
                 cmar6_tt<"cmar6", baseaddress, 0x78>,
                 ccr7_tt<"ccr7", baseaddress, 0x80>,
                 cndtr7_tt<"cndtr7", baseaddress, 0x84>,
                 cpar7_tt<"cpar7", baseaddress, 0x88>,
                 cmar7_tt<"cmar7", baseaddress, 0x8c>>;

} // namespace dma1

constexpr auto dma1 = dma1::dma1_t<dma1::DMA1_BASE>{};

namespace rtc {
  constexpr std::uint32_t RTC_BASE = 0x4000'2800;

  using crh_tt = regs::rtc_crh_v1_tt;
  using crl_tt = regs::rtc_crl_v1_tt;
  using prlh_tt = regs::rtc_prlh_v1_tt;
  using prll_tt = regs::rtc_prll_v1_tt;
  using divh_tt = regs::rtc_divh_v1_tt;
  using divl_tt = regs::rtc_divl_v1_tt;
  using cnth_tt = regs::rtc_cnth_v1_tt;
  using cntl_tt = regs::rtc_cntl_v1_tt;
  using alrh_tt = regs::rtc_alrh_v1_tt;
  using alrl_tt = regs::rtc_alrl_v1_tt;

  template <std::uint32_t baseaddress>
  using rtc_t =
    groov::group<"rtc",
                 groov::mmio_bus<>,
                 crh_tt<"crh", baseaddress, 0x0>,
                 crl_tt<"crl", baseaddress, 0x4>,
                 prlh_tt<"prlh", baseaddress, 0x8>,
                 prll_tt<"prll", baseaddress, 0xc>,
                 divh_tt<"divh", baseaddress, 0x10>,
                 divl_tt<"divl", baseaddress, 0x14>,
                 cnth_tt<"cnth", baseaddress, 0x18>,
                 cntl_tt<"cntl", baseaddress, 0x1c>,
                 alrh_tt<"alrh", baseaddress, 0x20>,
                 alrl_tt<"alrl", baseaddress, 0x24>>;

} // namespace rtc

constexpr auto rtc = rtc::rtc_t<rtc::RTC_BASE>{};

namespace bkp {
  constexpr std::uint32_t BKP_BASE = 0x4000'6c00;

  using dr1_tt = regs::bkp_dr1_v1_tt;
  using dr2_tt = regs::bkp_dr2_v1_tt;
  using dr3_tt = regs::bkp_dr3_v1_tt;
  using dr4_tt = regs::bkp_dr4_v1_tt;
  using dr5_tt = regs::bkp_dr5_v1_tt;
  using dr6_tt = regs::bkp_dr6_v1_tt;
  using dr7_tt = regs::bkp_dr7_v1_tt;
  using dr8_tt = regs::bkp_dr8_v1_tt;
  using dr9_tt = regs::bkp_dr9_v1_tt;
  using dr10_tt = regs::bkp_dr10_v1_tt;
  using rtccr_tt = regs::bkp_rtccr_v1_tt;
  using cr_tt = regs::bkp_cr_v1_tt;
  using csr_tt = regs::bkp_csr_v1_tt;

  template <std::uint32_t baseaddress>
  using bkp_t =
    groov::group<"bkp",
                 groov::mmio_bus<>,
                 dr1_tt<"dr1", baseaddress, 0x4>,
                 dr2_tt<"dr2", baseaddress, 0x8>,
                 dr3_tt<"dr3", baseaddress, 0xc>,
                 dr4_tt<"dr4", baseaddress, 0x10>,
                 dr5_tt<"dr5", baseaddress, 0x14>,
                 dr6_tt<"dr6", baseaddress, 0x18>,
                 dr7_tt<"dr7", baseaddress, 0x1c>,
                 dr8_tt<"dr8", baseaddress, 0x20>,
                 dr9_tt<"dr9", baseaddress, 0x24>,
                 dr10_tt<"dr10", baseaddress, 0x28>,
                 rtccr_tt<"rtccr", baseaddress, 0x2c>,
                 cr_tt<"cr", baseaddress, 0x30>,
                 csr_tt<"csr", baseaddress, 0x34>>;

} // namespace bkp

constexpr auto bkp = bkp::bkp_t<bkp::BKP_BASE>{};

namespace iwdg {
  constexpr std::uint32_t IWDG_BASE = 0x4000'3000;

  using kr_tt = regs::iwdg_kr_v1_tt;
  using pr_tt = regs::iwdg_pr_v1_tt;
  using rlr_tt = regs::iwdg_rlr_v1_tt;
  using sr_tt = regs::iwdg_sr_v1_tt;

  template <std::uint32_t baseaddress>
  using iwdg_t =
    groov::group<"iwdg",
                 groov::mmio_bus<>,
                 kr_tt<"kr", baseaddress, 0x0>,
                 pr_tt<"pr", baseaddress, 0x4>,
                 rlr_tt<"rlr", baseaddress, 0x8>,
                 sr_tt<"sr", baseaddress, 0xc>>;

} // namespace iwdg

constexpr auto iwdg = iwdg::iwdg_t<iwdg::IWDG_BASE>{};

namespace wwdg {
  constexpr std::uint32_t WWDG_BASE = 0x4000'2c00;

  using cr_tt = regs::wwdg_cr_v1_tt;
  using cfr_tt = regs::wwdg_cfr_v1_tt;
  using sr_tt = regs::wwdg_sr_v1_tt;

  template <std::uint32_t baseaddress>
  using wwdg_t =
    groov::group<"wwdg",
                 groov::mmio_bus<>,
                 cr_tt<"cr", baseaddress, 0x0>,
                 cfr_tt<"cfr", baseaddress, 0x4>,
                 sr_tt<"sr", baseaddress, 0x8>>;

} // namespace wwdg

constexpr auto wwdg = wwdg::wwdg_t<wwdg::WWDG_BASE>{};

namespace tim1 {
  constexpr std::uint32_t TIM1_BASE = 0x4001'2c00;

  using cr1_tt = regs::tim_cr1_v1_tt;
  using cr2_tt = regs::tim_cr2_v1_tt;
  using smcr_tt = regs::tim_smcr_v1_tt;
  using dier_tt = regs::tim_dier_v1_tt;
  using sr_tt = regs::tim_sr_v1_tt;
  using egr_tt = regs::tim_egr_v1_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v1_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v1_tt;
  using ccmr2_output_tt = regs::tim_ccmr2_output_v1_tt;
  using ccmr2_input_tt = regs::tim_ccmr2_input_v1_tt;
  using ccer_tt = regs::tim_ccer_v1_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using ccr2_tt = regs::tim_ccr2_v1_tt;
  using ccr3_tt = regs::tim_ccr3_v1_tt;
  using ccr4_tt = regs::tim_ccr4_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;
  using rcr_tt = regs::tim_rcr_v1_tt;
  using bdtr_tt = regs::tim_bdtr_v1_tt;

  template <std::uint32_t baseaddress>
  using tim1_t =
    groov::group<"tim1",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 smcr_tt<"smcr", baseaddress, 0x8>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccmr2_output_tt<"ccmr2_output", baseaddress, 0x1c>,
                 ccmr2_input_tt<"ccmr2_input", baseaddress, 0x1c>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 ccr2_tt<"ccr2", baseaddress, 0x38>,
                 ccr3_tt<"ccr3", baseaddress, 0x3c>,
                 ccr4_tt<"ccr4", baseaddress, 0x40>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>,
                 rcr_tt<"rcr", baseaddress, 0x30>,
                 bdtr_tt<"bdtr", baseaddress, 0x44>>;

} // namespace tim1

constexpr auto tim1 = tim1::tim1_t<tim1::TIM1_BASE>{};

namespace tim2 {
  constexpr std::uint32_t TIM2_BASE = 0x4000'0000;

  using cr1_tt = regs::tim_cr1_v1_tt;
  using cr2_tt = regs::tim_cr2_v2_tt;
  using smcr_tt = regs::tim_smcr_v2_tt;
  using dier_tt = regs::tim_dier_v2_tt;
  using sr_tt = regs::tim_sr_v2_tt;
  using egr_tt = regs::tim_egr_v2_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v1_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v2_tt;
  using ccmr2_output_tt = regs::tim_ccmr2_output_v1_tt;
  using ccmr2_input_tt = regs::tim_ccmr2_input_v2_tt;
  using ccer_tt = regs::tim_ccer_v2_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using ccr2_tt = regs::tim_ccr2_v1_tt;
  using ccr3_tt = regs::tim_ccr3_v1_tt;
  using ccr4_tt = regs::tim_ccr4_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;

  template <std::uint32_t baseaddress>
  using tim2_t =
    groov::group<"tim2",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 smcr_tt<"smcr", baseaddress, 0x8>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccmr2_output_tt<"ccmr2_output", baseaddress, 0x1c>,
                 ccmr2_input_tt<"ccmr2_input", baseaddress, 0x1c>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 ccr2_tt<"ccr2", baseaddress, 0x38>,
                 ccr3_tt<"ccr3", baseaddress, 0x3c>,
                 ccr4_tt<"ccr4", baseaddress, 0x40>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>>;

} // namespace tim2

constexpr auto tim2 = tim2::tim2_t<tim2::TIM2_BASE>{};

namespace tim12 {
  constexpr std::uint32_t TIM12_BASE = 0x4000'1800;

  using cr1_tt = regs::tim_cr1_v2_tt;
  using cr2_tt = regs::tim_cr2_v3_tt;
  using smcr_tt = regs::tim_smcr_v3_tt;
  using dier_tt = regs::tim_dier_v3_tt;
  using sr_tt = regs::tim_sr_v3_tt;
  using egr_tt = regs::tim_egr_v3_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v2_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v3_tt;
  using ccer_tt = regs::tim_ccer_v3_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using ccr2_tt = regs::tim_ccr2_v1_tt;

  template <std::uint32_t baseaddress>
  using tim12_t =
    groov::group<"tim12",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 smcr_tt<"smcr", baseaddress, 0x8>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 ccr2_tt<"ccr2", baseaddress, 0x38>>;

} // namespace tim12

constexpr auto tim12 = tim12::tim12_t<tim12::TIM12_BASE>{};

namespace tim13 {
  constexpr std::uint32_t TIM13_BASE = 0x4000'1c00;

  using cr1_tt = regs::tim_cr1_v3_tt;
  using dier_tt = regs::tim_dier_v4_tt;
  using sr_tt = regs::tim_sr_v4_tt;
  using egr_tt = regs::tim_egr_v4_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v3_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v4_tt;
  using ccer_tt = regs::tim_ccer_v4_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;

  template <std::uint32_t baseaddress>
  using tim13_t =
    groov::group<"tim13",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>>;

} // namespace tim13

constexpr auto tim13 = tim13::tim13_t<tim13::TIM13_BASE>{};

namespace tim6 {
  constexpr std::uint32_t TIM6_BASE = 0x4000'1000;

  using cr1_tt = regs::tim_cr1_v4_tt;
  using cr2_tt = regs::tim_cr2_v3_tt;
  using dier_tt = regs::tim_dier_v5_tt;
  using sr_tt = regs::tim_sr_v5_tt;
  using egr_tt = regs::tim_egr_v5_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;

  template <std::uint32_t baseaddress>
  using tim6_t =
    groov::group<"tim6",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>>;

} // namespace tim6

constexpr auto tim6 = tim6::tim6_t<tim6::TIM6_BASE>{};

namespace i2c1 {
  constexpr std::uint32_t I2C1_BASE = 0x4000'5400;

  using cr1_tt = regs::i2c_cr1_v1_tt;
  using cr2_tt = regs::i2c_cr2_v1_tt;
  using oar1_tt = regs::i2c_oar1_v1_tt;
  using oar2_tt = regs::i2c_oar2_v1_tt;
  using dr_tt = regs::i2c_dr_v1_tt;
  using sr1_tt = regs::i2c_sr1_v1_tt;
  using sr2_tt = regs::i2c_sr2_v1_tt;
  using ccr_tt = regs::i2c_ccr_v1_tt;
  using trise_tt = regs::i2c_trise_v1_tt;

  template <std::uint32_t baseaddress>
  using i2c1_t =
    groov::group<"i2c1",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 oar1_tt<"oar1", baseaddress, 0x8>,
                 oar2_tt<"oar2", baseaddress, 0xc>,
                 dr_tt<"dr", baseaddress, 0x10>,
                 sr1_tt<"sr1", baseaddress, 0x14>,
                 sr2_tt<"sr2", baseaddress, 0x18>,
                 ccr_tt<"ccr", baseaddress, 0x1c>,
                 trise_tt<"trise", baseaddress, 0x20>>;

} // namespace i2c1

constexpr auto i2c1 = i2c1::i2c1_t<i2c1::I2C1_BASE>{};

namespace spi1 {
  constexpr std::uint32_t SPI1_BASE = 0x4001'3000;

  using cr1_tt = regs::spi_cr1_v1_tt;
  using cr2_tt = regs::spi_cr2_v1_tt;
  using sr_tt = regs::spi_sr_v1_tt;
  using dr_tt = regs::spi_dr_v1_tt;
  using crcpr_tt = regs::spi_crcpr_v1_tt;
  using rxcrcr_tt = regs::spi_rxcrcr_v1_tt;
  using txcrcr_tt = regs::spi_txcrcr_v1_tt;

  template <std::uint32_t baseaddress>
  using spi1_t =
    groov::group<"spi1",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 sr_tt<"sr", baseaddress, 0x8>,
                 dr_tt<"dr", baseaddress, 0xc>,
                 crcpr_tt<"crcpr", baseaddress, 0x10>,
                 rxcrcr_tt<"rxcrcr", baseaddress, 0x14>,
                 txcrcr_tt<"txcrcr", baseaddress, 0x18>>;

} // namespace spi1

constexpr auto spi1 = spi1::spi1_t<spi1::SPI1_BASE>{};

namespace usart1 {
  constexpr std::uint32_t USART1_BASE = 0x4001'3800;

  using sr_tt = regs::usart_sr_v1_tt;
  using dr_tt = regs::usart_dr_v1_tt;
  using brr_tt = regs::usart_brr_v1_tt;
  using cr1_tt = regs::usart_cr1_v1_tt;
  using cr2_tt = regs::usart_cr2_v1_tt;
  using cr3_tt = regs::usart_cr3_v1_tt;
  using gtpr_tt = regs::usart_gtpr_v1_tt;

  template <std::uint32_t baseaddress>
  using usart1_t =
    groov::group<"usart1",
                 groov::mmio_bus<>,
                 sr_tt<"sr", baseaddress, 0x0>,
                 dr_tt<"dr", baseaddress, 0x4>,
                 brr_tt<"brr", baseaddress, 0x8>,
                 cr1_tt<"cr1", baseaddress, 0xc>,
                 cr2_tt<"cr2", baseaddress, 0x10>,
                 cr3_tt<"cr3", baseaddress, 0x14>,
                 gtpr_tt<"gtpr", baseaddress, 0x18>>;

} // namespace usart1

constexpr auto usart1 = usart1::usart1_t<usart1::USART1_BASE>{};

namespace adc1 {
  constexpr std::uint32_t ADC1_BASE = 0x4001'2400;

  using sr_tt = regs::adc_sr_v1_tt;
  using cr1_tt = regs::adc_cr1_v1_tt;
  using cr2_tt = regs::adc_cr2_v1_tt;
  using smpr1_tt = regs::adc_smpr1_v1_tt;
  using smpr2_tt = regs::adc_smpr2_v1_tt;
  using jofr1_tt = regs::adc_jofr1_v1_tt;
  using jofr2_tt = regs::adc_jofr2_v1_tt;
  using jofr3_tt = regs::adc_jofr3_v1_tt;
  using jofr4_tt = regs::adc_jofr4_v1_tt;
  using htr_tt = regs::adc_htr_v1_tt;
  using ltr_tt = regs::adc_ltr_v1_tt;
  using sqr1_tt = regs::adc_sqr1_v1_tt;
  using sqr2_tt = regs::adc_sqr2_v1_tt;
  using sqr3_tt = regs::adc_sqr3_v1_tt;
  using jsqr_tt = regs::adc_jsqr_v1_tt;
  using jdr1_tt = regs::adc_jdr1_v1_tt;
  using jdr2_tt = regs::adc_jdr2_v1_tt;
  using jdr3_tt = regs::adc_jdr3_v1_tt;
  using jdr4_tt = regs::adc_jdr4_v1_tt;
  using dr_tt = regs::adc_dr_v1_tt;

  template <std::uint32_t baseaddress>
  using adc1_t =
    groov::group<"adc1",
                 groov::mmio_bus<>,
                 sr_tt<"sr", baseaddress, 0x0>,
                 cr1_tt<"cr1", baseaddress, 0x4>,
                 cr2_tt<"cr2", baseaddress, 0x8>,
                 smpr1_tt<"smpr1", baseaddress, 0xc>,
                 smpr2_tt<"smpr2", baseaddress, 0x10>,
                 jofr1_tt<"jofr1", baseaddress, 0x14>,
                 jofr2_tt<"jofr2", baseaddress, 0x18>,
                 jofr3_tt<"jofr3", baseaddress, 0x1c>,
                 jofr4_tt<"jofr4", baseaddress, 0x20>,
                 htr_tt<"htr", baseaddress, 0x24>,
                 ltr_tt<"ltr", baseaddress, 0x28>,
                 sqr1_tt<"sqr1", baseaddress, 0x2c>,
                 sqr2_tt<"sqr2", baseaddress, 0x30>,
                 sqr3_tt<"sqr3", baseaddress, 0x34>,
                 jsqr_tt<"jsqr", baseaddress, 0x38>,
                 jdr1_tt<"jdr1", baseaddress, 0x3c>,
                 jdr2_tt<"jdr2", baseaddress, 0x40>,
                 jdr3_tt<"jdr3", baseaddress, 0x44>,
                 jdr4_tt<"jdr4", baseaddress, 0x48>,
                 dr_tt<"dr", baseaddress, 0x4c>>;

} // namespace adc1

constexpr auto adc1 = adc1::adc1_t<adc1::ADC1_BASE>{};

namespace dac {
  constexpr std::uint32_t DAC_BASE = 0x4000'7400;

  using cr_tt = regs::dac_cr_v1_tt;
  using swtrigr_tt = regs::dac_swtrigr_v1_tt;
  using dhr12r1_tt = regs::dac_dhr12r1_v1_tt;
  using dhr12l1_tt = regs::dac_dhr12l1_v1_tt;
  using dhr8r1_tt = regs::dac_dhr8r1_v1_tt;
  using dhr12r2_tt = regs::dac_dhr12r2_v1_tt;
  using dhr12l2_tt = regs::dac_dhr12l2_v1_tt;
  using dhr8r2_tt = regs::dac_dhr8r2_v1_tt;
  using dhr12rd_tt = regs::dac_dhr12rd_v1_tt;
  using dhr12ld_tt = regs::dac_dhr12ld_v1_tt;
  using dhr8rd_tt = regs::dac_dhr8rd_v1_tt;
  using dor1_tt = regs::dac_dor1_v1_tt;
  using dor2_tt = regs::dac_dor2_v1_tt;
  using sr_tt = regs::dac_sr_v1_tt;

  template <std::uint32_t baseaddress>
  using dac_t =
    groov::group<"dac",
                 groov::mmio_bus<>,
                 cr_tt<"cr", baseaddress, 0x0>,
                 swtrigr_tt<"swtrigr", baseaddress, 0x4>,
                 dhr12r1_tt<"dhr12r1", baseaddress, 0x8>,
                 dhr12l1_tt<"dhr12l1", baseaddress, 0xc>,
                 dhr8r1_tt<"dhr8r1", baseaddress, 0x10>,
                 dhr12r2_tt<"dhr12r2", baseaddress, 0x14>,
                 dhr12l2_tt<"dhr12l2", baseaddress, 0x18>,
                 dhr8r2_tt<"dhr8r2", baseaddress, 0x1c>,
                 dhr12rd_tt<"dhr12rd", baseaddress, 0x20>,
                 dhr12ld_tt<"dhr12ld", baseaddress, 0x24>,
                 dhr8rd_tt<"dhr8rd", baseaddress, 0x28>,
                 dor1_tt<"dor1", baseaddress, 0x2c>,
                 dor2_tt<"dor2", baseaddress, 0x30>,
                 sr_tt<"sr", baseaddress, 0x34>>;

} // namespace dac

constexpr auto dac = dac::dac_t<dac::DAC_BASE>{};

namespace dbg {
  constexpr std::uint32_t DBG_BASE = 0xe004'2000;

  using idcode_tt = regs::dbg_idcode_v1_tt;
  using cr_tt = regs::dbg_cr_v1_tt;

  template <std::uint32_t baseaddress>
  using dbg_t =
    groov::group<"dbg",
                 groov::mmio_bus<>,
                 idcode_tt<"idcode", baseaddress, 0x0>,
                 cr_tt<"cr", baseaddress, 0x4>>;

} // namespace dbg

constexpr auto dbg = dbg::dbg_t<dbg::DBG_BASE>{};

namespace uart4 {
  constexpr std::uint32_t UART4_BASE = 0x4000'4c00;

  using sr_tt = regs::usart_sr_v2_tt;
  using dr_tt = regs::usart_dr_v1_tt;
  using brr_tt = regs::usart_brr_v1_tt;
  using cr1_tt = regs::usart_cr1_v1_tt;
  using cr2_tt = regs::usart_cr2_v2_tt;
  using cr3_tt = regs::usart_cr3_v2_tt;

  template <std::uint32_t baseaddress>
  using uart4_t =
    groov::group<"uart4",
                 groov::mmio_bus<>,
                 sr_tt<"sr", baseaddress, 0x0>,
                 dr_tt<"dr", baseaddress, 0x4>,
                 brr_tt<"brr", baseaddress, 0x8>,
                 cr1_tt<"cr1", baseaddress, 0xc>,
                 cr2_tt<"cr2", baseaddress, 0x10>,
                 cr3_tt<"cr3", baseaddress, 0x14>>;

} // namespace uart4

constexpr auto uart4 = uart4::uart4_t<uart4::UART4_BASE>{};

namespace uart5 {
  constexpr std::uint32_t UART5_BASE = 0x4000'5000;

  using sr_tt = regs::usart_sr_v2_tt;
  using dr_tt = regs::usart_dr_v1_tt;
  using brr_tt = regs::usart_brr_v1_tt;
  using cr1_tt = regs::usart_cr1_v1_tt;
  using cr2_tt = regs::usart_cr2_v2_tt;
  using cr3_tt = regs::usart_cr3_v3_tt;

  template <std::uint32_t baseaddress>
  using uart5_t =
    groov::group<"uart5",
                 groov::mmio_bus<>,
                 sr_tt<"sr", baseaddress, 0x0>,
                 dr_tt<"dr", baseaddress, 0x4>,
                 brr_tt<"brr", baseaddress, 0x8>,
                 cr1_tt<"cr1", baseaddress, 0xc>,
                 cr2_tt<"cr2", baseaddress, 0x10>,
                 cr3_tt<"cr3", baseaddress, 0x14>>;

} // namespace uart5

constexpr auto uart5 = uart5::uart5_t<uart5::UART5_BASE>{};

namespace crc {
  constexpr std::uint32_t CRC_BASE = 0x4002'3000;

  using dr_tt = regs::crc_dr_v1_tt;
  using idr_tt = regs::crc_idr_v1_tt;
  using cr_tt = regs::crc_cr_v1_tt;

  template <std::uint32_t baseaddress>
  using crc_t =
    groov::group<"crc",
                 groov::mmio_bus<>,
                 dr_tt<"dr", baseaddress, 0x0>,
                 idr_tt<"idr", baseaddress, 0x4>,
                 cr_tt<"cr", baseaddress, 0x8>>;

} // namespace crc

constexpr auto crc = crc::crc_t<crc::CRC_BASE>{};

namespace flash {
  constexpr std::uint32_t FLASH_BASE = 0x4002'2000;

  using acr_tt = regs::flash_acr_v1_tt;
  using keyr_tt = regs::flash_keyr_v1_tt;
  using optkeyr_tt = regs::flash_optkeyr_v1_tt;
  using sr_tt = regs::flash_sr_v1_tt;
  using cr_tt = regs::flash_cr_v1_tt;
  using ar_tt = regs::flash_ar_v1_tt;
  using obr_tt = regs::flash_obr_v1_tt;
  using wrpr_tt = regs::flash_wrpr_v1_tt;

  template <std::uint32_t baseaddress>
  using flash_t =
    groov::group<"flash",
                 groov::mmio_bus<>,
                 acr_tt<"acr", baseaddress, 0x0>,
                 keyr_tt<"keyr", baseaddress, 0x4>,
                 optkeyr_tt<"optkeyr", baseaddress, 0x8>,
                 sr_tt<"sr", baseaddress, 0xc>,
                 cr_tt<"cr", baseaddress, 0x10>,
                 ar_tt<"ar", baseaddress, 0x14>,
                 obr_tt<"obr", baseaddress, 0x1c>,
                 wrpr_tt<"wrpr", baseaddress, 0x20>>;

} // namespace flash

constexpr auto flash = flash::flash_t<flash::FLASH_BASE>{};

namespace tim15 {
  constexpr std::uint32_t TIM15_BASE = 0x4001'4000;

  using cr1_tt = regs::tim_cr1_v2_tt;
  using cr2_tt = regs::tim_cr2_v4_tt;
  using smcr_tt = regs::tim_smcr_v3_tt;
  using dier_tt = regs::tim_dier_v6_tt;
  using sr_tt = regs::tim_sr_v6_tt;
  using egr_tt = regs::tim_egr_v6_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v2_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v2_tt;
  using ccer_tt = regs::tim_ccer_v5_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using rcr_tt = regs::tim_rcr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using ccr2_tt = regs::tim_ccr2_v1_tt;
  using bdtr_tt = regs::tim_bdtr_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;

  template <std::uint32_t baseaddress>
  using tim15_t =
    groov::group<"tim15",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 smcr_tt<"smcr", baseaddress, 0x8>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 rcr_tt<"rcr", baseaddress, 0x30>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 ccr2_tt<"ccr2", baseaddress, 0x38>,
                 bdtr_tt<"bdtr", baseaddress, 0x44>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>>;

} // namespace tim15

constexpr auto tim15 = tim15::tim15_t<tim15::TIM15_BASE>{};

namespace tim16 {
  constexpr std::uint32_t TIM16_BASE = 0x4001'4400;

  using cr1_tt = regs::tim_cr1_v2_tt;
  using cr2_tt = regs::tim_cr2_v5_tt;
  using dier_tt = regs::tim_dier_v7_tt;
  using sr_tt = regs::tim_sr_v7_tt;
  using egr_tt = regs::tim_egr_v7_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v3_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v4_tt;
  using ccer_tt = regs::tim_ccer_v6_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using rcr_tt = regs::tim_rcr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using bdtr_tt = regs::tim_bdtr_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;

  template <std::uint32_t baseaddress>
  using tim16_t =
    groov::group<"tim16",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 rcr_tt<"rcr", baseaddress, 0x30>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 bdtr_tt<"bdtr", baseaddress, 0x44>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>>;

} // namespace tim16

constexpr auto tim16 = tim16::tim16_t<tim16::TIM16_BASE>{};

namespace cec {
  constexpr std::uint32_t CEC_BASE = 0x4000'7800;

  using cfgr_tt = regs::cec_cfgr_v1_tt;
  using oar_tt = regs::cec_oar_v1_tt;
  using pres_tt = regs::cec_pres_v1_tt;
  using esr_tt = regs::cec_esr_v1_tt;
  using csr_tt = regs::cec_csr_v1_tt;
  using txd_tt = regs::cec_txd_v1_tt;
  using rxd_tt = regs::cec_rxd_v1_tt;

  template <std::uint32_t baseaddress>
  using cec_t =
    groov::group<"cec",
                 groov::mmio_bus<>,
                 cfgr_tt<"cfgr", baseaddress, 0x0>,
                 oar_tt<"oar", baseaddress, 0x4>,
                 pres_tt<"pres", baseaddress, 0x8>,
                 esr_tt<"esr", baseaddress, 0xc>,
                 csr_tt<"csr", baseaddress, 0x10>,
                 txd_tt<"txd", baseaddress, 0x14>,
                 rxd_tt<"rxd", baseaddress, 0x18>>;

} // namespace cec

constexpr auto cec = cec::cec_t<cec::CEC_BASE>{};

namespace gpiob {
  constexpr std::uint32_t GPIOB_BASE = 0x4001'0c00;

  using crl_tt = regs::gpio_crl_v1_tt;
  using crh_tt = regs::gpio_crh_v1_tt;
  using idr_tt = regs::gpio_idr_v1_tt;
  using odr_tt = regs::gpio_odr_v1_tt;
  using bsrr_tt = regs::gpio_bsrr_v1_tt;
  using brr_tt = regs::gpio_brr_v1_tt;
  using lckr_tt = regs::gpio_lckr_v1_tt;

  template <std::uint32_t baseaddress>
  using gpiob_t =
    groov::group<"gpiob",
                 groov::mmio_bus<>,
                 crl_tt<"crl", baseaddress, 0x0>,
                 crh_tt<"crh", baseaddress, 0x4>,
                 idr_tt<"idr", baseaddress, 0x8>,
                 odr_tt<"odr", baseaddress, 0xc>,
                 bsrr_tt<"bsrr", baseaddress, 0x10>,
                 brr_tt<"brr", baseaddress, 0x14>,
                 lckr_tt<"lckr", baseaddress, 0x18>>;

} // namespace gpiob

constexpr auto gpiob = gpiob::gpiob_t<gpiob::GPIOB_BASE>{};

namespace gpioc {
  constexpr std::uint32_t GPIOC_BASE = 0x4001'1000;

  using crl_tt = regs::gpio_crl_v1_tt;
  using crh_tt = regs::gpio_crh_v1_tt;
  using idr_tt = regs::gpio_idr_v1_tt;
  using odr_tt = regs::gpio_odr_v1_tt;
  using bsrr_tt = regs::gpio_bsrr_v1_tt;
  using brr_tt = regs::gpio_brr_v1_tt;
  using lckr_tt = regs::gpio_lckr_v1_tt;

  template <std::uint32_t baseaddress>
  using gpioc_t =
    groov::group<"gpioc",
                 groov::mmio_bus<>,
                 crl_tt<"crl", baseaddress, 0x0>,
                 crh_tt<"crh", baseaddress, 0x4>,
                 idr_tt<"idr", baseaddress, 0x8>,
                 odr_tt<"odr", baseaddress, 0xc>,
                 bsrr_tt<"bsrr", baseaddress, 0x10>,
                 brr_tt<"brr", baseaddress, 0x14>,
                 lckr_tt<"lckr", baseaddress, 0x18>>;

} // namespace gpioc

constexpr auto gpioc = gpioc::gpioc_t<gpioc::GPIOC_BASE>{};

namespace gpiod {
  constexpr std::uint32_t GPIOD_BASE = 0x4001'1400;

  using crl_tt = regs::gpio_crl_v1_tt;
  using crh_tt = regs::gpio_crh_v1_tt;
  using idr_tt = regs::gpio_idr_v1_tt;
  using odr_tt = regs::gpio_odr_v1_tt;
  using bsrr_tt = regs::gpio_bsrr_v1_tt;
  using brr_tt = regs::gpio_brr_v1_tt;
  using lckr_tt = regs::gpio_lckr_v1_tt;

  template <std::uint32_t baseaddress>
  using gpiod_t =
    groov::group<"gpiod",
                 groov::mmio_bus<>,
                 crl_tt<"crl", baseaddress, 0x0>,
                 crh_tt<"crh", baseaddress, 0x4>,
                 idr_tt<"idr", baseaddress, 0x8>,
                 odr_tt<"odr", baseaddress, 0xc>,
                 bsrr_tt<"bsrr", baseaddress, 0x10>,
                 brr_tt<"brr", baseaddress, 0x14>,
                 lckr_tt<"lckr", baseaddress, 0x18>>;

} // namespace gpiod

constexpr auto gpiod = gpiod::gpiod_t<gpiod::GPIOD_BASE>{};

namespace gpioe {
  constexpr std::uint32_t GPIOE_BASE = 0x4001'1800;

  using crl_tt = regs::gpio_crl_v1_tt;
  using crh_tt = regs::gpio_crh_v1_tt;
  using idr_tt = regs::gpio_idr_v1_tt;
  using odr_tt = regs::gpio_odr_v1_tt;
  using bsrr_tt = regs::gpio_bsrr_v1_tt;
  using brr_tt = regs::gpio_brr_v1_tt;
  using lckr_tt = regs::gpio_lckr_v1_tt;

  template <std::uint32_t baseaddress>
  using gpioe_t =
    groov::group<"gpioe",
                 groov::mmio_bus<>,
                 crl_tt<"crl", baseaddress, 0x0>,
                 crh_tt<"crh", baseaddress, 0x4>,
                 idr_tt<"idr", baseaddress, 0x8>,
                 odr_tt<"odr", baseaddress, 0xc>,
                 bsrr_tt<"bsrr", baseaddress, 0x10>,
                 brr_tt<"brr", baseaddress, 0x14>,
                 lckr_tt<"lckr", baseaddress, 0x18>>;

} // namespace gpioe

constexpr auto gpioe = gpioe::gpioe_t<gpioe::GPIOE_BASE>{};

namespace gpiof {
  constexpr std::uint32_t GPIOF_BASE = 0x4001'1c00;

  using crl_tt = regs::gpio_crl_v1_tt;
  using crh_tt = regs::gpio_crh_v1_tt;
  using idr_tt = regs::gpio_idr_v1_tt;
  using odr_tt = regs::gpio_odr_v1_tt;
  using bsrr_tt = regs::gpio_bsrr_v1_tt;
  using brr_tt = regs::gpio_brr_v1_tt;
  using lckr_tt = regs::gpio_lckr_v1_tt;

  template <std::uint32_t baseaddress>
  using gpiof_t =
    groov::group<"gpiof",
                 groov::mmio_bus<>,
                 crl_tt<"crl", baseaddress, 0x0>,
                 crh_tt<"crh", baseaddress, 0x4>,
                 idr_tt<"idr", baseaddress, 0x8>,
                 odr_tt<"odr", baseaddress, 0xc>,
                 bsrr_tt<"bsrr", baseaddress, 0x10>,
                 brr_tt<"brr", baseaddress, 0x14>,
                 lckr_tt<"lckr", baseaddress, 0x18>>;

} // namespace gpiof

constexpr auto gpiof = gpiof::gpiof_t<gpiof::GPIOF_BASE>{};

namespace gpiog {
  constexpr std::uint32_t GPIOG_BASE = 0x4001'2000;

  using crl_tt = regs::gpio_crl_v1_tt;
  using crh_tt = regs::gpio_crh_v1_tt;
  using idr_tt = regs::gpio_idr_v1_tt;
  using odr_tt = regs::gpio_odr_v1_tt;
  using bsrr_tt = regs::gpio_bsrr_v1_tt;
  using brr_tt = regs::gpio_brr_v1_tt;
  using lckr_tt = regs::gpio_lckr_v1_tt;

  template <std::uint32_t baseaddress>
  using gpiog_t =
    groov::group<"gpiog",
                 groov::mmio_bus<>,
                 crl_tt<"crl", baseaddress, 0x0>,
                 crh_tt<"crh", baseaddress, 0x4>,
                 idr_tt<"idr", baseaddress, 0x8>,
                 odr_tt<"odr", baseaddress, 0xc>,
                 bsrr_tt<"bsrr", baseaddress, 0x10>,
                 brr_tt<"brr", baseaddress, 0x14>,
                 lckr_tt<"lckr", baseaddress, 0x18>>;

} // namespace gpiog

constexpr auto gpiog = gpiog::gpiog_t<gpiog::GPIOG_BASE>{};

namespace dma2 {
  constexpr std::uint32_t DMA2_BASE = 0x4002'0400;

  using isr_tt = regs::dma_isr_v1_tt;
  using ifcr_tt = regs::dma_ifcr_v1_tt;
  using ccr1_tt = regs::dma_ccr1_v1_tt;
  using cndtr1_tt = regs::dma_cndtr1_v1_tt;
  using cpar1_tt = regs::dma_cpar1_v1_tt;
  using cmar1_tt = regs::dma_cmar1_v1_tt;
  using ccr2_tt = regs::dma_ccr2_v1_tt;
  using cndtr2_tt = regs::dma_cndtr2_v1_tt;
  using cpar2_tt = regs::dma_cpar2_v1_tt;
  using cmar2_tt = regs::dma_cmar2_v1_tt;
  using ccr3_tt = regs::dma_ccr3_v1_tt;
  using cndtr3_tt = regs::dma_cndtr3_v1_tt;
  using cpar3_tt = regs::dma_cpar3_v1_tt;
  using cmar3_tt = regs::dma_cmar3_v1_tt;
  using ccr4_tt = regs::dma_ccr4_v1_tt;
  using cndtr4_tt = regs::dma_cndtr4_v1_tt;
  using cpar4_tt = regs::dma_cpar4_v1_tt;
  using cmar4_tt = regs::dma_cmar4_v1_tt;
  using ccr5_tt = regs::dma_ccr5_v1_tt;
  using cndtr5_tt = regs::dma_cndtr5_v1_tt;
  using cpar5_tt = regs::dma_cpar5_v1_tt;
  using cmar5_tt = regs::dma_cmar5_v1_tt;
  using ccr6_tt = regs::dma_ccr6_v1_tt;
  using cndtr6_tt = regs::dma_cndtr6_v1_tt;
  using cpar6_tt = regs::dma_cpar6_v1_tt;
  using cmar6_tt = regs::dma_cmar6_v1_tt;
  using ccr7_tt = regs::dma_ccr7_v1_tt;
  using cndtr7_tt = regs::dma_cndtr7_v1_tt;
  using cpar7_tt = regs::dma_cpar7_v1_tt;
  using cmar7_tt = regs::dma_cmar7_v1_tt;

  template <std::uint32_t baseaddress>
  using dma2_t =
    groov::group<"dma2",
                 groov::mmio_bus<>,
                 isr_tt<"isr", baseaddress, 0x0>,
                 ifcr_tt<"ifcr", baseaddress, 0x4>,
                 ccr1_tt<"ccr1", baseaddress, 0x8>,
                 cndtr1_tt<"cndtr1", baseaddress, 0xc>,
                 cpar1_tt<"cpar1", baseaddress, 0x10>,
                 cmar1_tt<"cmar1", baseaddress, 0x14>,
                 ccr2_tt<"ccr2", baseaddress, 0x1c>,
                 cndtr2_tt<"cndtr2", baseaddress, 0x20>,
                 cpar2_tt<"cpar2", baseaddress, 0x24>,
                 cmar2_tt<"cmar2", baseaddress, 0x28>,
                 ccr3_tt<"ccr3", baseaddress, 0x30>,
                 cndtr3_tt<"cndtr3", baseaddress, 0x34>,
                 cpar3_tt<"cpar3", baseaddress, 0x38>,
                 cmar3_tt<"cmar3", baseaddress, 0x3c>,
                 ccr4_tt<"ccr4", baseaddress, 0x44>,
                 cndtr4_tt<"cndtr4", baseaddress, 0x48>,
                 cpar4_tt<"cpar4", baseaddress, 0x4c>,
                 cmar4_tt<"cmar4", baseaddress, 0x50>,
                 ccr5_tt<"ccr5", baseaddress, 0x58>,
                 cndtr5_tt<"cndtr5", baseaddress, 0x5c>,
                 cpar5_tt<"cpar5", baseaddress, 0x60>,
                 cmar5_tt<"cmar5", baseaddress, 0x64>,
                 ccr6_tt<"ccr6", baseaddress, 0x6c>,
                 cndtr6_tt<"cndtr6", baseaddress, 0x70>,
                 cpar6_tt<"cpar6", baseaddress, 0x74>,
                 cmar6_tt<"cmar6", baseaddress, 0x78>,
                 ccr7_tt<"ccr7", baseaddress, 0x80>,
                 cndtr7_tt<"cndtr7", baseaddress, 0x84>,
                 cpar7_tt<"cpar7", baseaddress, 0x88>,
                 cmar7_tt<"cmar7", baseaddress, 0x8c>>;

} // namespace dma2

constexpr auto dma2 = dma2::dma2_t<dma2::DMA2_BASE>{};

namespace tim3 {
  constexpr std::uint32_t TIM3_BASE = 0x4000'0400;

  using cr1_tt = regs::tim_cr1_v1_tt;
  using cr2_tt = regs::tim_cr2_v2_tt;
  using smcr_tt = regs::tim_smcr_v2_tt;
  using dier_tt = regs::tim_dier_v2_tt;
  using sr_tt = regs::tim_sr_v2_tt;
  using egr_tt = regs::tim_egr_v2_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v1_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v2_tt;
  using ccmr2_output_tt = regs::tim_ccmr2_output_v1_tt;
  using ccmr2_input_tt = regs::tim_ccmr2_input_v2_tt;
  using ccer_tt = regs::tim_ccer_v2_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using ccr2_tt = regs::tim_ccr2_v1_tt;
  using ccr3_tt = regs::tim_ccr3_v1_tt;
  using ccr4_tt = regs::tim_ccr4_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;

  template <std::uint32_t baseaddress>
  using tim3_t =
    groov::group<"tim3",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 smcr_tt<"smcr", baseaddress, 0x8>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccmr2_output_tt<"ccmr2_output", baseaddress, 0x1c>,
                 ccmr2_input_tt<"ccmr2_input", baseaddress, 0x1c>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 ccr2_tt<"ccr2", baseaddress, 0x38>,
                 ccr3_tt<"ccr3", baseaddress, 0x3c>,
                 ccr4_tt<"ccr4", baseaddress, 0x40>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>>;

} // namespace tim3

constexpr auto tim3 = tim3::tim3_t<tim3::TIM3_BASE>{};

namespace tim4 {
  constexpr std::uint32_t TIM4_BASE = 0x4000'0800;

  using cr1_tt = regs::tim_cr1_v1_tt;
  using cr2_tt = regs::tim_cr2_v2_tt;
  using smcr_tt = regs::tim_smcr_v2_tt;
  using dier_tt = regs::tim_dier_v2_tt;
  using sr_tt = regs::tim_sr_v2_tt;
  using egr_tt = regs::tim_egr_v2_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v1_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v2_tt;
  using ccmr2_output_tt = regs::tim_ccmr2_output_v1_tt;
  using ccmr2_input_tt = regs::tim_ccmr2_input_v2_tt;
  using ccer_tt = regs::tim_ccer_v2_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using ccr2_tt = regs::tim_ccr2_v1_tt;
  using ccr3_tt = regs::tim_ccr3_v1_tt;
  using ccr4_tt = regs::tim_ccr4_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;

  template <std::uint32_t baseaddress>
  using tim4_t =
    groov::group<"tim4",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 smcr_tt<"smcr", baseaddress, 0x8>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccmr2_output_tt<"ccmr2_output", baseaddress, 0x1c>,
                 ccmr2_input_tt<"ccmr2_input", baseaddress, 0x1c>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 ccr2_tt<"ccr2", baseaddress, 0x38>,
                 ccr3_tt<"ccr3", baseaddress, 0x3c>,
                 ccr4_tt<"ccr4", baseaddress, 0x40>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>>;

} // namespace tim4

constexpr auto tim4 = tim4::tim4_t<tim4::TIM4_BASE>{};

namespace tim5 {
  constexpr std::uint32_t TIM5_BASE = 0x4000'0c00;

  using cr1_tt = regs::tim_cr1_v1_tt;
  using cr2_tt = regs::tim_cr2_v2_tt;
  using smcr_tt = regs::tim_smcr_v2_tt;
  using dier_tt = regs::tim_dier_v2_tt;
  using sr_tt = regs::tim_sr_v2_tt;
  using egr_tt = regs::tim_egr_v2_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v1_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v2_tt;
  using ccmr2_output_tt = regs::tim_ccmr2_output_v1_tt;
  using ccmr2_input_tt = regs::tim_ccmr2_input_v2_tt;
  using ccer_tt = regs::tim_ccer_v2_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using ccr2_tt = regs::tim_ccr2_v1_tt;
  using ccr3_tt = regs::tim_ccr3_v1_tt;
  using ccr4_tt = regs::tim_ccr4_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;

  template <std::uint32_t baseaddress>
  using tim5_t =
    groov::group<"tim5",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 smcr_tt<"smcr", baseaddress, 0x8>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccmr2_output_tt<"ccmr2_output", baseaddress, 0x1c>,
                 ccmr2_input_tt<"ccmr2_input", baseaddress, 0x1c>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 ccr2_tt<"ccr2", baseaddress, 0x38>,
                 ccr3_tt<"ccr3", baseaddress, 0x3c>,
                 ccr4_tt<"ccr4", baseaddress, 0x40>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>>;

} // namespace tim5

constexpr auto tim5 = tim5::tim5_t<tim5::TIM5_BASE>{};

namespace tim14 {
  constexpr std::uint32_t TIM14_BASE = 0x4000'2000;

  using cr1_tt = regs::tim_cr1_v3_tt;
  using dier_tt = regs::tim_dier_v4_tt;
  using sr_tt = regs::tim_sr_v4_tt;
  using egr_tt = regs::tim_egr_v4_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v3_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v4_tt;
  using ccer_tt = regs::tim_ccer_v4_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;

  template <std::uint32_t baseaddress>
  using tim14_t =
    groov::group<"tim14",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>>;

} // namespace tim14

constexpr auto tim14 = tim14::tim14_t<tim14::TIM14_BASE>{};

namespace tim7 {
  constexpr std::uint32_t TIM7_BASE = 0x4000'1400;

  using cr1_tt = regs::tim_cr1_v4_tt;
  using cr2_tt = regs::tim_cr2_v3_tt;
  using dier_tt = regs::tim_dier_v5_tt;
  using sr_tt = regs::tim_sr_v5_tt;
  using egr_tt = regs::tim_egr_v5_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;

  template <std::uint32_t baseaddress>
  using tim7_t =
    groov::group<"tim7",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>>;

} // namespace tim7

constexpr auto tim7 = tim7::tim7_t<tim7::TIM7_BASE>{};

namespace i2c2 {
  constexpr std::uint32_t I2C2_BASE = 0x4000'5800;

  using cr1_tt = regs::i2c_cr1_v1_tt;
  using cr2_tt = regs::i2c_cr2_v1_tt;
  using oar1_tt = regs::i2c_oar1_v1_tt;
  using oar2_tt = regs::i2c_oar2_v1_tt;
  using dr_tt = regs::i2c_dr_v1_tt;
  using sr1_tt = regs::i2c_sr1_v1_tt;
  using sr2_tt = regs::i2c_sr2_v1_tt;
  using ccr_tt = regs::i2c_ccr_v1_tt;
  using trise_tt = regs::i2c_trise_v1_tt;

  template <std::uint32_t baseaddress>
  using i2c2_t =
    groov::group<"i2c2",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 oar1_tt<"oar1", baseaddress, 0x8>,
                 oar2_tt<"oar2", baseaddress, 0xc>,
                 dr_tt<"dr", baseaddress, 0x10>,
                 sr1_tt<"sr1", baseaddress, 0x14>,
                 sr2_tt<"sr2", baseaddress, 0x18>,
                 ccr_tt<"ccr", baseaddress, 0x1c>,
                 trise_tt<"trise", baseaddress, 0x20>>;

} // namespace i2c2

constexpr auto i2c2 = i2c2::i2c2_t<i2c2::I2C2_BASE>{};

namespace spi2 {
  constexpr std::uint32_t SPI2_BASE = 0x4000'3800;

  using cr1_tt = regs::spi_cr1_v1_tt;
  using cr2_tt = regs::spi_cr2_v1_tt;
  using sr_tt = regs::spi_sr_v1_tt;
  using dr_tt = regs::spi_dr_v1_tt;
  using crcpr_tt = regs::spi_crcpr_v1_tt;
  using rxcrcr_tt = regs::spi_rxcrcr_v1_tt;
  using txcrcr_tt = regs::spi_txcrcr_v1_tt;

  template <std::uint32_t baseaddress>
  using spi2_t =
    groov::group<"spi2",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 sr_tt<"sr", baseaddress, 0x8>,
                 dr_tt<"dr", baseaddress, 0xc>,
                 crcpr_tt<"crcpr", baseaddress, 0x10>,
                 rxcrcr_tt<"rxcrcr", baseaddress, 0x14>,
                 txcrcr_tt<"txcrcr", baseaddress, 0x18>>;

} // namespace spi2

constexpr auto spi2 = spi2::spi2_t<spi2::SPI2_BASE>{};

namespace spi3 {
  constexpr std::uint32_t SPI3_BASE = 0x4000'3c00;

  using cr1_tt = regs::spi_cr1_v1_tt;
  using cr2_tt = regs::spi_cr2_v1_tt;
  using sr_tt = regs::spi_sr_v1_tt;
  using dr_tt = regs::spi_dr_v1_tt;
  using crcpr_tt = regs::spi_crcpr_v1_tt;
  using rxcrcr_tt = regs::spi_rxcrcr_v1_tt;
  using txcrcr_tt = regs::spi_txcrcr_v1_tt;

  template <std::uint32_t baseaddress>
  using spi3_t =
    groov::group<"spi3",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 sr_tt<"sr", baseaddress, 0x8>,
                 dr_tt<"dr", baseaddress, 0xc>,
                 crcpr_tt<"crcpr", baseaddress, 0x10>,
                 rxcrcr_tt<"rxcrcr", baseaddress, 0x14>,
                 txcrcr_tt<"txcrcr", baseaddress, 0x18>>;

} // namespace spi3

constexpr auto spi3 = spi3::spi3_t<spi3::SPI3_BASE>{};

namespace usart2 {
  constexpr std::uint32_t USART2_BASE = 0x4000'4400;

  using sr_tt = regs::usart_sr_v1_tt;
  using dr_tt = regs::usart_dr_v1_tt;
  using brr_tt = regs::usart_brr_v1_tt;
  using cr1_tt = regs::usart_cr1_v1_tt;
  using cr2_tt = regs::usart_cr2_v1_tt;
  using cr3_tt = regs::usart_cr3_v1_tt;
  using gtpr_tt = regs::usart_gtpr_v1_tt;

  template <std::uint32_t baseaddress>
  using usart2_t =
    groov::group<"usart2",
                 groov::mmio_bus<>,
                 sr_tt<"sr", baseaddress, 0x0>,
                 dr_tt<"dr", baseaddress, 0x4>,
                 brr_tt<"brr", baseaddress, 0x8>,
                 cr1_tt<"cr1", baseaddress, 0xc>,
                 cr2_tt<"cr2", baseaddress, 0x10>,
                 cr3_tt<"cr3", baseaddress, 0x14>,
                 gtpr_tt<"gtpr", baseaddress, 0x18>>;

} // namespace usart2

constexpr auto usart2 = usart2::usart2_t<usart2::USART2_BASE>{};

namespace usart3 {
  constexpr std::uint32_t USART3_BASE = 0x4000'4800;

  using sr_tt = regs::usart_sr_v1_tt;
  using dr_tt = regs::usart_dr_v1_tt;
  using brr_tt = regs::usart_brr_v1_tt;
  using cr1_tt = regs::usart_cr1_v1_tt;
  using cr2_tt = regs::usart_cr2_v1_tt;
  using cr3_tt = regs::usart_cr3_v1_tt;
  using gtpr_tt = regs::usart_gtpr_v1_tt;

  template <std::uint32_t baseaddress>
  using usart3_t =
    groov::group<"usart3",
                 groov::mmio_bus<>,
                 sr_tt<"sr", baseaddress, 0x0>,
                 dr_tt<"dr", baseaddress, 0x4>,
                 brr_tt<"brr", baseaddress, 0x8>,
                 cr1_tt<"cr1", baseaddress, 0xc>,
                 cr2_tt<"cr2", baseaddress, 0x10>,
                 cr3_tt<"cr3", baseaddress, 0x14>,
                 gtpr_tt<"gtpr", baseaddress, 0x18>>;

} // namespace usart3

constexpr auto usart3 = usart3::usart3_t<usart3::USART3_BASE>{};

namespace tim17 {
  constexpr std::uint32_t TIM17_BASE = 0x4001'4800;

  using cr1_tt = regs::tim_cr1_v2_tt;
  using cr2_tt = regs::tim_cr2_v5_tt;
  using dier_tt = regs::tim_dier_v7_tt;
  using sr_tt = regs::tim_sr_v7_tt;
  using egr_tt = regs::tim_egr_v7_tt;
  using ccmr1_output_tt = regs::tim_ccmr1_output_v3_tt;
  using ccmr1_input_tt = regs::tim_ccmr1_input_v4_tt;
  using ccer_tt = regs::tim_ccer_v6_tt;
  using cnt_tt = regs::tim_cnt_v1_tt;
  using psc_tt = regs::tim_psc_v1_tt;
  using arr_tt = regs::tim_arr_v1_tt;
  using rcr_tt = regs::tim_rcr_v1_tt;
  using ccr1_tt = regs::tim_ccr1_v1_tt;
  using bdtr_tt = regs::tim_bdtr_v1_tt;
  using dcr_tt = regs::tim_dcr_v1_tt;
  using dmar_tt = regs::tim_dmar_v1_tt;

  template <std::uint32_t baseaddress>
  using tim17_t =
    groov::group<"tim17",
                 groov::mmio_bus<>,
                 cr1_tt<"cr1", baseaddress, 0x0>,
                 cr2_tt<"cr2", baseaddress, 0x4>,
                 dier_tt<"dier", baseaddress, 0xc>,
                 sr_tt<"sr", baseaddress, 0x10>,
                 egr_tt<"egr", baseaddress, 0x14>,
                 ccmr1_output_tt<"ccmr1_output", baseaddress, 0x18>,
                 ccmr1_input_tt<"ccmr1_input", baseaddress, 0x18>,
                 ccer_tt<"ccer", baseaddress, 0x20>,
                 cnt_tt<"cnt", baseaddress, 0x24>,
                 psc_tt<"psc", baseaddress, 0x28>,
                 arr_tt<"arr", baseaddress, 0x2c>,
                 rcr_tt<"rcr", baseaddress, 0x30>,
                 ccr1_tt<"ccr1", baseaddress, 0x34>,
                 bdtr_tt<"bdtr", baseaddress, 0x44>,
                 dcr_tt<"dcr", baseaddress, 0x48>,
                 dmar_tt<"dmar", baseaddress, 0x4c>>;

} // namespace tim17

constexpr auto tim17 = tim17::tim17_t<tim17::TIM17_BASE>{};

} // namespace stm32
