/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>
#include <stm32/stm32l4x1/registers/sai.hpp>

namespace stm32::stm32l4x1 {

namespace sai1 {
  using bcr1_tt = regs::sai_bcr1_v1_tt;
  using bcr2_tt = regs::sai_bcr2_v1_tt;
  using bfrcr_tt = regs::sai_bfrcr_v1_tt;
  using bslotr_tt = regs::sai_bslotr_v1_tt;
  using bim_tt = regs::sai_bim_v1_tt;
  using bsr_tt = regs::sai_bsr_v1_tt;
  using bclrfr_tt = regs::sai_bclrfr_v1_tt;
  using bdr_tt = regs::sai_bdr_v1_tt;
  using acr1_tt = regs::sai_acr1_v1_tt;
  using acr2_tt = regs::sai_acr2_v1_tt;
  using afrcr_tt = regs::sai_afrcr_v1_tt;
  using aslotr_tt = regs::sai_aslotr_v1_tt;
  using aim_tt = regs::sai_aim_v1_tt;
  using asr_tt = regs::sai_asr_v1_tt;
  using aclrfr_tt = regs::sai_aclrfr_v1_tt;
  using adr_tt = regs::sai_adr_v1_tt;

  template <std::uint32_t baseaddress>
  using sai1_t =
    groov::group<"sai1",
                 groov::mmio_bus<>,
                 bcr1_tt<"bcr1", baseaddress, 0x24>,
                 bcr2_tt<"bcr2", baseaddress, 0x28>,
                 bfrcr_tt<"bfrcr", baseaddress, 0x2c>,
                 bslotr_tt<"bslotr", baseaddress, 0x30>,
                 bim_tt<"bim", baseaddress, 0x34>,
                 bsr_tt<"bsr", baseaddress, 0x38>,
                 bclrfr_tt<"bclrfr", baseaddress, 0x3c>,
                 bdr_tt<"bdr", baseaddress, 0x40>,
                 acr1_tt<"acr1", baseaddress, 0x4>,
                 acr2_tt<"acr2", baseaddress, 0x8>,
                 afrcr_tt<"afrcr", baseaddress, 0xc>,
                 aslotr_tt<"aslotr", baseaddress, 0x10>,
                 aim_tt<"aim", baseaddress, 0x14>,
                 asr_tt<"asr", baseaddress, 0x18>,
                 aclrfr_tt<"aclrfr", baseaddress, 0x1c>,
                 adr_tt<"adr", baseaddress, 0x20>>;

} // namespace sai1

} // namespace stm32::stm32l4x1
