#pragma once

#include <cstdint>
#include <groov/groov.hpp>

/* Intel groov for STM32H73x MCU, using CM7 cpu */
/* Generated by svd2groov */

namespace mcu {

using fmac_t = groov::group<
  "FMAC",
  groov::mmio_bus<>,
  groov::reg<
    "FMAC_X1BUFCFG",
    std::uint32_t,
    0x4802'4000 + 0u,
    groov::w::replace,
    groov::field<"X1_BASE", std::uint_fast8_t, 7u, 0u, groov::w::replace>,
    groov::field<"X1_BUF_SIZE", std::uint_fast8_t, 15u, 8u, groov::w::replace>,
    groov::field<"FULL_WM", std::uint_fast8_t, 25u, 24u, groov::w::replace>>,
  groov::reg<
    "FMAC_X2BUFCFG",
    std::uint32_t,
    0x4802'4000 + 0x4u,
    groov::w::replace,
    groov::field<"X2_BASE", std::uint_fast8_t, 7u, 0u, groov::w::replace>,
    groov::field<"X2_BUF_SIZE", std::uint_fast8_t, 15u, 8u, groov::w::replace>>,
  groov::reg<
    "FMAC_YBUFCFG",
    std::uint32_t,
    0x4802'4000 + 0x8u,
    groov::w::replace,
    groov::field<"Y_BASE", std::uint_fast8_t, 7u, 0u, groov::w::replace>,
    groov::field<"Y_BUF_SIZE", std::uint_fast8_t, 15u, 8u, groov::w::replace>,
    groov::field<"EMPTY_WM", std::uint_fast8_t, 25u, 24u, groov::w::replace>>,
  groov::reg<
    "FMAC_PARAM",
    std::uint32_t,
    0x4802'4000 + 0xcu,
    groov::w::replace,
    groov::field<"P", std::uint_fast8_t, 7u, 0u, groov::w::replace>,
    groov::field<"Q", std::uint_fast8_t, 15u, 8u, groov::w::replace>,
    groov::field<"R", std::uint_fast8_t, 23u, 16u, groov::w::replace>,
    groov::field<"FUNC", std::uint_fast8_t, 30u, 24u, groov::w::replace>,
    groov::field<"START", bool, 31u, 31u, groov::w::replace>>,
  groov::reg<"FMAC_CR",
             std::uint32_t,
             0x4802'4000 + 0x10u,
             groov::w::replace,
             groov::field<"RIEN", bool, 0u, 0u, groov::w::replace>,
             groov::field<"WIEN", bool, 1u, 1u, groov::w::replace>,
             groov::field<"OVFLIEN", bool, 2u, 2u, groov::w::replace>,
             groov::field<"UNFLIEN", bool, 3u, 3u, groov::w::replace>,
             groov::field<"SATIEN", bool, 4u, 4u, groov::w::replace>,
             groov::field<"DMAREN", bool, 8u, 8u, groov::w::replace>,
             groov::field<"DMAWEN", bool, 9u, 9u, groov::w::replace>,
             groov::field<"CLIPEN", bool, 15u, 15u, groov::w::replace>,
             groov::field<"RESET", bool, 16u, 16u, groov::w::replace>>,
  groov::reg<"FMAC_SR",
             std::uint32_t,
             0x4802'4000 + 0x14u,
             groov::w::replace,
             groov::field<"YEMPTY", bool, 0u, 0u, groov::w::replace>,
             groov::field<"X1FULL", bool, 1u, 1u, groov::w::replace>,
             groov::field<"OVFL", bool, 8u, 8u, groov::w::replace>,
             groov::field<"UNFL", bool, 9u, 9u, groov::w::replace>,
             groov::field<"SAT", bool, 10u, 10u, groov::w::replace>>,
  groov::reg<
    "FMAC_WDATA",
    std::uint32_t,
    0x4802'4000 + 0x18u,
    groov::w::replace,
    groov::field<"WDATA", std::uint_fast16_t, 15u, 0u, groov::w::replace>>,
  groov::reg<
    "FMAC_RDATA",
    std::uint32_t,
    0x4802'4000 + 0x1cu,
    groov::w::replace,
    groov::field<"RDATA", std::uint_fast16_t, 15u, 0u, groov::w::replace>>>;
constexpr auto fmac = fmac_t{};

} // namespace mcu
