/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace sec_adc12_common {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using adc12_csr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"reserved3", std::uint8_t, 31, 29>,
               groov::field<"ldordy_slv", bool, 28, 28>,
               groov::field<"reserved2", std::uint8_t, 27, 26>,
               groov::field<"awd3_slv", bool, 25, 25>,
               groov::field<"awd2_slv", bool, 24, 24>,
               groov::field<"awd1_slv", bool, 23, 23>,
               groov::field<"jeos_slv", bool, 22, 22>,
               groov::field<"jeoc_slv", bool, 21, 21>,
               groov::field<"ovr_slv", bool, 20, 20>,
               groov::field<"eos_slv", bool, 19, 19>,
               groov::field<"eoc_slv", bool, 18, 18>,
               groov::field<"eosmp_slv", bool, 17, 17>,
               groov::field<"adrdy_slv", bool, 16, 16>,
               groov::field<"reserved1", std::uint8_t, 15, 13>,
               groov::field<"ldordy_mst", bool, 12, 12>,
               groov::field<"reserved0", std::uint8_t, 11, 10>,
               groov::field<"awd3_mst", bool, 9, 9>,
               groov::field<"awd2_mst", bool, 8, 8>,
               groov::field<"awd1_mst", bool, 7, 7>,
               groov::field<"jeos_mst", bool, 6, 6>,
               groov::field<"jeoc_mst", bool, 5, 5>,
               groov::field<"ovr_mst", bool, 4, 4>,
               groov::field<"eos_mst", bool, 3, 3>,
               groov::field<"eoc_mst", bool, 2, 2>,
               groov::field<"eosmp_mst", bool, 1, 1>,
               groov::field<"adrdy_mst", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using adc12_ccr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"reserved3", std::uint8_t, 31, 25, access::ro>,
               groov::field<"vbaten", bool, 24, 24>,
               groov::field<"vsensesel", bool, 23, 23>,
               groov::field<"vrefen", bool, 22, 22>,
               groov::field<"presc", std::uint8_t, 21, 18>,
               groov::field<"reserved2", std::uint8_t, 17, 16, access::ro>,
               groov::field<"damdf", std::uint8_t, 15, 14>,
               groov::field<"reserved1", std::uint8_t, 13, 12, access::ro>,
               groov::field<"delay", std::uint8_t, 11, 8>,
               groov::field<"reserved0", std::uint8_t, 7, 5, access::ro>,
               groov::field<"dual", std::uint8_t, 4, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using adc12_cdr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"rdata_slv", std::uint16_t, 31, 16>,
               groov::field<"rdata_mst", std::uint16_t, 15, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using adc12_cdr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"rdata_alt", std::uint32_t, 31, 0>>;

} // namespace sec_adc12_common
