/* File autogenerated with
 * svd2groov, version: 0.1.0, branch: dev, hash: ce7ae6e
 */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32 {

namespace adc1 {

  constexpr std::uint32_t ADC1_BASE = 0x5004'0000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using adc1_t = groov::group<name,
                              groov::mmio_bus<>,
                              isr<baseaddress>,
                              ier<baseaddress>,
                              cr<baseaddress>,
                              cfgr<baseaddress>,
                              cfgr2<baseaddress>,
                              smpr1<baseaddress>,
                              smpr2<baseaddress>,
                              tr1<baseaddress>,
                              tr2<baseaddress>,
                              tr3<baseaddress>,
                              sqr1<baseaddress>,
                              sqr2<baseaddress>,
                              sqr3<baseaddress>,
                              sqr4<baseaddress>,
                              dr<baseaddress>,
                              jsqr<baseaddress>,
                              ofr1<baseaddress>,
                              ofr2<baseaddress>,
                              ofr3<baseaddress>,
                              ofr4<baseaddress>,
                              jdr1<baseaddress>,
                              jdr2<baseaddress>,
                              jdr3<baseaddress>,
                              jdr4<baseaddress>,
                              awd2cr<baseaddress>,
                              awd3cr<baseaddress>,
                              difsel<baseaddress>,
                              calfact<baseaddress>>;

  constexpr auto adc1 = adc1_t{};

} // namespace adc1

namespace adc2 {

  constexpr std::uint32_t ADC2_BASE = 0x5004'0100;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using adc2_t = groov::group<name,
                              groov::mmio_bus<>,
                              isr<baseaddress>,
                              ier<baseaddress>,
                              cr<baseaddress>,
                              cfgr<baseaddress>,
                              cfgr2<baseaddress>,
                              smpr1<baseaddress>,
                              smpr2<baseaddress>,
                              tr1<baseaddress>,
                              tr2<baseaddress>,
                              tr3<baseaddress>,
                              sqr1<baseaddress>,
                              sqr2<baseaddress>,
                              sqr3<baseaddress>,
                              sqr4<baseaddress>,
                              dr<baseaddress>,
                              jsqr<baseaddress>,
                              ofr1<baseaddress>,
                              ofr2<baseaddress>,
                              ofr3<baseaddress>,
                              ofr4<baseaddress>,
                              jdr1<baseaddress>,
                              jdr2<baseaddress>,
                              jdr3<baseaddress>,
                              jdr4<baseaddress>,
                              awd2cr<baseaddress>,
                              awd3cr<baseaddress>,
                              difsel<baseaddress>,
                              calfact<baseaddress>>;

  constexpr auto adc2 = adc2_t{};

} // namespace adc2

namespace adc12_common {

  constexpr std::uint32_t ADC12_COMMON_BASE = 0x5004'0300;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using adc12_common_t = groov::group<name,
                                      groov::mmio_bus<>,
                                      csr<baseaddress>,
                                      ccr<baseaddress>,
                                      cdr<baseaddress>>;

  constexpr auto adc12_common = adc12_common_t{};

} // namespace adc12_common

namespace comp {

  constexpr std::uint32_t COMP_BASE = 0x4001'0200;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using comp_t = groov::group<name,
                              groov::mmio_bus<>,
                              comp1_csr<baseaddress>,
                              comp2_csr<baseaddress>>;

  constexpr auto comp = comp_t{};

} // namespace comp

namespace crc {

  constexpr std::uint32_t CRC_BASE = 0x4002'3000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using crc_t = groov::group<name,
                             groov::mmio_bus<>,
                             dr<baseaddress>,
                             idr<baseaddress>,
                             cr<baseaddress>,
                             init<baseaddress>,
                             pol<baseaddress>>;

  constexpr auto crc = crc_t{};

} // namespace crc

namespace crs {

  constexpr std::uint32_t CRS_BASE = 0x4000'6000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using crs_t = groov::group<name,
                             groov::mmio_bus<>,
                             cr<baseaddress>,
                             cfgr<baseaddress>,
                             isr<baseaddress>,
                             icr<baseaddress>>;

  constexpr auto crs = crs_t{};

} // namespace crs

namespace dbgmcu {

  constexpr std::uint32_t DBGMCU_BASE = 0xe004'2000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using dbgmcu_t = groov::group<name,
                                groov::mmio_bus<>,
                                idcode<baseaddress>,
                                cr<baseaddress>,
                                apb1fzr1<baseaddress>,
                                apb1fzr2<baseaddress>,
                                apb2fzr<baseaddress>>;

  constexpr auto dbgmcu = dbgmcu_t{};

} // namespace dbgmcu

namespace dma1 {

  constexpr std::uint32_t DMA1_BASE = 0x4002'0000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using dma1_t = groov::group<name,
                              groov::mmio_bus<>,
                              isr<baseaddress>,
                              ifcr<baseaddress>,
                              ccr1<baseaddress>,
                              cndtr1<baseaddress>,
                              cpar1<baseaddress>,
                              cmar1<baseaddress>,
                              ccr2<baseaddress>,
                              cndtr2<baseaddress>,
                              cpar2<baseaddress>,
                              cmar2<baseaddress>,
                              ccr3<baseaddress>,
                              cndtr3<baseaddress>,
                              cpar3<baseaddress>,
                              cmar3<baseaddress>,
                              ccr4<baseaddress>,
                              cndtr4<baseaddress>,
                              cpar4<baseaddress>,
                              cmar4<baseaddress>,
                              ccr5<baseaddress>,
                              cndtr5<baseaddress>,
                              cpar5<baseaddress>,
                              cmar5<baseaddress>,
                              ccr6<baseaddress>,
                              cndtr6<baseaddress>,
                              cpar6<baseaddress>,
                              cmar6<baseaddress>,
                              ccr7<baseaddress>,
                              cndtr7<baseaddress>,
                              cpar7<baseaddress>,
                              cmar7<baseaddress>,
                              cselr<baseaddress>>;

  constexpr auto dma1 = dma1_t{};

} // namespace dma1

namespace dma2 {

  constexpr std::uint32_t DMA2_BASE = 0x4002'0400;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using dma2_t = groov::group<name,
                              groov::mmio_bus<>,
                              isr<baseaddress>,
                              ifcr<baseaddress>,
                              ccr1<baseaddress>,
                              cndtr1<baseaddress>,
                              cpar1<baseaddress>,
                              cmar1<baseaddress>,
                              ccr2<baseaddress>,
                              cndtr2<baseaddress>,
                              cpar2<baseaddress>,
                              cmar2<baseaddress>,
                              ccr3<baseaddress>,
                              cndtr3<baseaddress>,
                              cpar3<baseaddress>,
                              cmar3<baseaddress>,
                              ccr4<baseaddress>,
                              cndtr4<baseaddress>,
                              cpar4<baseaddress>,
                              cmar4<baseaddress>,
                              ccr5<baseaddress>,
                              cndtr5<baseaddress>,
                              cpar5<baseaddress>,
                              cmar5<baseaddress>,
                              ccr6<baseaddress>,
                              cndtr6<baseaddress>,
                              cpar6<baseaddress>,
                              cmar6<baseaddress>,
                              ccr7<baseaddress>,
                              cndtr7<baseaddress>,
                              cpar7<baseaddress>,
                              cmar7<baseaddress>,
                              cselr<baseaddress>>;

  constexpr auto dma2 = dma2_t{};

} // namespace dma2

namespace exti {

  constexpr std::uint32_t EXTI_BASE = 0x4001'0400;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using exti_t = groov::group<name,
                              groov::mmio_bus<>,
                              imr1<baseaddress>,
                              emr1<baseaddress>,
                              rtsr1<baseaddress>,
                              ftsr1<baseaddress>,
                              swier1<baseaddress>,
                              pr1<baseaddress>,
                              imr2<baseaddress>,
                              emr2<baseaddress>,
                              rtsr2<baseaddress>,
                              ftsr2<baseaddress>,
                              swier2<baseaddress>,
                              pr2<baseaddress>>;

  constexpr auto exti = exti_t{};

} // namespace exti

namespace firewall {

  constexpr std::uint32_t FIREWALL_BASE = 0x4001'1c00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using firewall_t = groov::group<name,
                                  groov::mmio_bus<>,
                                  cssa<baseaddress>,
                                  csl<baseaddress>,
                                  nvdssa<baseaddress>,
                                  nvdsl<baseaddress>,
                                  vdssa<baseaddress>,
                                  vdsl<baseaddress>,
                                  cr<baseaddress>>;

  constexpr auto firewall = firewall_t{};

} // namespace firewall

namespace flash {

  constexpr std::uint32_t FLASH_BASE = 0x4002'2000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using flash_t = groov::group<name,
                               groov::mmio_bus<>,
                               acr<baseaddress>,
                               pdkeyr<baseaddress>,
                               keyr<baseaddress>,
                               optkeyr<baseaddress>,
                               sr<baseaddress>,
                               cr<baseaddress>,
                               eccr<baseaddress>,
                               optr<baseaddress>,
                               pcrop1sr<baseaddress>,
                               pcrop1er<baseaddress>,
                               wrp1ar<baseaddress>,
                               wrp1br<baseaddress>>;

  constexpr auto flash = flash_t{};

} // namespace flash

namespace fpu {

  constexpr std::uint32_t FPU_BASE = 0xe000'ef34;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using fpu_t = groov::group<name,
                             groov::mmio_bus<>,
                             fpccr<baseaddress>,
                             fpcar<baseaddress>,
                             fpscr<baseaddress>>;

  constexpr auto fpu = fpu_t{};

} // namespace fpu

namespace fpu_cpacr {

  constexpr std::uint32_t FPU_CPACR_BASE = 0xe000'ed88;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using fpu_cpacr_t = groov::group<name, groov::mmio_bus<>, cpacr<baseaddress>>;

  constexpr auto fpu_cpacr = fpu_cpacr_t{};

} // namespace fpu_cpacr

namespace i2c1 {

  constexpr std::uint32_t I2C1_BASE = 0x4000'5400;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using i2c1_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              oar1<baseaddress>,
                              oar2<baseaddress>,
                              timingr<baseaddress>,
                              timeoutr<baseaddress>,
                              isr<baseaddress>,
                              icr<baseaddress>,
                              pecr<baseaddress>,
                              rxdr<baseaddress>,
                              txdr<baseaddress>>;

  constexpr auto i2c1 = i2c1_t{};

} // namespace i2c1

namespace i2c2 {

  constexpr std::uint32_t I2C2_BASE = 0x4000'5800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using i2c2_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              oar1<baseaddress>,
                              oar2<baseaddress>,
                              timingr<baseaddress>,
                              timeoutr<baseaddress>,
                              isr<baseaddress>,
                              icr<baseaddress>,
                              pecr<baseaddress>,
                              rxdr<baseaddress>,
                              txdr<baseaddress>>;

  constexpr auto i2c2 = i2c2_t{};

} // namespace i2c2

namespace i2c3 {

  constexpr std::uint32_t I2C3_BASE = 0x4000'5c00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using i2c3_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              oar1<baseaddress>,
                              oar2<baseaddress>,
                              timingr<baseaddress>,
                              timeoutr<baseaddress>,
                              isr<baseaddress>,
                              icr<baseaddress>,
                              pecr<baseaddress>,
                              rxdr<baseaddress>,
                              txdr<baseaddress>>;

  constexpr auto i2c3 = i2c3_t{};

} // namespace i2c3

namespace iwdg {

  constexpr std::uint32_t IWDG_BASE = 0x4000'3000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using iwdg_t = groov::group<name,
                              groov::mmio_bus<>,
                              kr<baseaddress>,
                              pr<baseaddress>,
                              rlr<baseaddress>,
                              sr<baseaddress>,
                              winr<baseaddress>>;

  constexpr auto iwdg = iwdg_t{};

} // namespace iwdg

namespace lptim1 {

  constexpr std::uint32_t LPTIM1_BASE = 0x4000'7c00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using lptim1_t = groov::group<name,
                                groov::mmio_bus<>,
                                isr<baseaddress>,
                                icr<baseaddress>,
                                ier<baseaddress>,
                                cfgr<baseaddress>,
                                cr<baseaddress>,
                                cmp<baseaddress>,
                                arr<baseaddress>,
                                cnt<baseaddress>,
                                or <baseaddress>,
                                cfgr2<baseaddress>,
                                rcr<baseaddress>>;

  constexpr auto lptim1 = lptim1_t{};

} // namespace lptim1

namespace lptim2 {

  constexpr std::uint32_t LPTIM2_BASE = 0x4000'9400;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using lptim2_t = groov::group<name,
                                groov::mmio_bus<>,
                                isr<baseaddress>,
                                icr<baseaddress>,
                                ier<baseaddress>,
                                cfgr<baseaddress>,
                                cr<baseaddress>,
                                cmp<baseaddress>,
                                arr<baseaddress>,
                                cnt<baseaddress>,
                                or <baseaddress>,
                                cfgr2<baseaddress>,
                                rcr<baseaddress>>;

  constexpr auto lptim2 = lptim2_t{};

} // namespace lptim2

namespace lpuart1 {

  constexpr std::uint32_t LPUART1_BASE = 0x4000'8000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using lpuart1_t = groov::group<name,
                                 groov::mmio_bus<>,
                                 cr1<baseaddress>,
                                 cr2<baseaddress>,
                                 cr3<baseaddress>,
                                 brr<baseaddress>,
                                 rqr<baseaddress>,
                                 isr<baseaddress>,
                                 icr<baseaddress>,
                                 rdr<baseaddress>,
                                 tdr<baseaddress>>;

  constexpr auto lpuart1 = lpuart1_t{};

} // namespace lpuart1

namespace mpu {

  constexpr std::uint32_t MPU_BASE = 0xe000'ed90;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using mpu_t = groov::group<name,
                             groov::mmio_bus<>,
                             mpu_typer<baseaddress>,
                             mpu_ctrl<baseaddress>,
                             mpu_rnr<baseaddress>,
                             mpu_rbar<baseaddress>,
                             mpu_rasr<baseaddress>>;

  constexpr auto mpu = mpu_t{};

} // namespace mpu

namespace nvic {

  constexpr std::uint32_t NVIC_BASE = 0xe000'e100;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using nvic_t = groov::group<name,
                              groov::mmio_bus<>,
                              iser0<baseaddress>,
                              iser1<baseaddress>,
                              iser2<baseaddress>,
                              icer0<baseaddress>,
                              icer1<baseaddress>,
                              icer2<baseaddress>,
                              ispr0<baseaddress>,
                              ispr1<baseaddress>,
                              ispr2<baseaddress>,
                              icpr0<baseaddress>,
                              icpr1<baseaddress>,
                              icpr2<baseaddress>,
                              iabr0<baseaddress>,
                              iabr1<baseaddress>,
                              iabr2<baseaddress>,
                              ipr0<baseaddress>,
                              ipr1<baseaddress>,
                              ipr2<baseaddress>,
                              ipr3<baseaddress>,
                              ipr4<baseaddress>,
                              ipr5<baseaddress>,
                              ipr6<baseaddress>,
                              ipr7<baseaddress>,
                              ipr8<baseaddress>,
                              ipr9<baseaddress>,
                              ipr10<baseaddress>,
                              ipr11<baseaddress>,
                              ipr12<baseaddress>,
                              ipr13<baseaddress>,
                              ipr14<baseaddress>,
                              ipr15<baseaddress>,
                              ipr16<baseaddress>,
                              ipr17<baseaddress>,
                              ipr18<baseaddress>,
                              ipr19<baseaddress>,
                              ipr20<baseaddress>,
                              ipr21<baseaddress>,
                              ipr22<baseaddress>>;

  constexpr auto nvic = nvic_t{};

} // namespace nvic

namespace nvic_stir {

  constexpr std::uint32_t NVIC_STIR_BASE = 0xe000'ef00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using nvic_stir_t = groov::group<name, groov::mmio_bus<>, stir<baseaddress>>;

  constexpr auto nvic_stir = nvic_stir_t{};

} // namespace nvic_stir

namespace opamp {

  constexpr std::uint32_t OPAMP_BASE = 0x4000'7800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using opamp_t = groov::group<name,
                               groov::mmio_bus<>,
                               opamp1_csr<baseaddress>,
                               opamp1_otr<baseaddress>,
                               opamp1_lpotr<baseaddress>,
                               opamp2_csr<baseaddress>,
                               opamp2_otr<baseaddress>,
                               opamp2_lpotr<baseaddress>>;

  constexpr auto opamp = opamp_t{};

} // namespace opamp

namespace pwr {

  constexpr std::uint32_t PWR_BASE = 0x4000'7000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using pwr_t = groov::group<name,
                             groov::mmio_bus<>,
                             cr1<baseaddress>,
                             cr2<baseaddress>,
                             cr3<baseaddress>,
                             cr4<baseaddress>,
                             sr1<baseaddress>,
                             sr2<baseaddress>,
                             scr<baseaddress>,
                             pucra<baseaddress>,
                             pdcra<baseaddress>,
                             pucrb<baseaddress>,
                             pdcrb<baseaddress>,
                             pucrc<baseaddress>,
                             pdcrc<baseaddress>,
                             pucrd<baseaddress>,
                             pdcrd<baseaddress>,
                             pucre<baseaddress>,
                             pdcre<baseaddress>,
                             pucrh<baseaddress>,
                             pdcrh<baseaddress>>;

  constexpr auto pwr = pwr_t{};

} // namespace pwr

namespace rng {

  constexpr std::uint32_t RNG_BASE = 0x5006'0800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using rng_t = groov::group<name,
                             groov::mmio_bus<>,
                             cr<baseaddress>,
                             sr<baseaddress>,
                             dr<baseaddress>>;

  constexpr auto rng = rng_t{};

} // namespace rng

namespace rtc {

  constexpr std::uint32_t RTC_BASE = 0x4000'2800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using rtc_t = groov::group<name,
                             groov::mmio_bus<>,
                             tr<baseaddress>,
                             dr<baseaddress>,
                             ssr<baseaddress>,
                             icsr<baseaddress>,
                             prer<baseaddress>,
                             wutr<baseaddress>,
                             alrmar<baseaddress>,
                             wpr<baseaddress>,
                             shiftr<baseaddress>,
                             tstr<baseaddress>,
                             tsdr<baseaddress>,
                             tsssr<baseaddress>,
                             calr<baseaddress>,
                             alrmassr<baseaddress>,
                             alrmbr<baseaddress>,
                             alrmbssr<baseaddress>,
                             sr<baseaddress>,
                             misr<baseaddress>,
                             scr<baseaddress>,
                             cr<baseaddress>>;

  constexpr auto rtc = rtc_t{};

} // namespace rtc

namespace scb {

  constexpr std::uint32_t SCB_BASE = 0xe000'ed00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using scb_t = groov::group<name,
                             groov::mmio_bus<>,
                             cpuid<baseaddress>,
                             icsr<baseaddress>,
                             vtor<baseaddress>,
                             aircr<baseaddress>,
                             scr<baseaddress>,
                             ccr<baseaddress>,
                             shpr1<baseaddress>,
                             shpr2<baseaddress>,
                             shpr3<baseaddress>,
                             shcsr<baseaddress>,
                             cfsr_ufsr_bfsr_mmfsr<baseaddress>,
                             hfsr<baseaddress>,
                             mmfar<baseaddress>,
                             bfar<baseaddress>,
                             afsr<baseaddress>>;

  constexpr auto scb = scb_t{};

} // namespace scb

namespace scb_actrl {

  constexpr std::uint32_t SCB_ACTRL_BASE = 0xe000'e008;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using scb_actrl_t = groov::group<name, groov::mmio_bus<>, actrl<baseaddress>>;

  constexpr auto scb_actrl = scb_actrl_t{};

} // namespace scb_actrl

namespace spi1 {

  constexpr std::uint32_t SPI1_BASE = 0x4001'3000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using spi1_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              sr<baseaddress>,
                              dr<baseaddress>,
                              crcpr<baseaddress>,
                              rxcrcr<baseaddress>,
                              txcrcr<baseaddress>>;

  constexpr auto spi1 = spi1_t{};

} // namespace spi1

namespace spi2 {

  constexpr std::uint32_t SPI2_BASE = 0x4000'3800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using spi2_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              sr<baseaddress>,
                              dr<baseaddress>,
                              crcpr<baseaddress>,
                              rxcrcr<baseaddress>,
                              txcrcr<baseaddress>>;

  constexpr auto spi2 = spi2_t{};

} // namespace spi2

namespace stk {

  constexpr std::uint32_t STK_BASE = 0xe000'e010;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using stk_t = groov::group<name,
                             groov::mmio_bus<>,
                             ctrl<baseaddress>,
                             load<baseaddress>,
                             val<baseaddress>,
                             calib<baseaddress>>;

  constexpr auto stk = stk_t{};

} // namespace stk

namespace syscfg {

  constexpr std::uint32_t SYSCFG_BASE = 0x4001'0000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using syscfg_t = groov::group<name,
                                groov::mmio_bus<>,
                                memrmp<baseaddress>,
                                cfgr1<baseaddress>,
                                exticr1<baseaddress>,
                                exticr2<baseaddress>,
                                exticr3<baseaddress>,
                                exticr4<baseaddress>,
                                scsr<baseaddress>,
                                cfgr2<baseaddress>,
                                swpr<baseaddress>,
                                skr<baseaddress>>;

  constexpr auto syscfg = syscfg_t{};

} // namespace syscfg

namespace tim1 {

  constexpr std::uint32_t TIM1_BASE = 0x4001'2c00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using tim1_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              smcr<baseaddress>,
                              dier<baseaddress>,
                              sr<baseaddress>,
                              egr<baseaddress>,
                              ccmr1_output<baseaddress>,
                              ccmr1_input<baseaddress>,
                              ccmr2_output<baseaddress>,
                              ccmr2_input<baseaddress>,
                              ccer<baseaddress>,
                              cnt<baseaddress>,
                              psc<baseaddress>,
                              arr<baseaddress>,
                              rcr<baseaddress>,
                              ccr1<baseaddress>,
                              ccr2<baseaddress>,
                              ccr3<baseaddress>,
                              ccr4<baseaddress>,
                              bdtr<baseaddress>,
                              dcr<baseaddress>,
                              dmar<baseaddress>,
                              or1<baseaddress>,
                              ccmr3_output<baseaddress>,
                              ccr5<baseaddress>,
                              ccr6<baseaddress>,
                              or2<baseaddress>,
                              or3<baseaddress>>;

  constexpr auto tim1 = tim1_t{};

} // namespace tim1

namespace tim15 {

  constexpr std::uint32_t TIM15_BASE = 0x4001'4000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using tim15_t = groov::group<name,
                               groov::mmio_bus<>,
                               cr1<baseaddress>,
                               cr2<baseaddress>,
                               dier<baseaddress>,
                               sr<baseaddress>,
                               egr<baseaddress>,
                               ccmr1_output<baseaddress>,
                               ccmr1_input<baseaddress>,
                               ccer<baseaddress>,
                               cnt<baseaddress>,
                               psc<baseaddress>,
                               arr<baseaddress>,
                               rcr<baseaddress>,
                               ccr1<baseaddress>,
                               bdtr<baseaddress>,
                               dcr<baseaddress>,
                               dmar<baseaddress>,
                               smcr<baseaddress>,
                               ccr2<baseaddress>,
                               or1<baseaddress>,
                               or2<baseaddress>>;

  constexpr auto tim15 = tim15_t{};

} // namespace tim15

namespace tim16 {

  constexpr std::uint32_t TIM16_BASE = 0x4001'4400;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using tim16_t = groov::group<name,
                               groov::mmio_bus<>,
                               cr1<baseaddress>,
                               cr2<baseaddress>,
                               dier<baseaddress>,
                               sr<baseaddress>,
                               egr<baseaddress>,
                               ccmr1_output<baseaddress>,
                               ccmr1_input<baseaddress>,
                               ccer<baseaddress>,
                               cnt<baseaddress>,
                               psc<baseaddress>,
                               arr<baseaddress>,
                               rcr<baseaddress>,
                               ccr1<baseaddress>,
                               bdtr<baseaddress>,
                               dcr<baseaddress>,
                               dmar<baseaddress>,
                               or1<baseaddress>,
                               or2<baseaddress>>;

  constexpr auto tim16 = tim16_t{};

} // namespace tim16

namespace tim2 {

  constexpr std::uint32_t TIM2_BASE = 0x4000'0000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using tim2_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              smcr<baseaddress>,
                              dier<baseaddress>,
                              sr<baseaddress>,
                              egr<baseaddress>,
                              ccmr1_output<baseaddress>,
                              ccmr1_input<baseaddress>,
                              ccmr2_output<baseaddress>,
                              ccmr2_input<baseaddress>,
                              ccer<baseaddress>,
                              cnt<baseaddress>,
                              psc<baseaddress>,
                              arr<baseaddress>,
                              ccr1<baseaddress>,
                              ccr2<baseaddress>,
                              ccr3<baseaddress>,
                              ccr4<baseaddress>,
                              dcr<baseaddress>,
                              dmar<baseaddress>,
                              or1<baseaddress>,
                              or2<baseaddress>>;

  constexpr auto tim2 = tim2_t{};

} // namespace tim2

namespace tim6 {

  constexpr std::uint32_t TIM6_BASE = 0x4000'1000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using tim6_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr1<baseaddress>,
                              cr2<baseaddress>,
                              dier<baseaddress>,
                              sr<baseaddress>,
                              egr<baseaddress>,
                              cnt<baseaddress>,
                              psc<baseaddress>,
                              arr<baseaddress>>;

  constexpr auto tim6 = tim6_t{};

} // namespace tim6

namespace tsc {

  constexpr std::uint32_t TSC_BASE = 0x4002'4000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using tsc_t = groov::group<name,
                             groov::mmio_bus<>,
                             cr<baseaddress>,
                             ier<baseaddress>,
                             icr<baseaddress>,
                             isr<baseaddress>,
                             iohcr<baseaddress>,
                             ioascr<baseaddress>,
                             ioscr<baseaddress>,
                             ioccr<baseaddress>,
                             iogcsr<baseaddress>,
                             iog1cr<baseaddress>,
                             iog2cr<baseaddress>,
                             iog3cr<baseaddress>,
                             iog4cr<baseaddress>,
                             iog5cr<baseaddress>,
                             iog6cr<baseaddress>,
                             iog7cr<baseaddress>,
                             iog8cr<baseaddress>>;

  constexpr auto tsc = tsc_t{};

} // namespace tsc

namespace usart1 {

  constexpr std::uint32_t USART1_BASE = 0x4001'3800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using usart1_t = groov::group<name,
                                groov::mmio_bus<>,
                                cr1<baseaddress>,
                                cr2<baseaddress>,
                                cr3<baseaddress>,
                                brr<baseaddress>,
                                gtpr<baseaddress>,
                                rtor<baseaddress>,
                                rqr<baseaddress>,
                                isr<baseaddress>,
                                icr<baseaddress>,
                                rdr<baseaddress>,
                                tdr<baseaddress>>;

  constexpr auto usart1 = usart1_t{};

} // namespace usart1

namespace wwdg {

  constexpr std::uint32_t WWDG_BASE = 0x4000'2c00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using wwdg_t = groov::group<name,
                              groov::mmio_bus<>,
                              cr<baseaddress>,
                              cfr<baseaddress>,
                              sr<baseaddress>>;

  constexpr auto wwdg = wwdg_t{};

} // namespace wwdg

namespace quadspi {

  constexpr std::uint32_t QUADSPI_BASE = 0xa000'1000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using quadspi_t = groov::group<name,
                                 groov::mmio_bus<>,
                                 cr<baseaddress>,
                                 dcr<baseaddress>,
                                 sr<baseaddress>,
                                 fcr<baseaddress>,
                                 dlr<baseaddress>,
                                 ccr<baseaddress>,
                                 ar<baseaddress>,
                                 abr<baseaddress>,
                                 dr<baseaddress>,
                                 psmkr<baseaddress>,
                                 psmar<baseaddress>,
                                 pir<baseaddress>,
                                 lptr<baseaddress>>;

  constexpr auto quadspi = quadspi_t{};

} // namespace quadspi

namespace gpioa {

  constexpr std::uint32_t GPIOA_BASE = 0x4800'0000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gpioa_t = groov::group<name,
                               groov::mmio_bus<>,
                               moder<baseaddress>,
                               otyper<baseaddress>,
                               ospeedr<baseaddress>,
                               pupdr<baseaddress>,
                               idr<baseaddress>,
                               odr<baseaddress>,
                               bsrr<baseaddress>,
                               lckr<baseaddress>,
                               afrl<baseaddress>,
                               afrh<baseaddress>,
                               brr<baseaddress>>;

  constexpr auto gpioa = gpioa_t{};

} // namespace gpioa

namespace gpiob {

  constexpr std::uint32_t GPIOB_BASE = 0x4800'0400;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gpiob_t = groov::group<name,
                               groov::mmio_bus<>,
                               moder<baseaddress>,
                               otyper<baseaddress>,
                               ospeedr<baseaddress>,
                               pupdr<baseaddress>,
                               idr<baseaddress>,
                               odr<baseaddress>,
                               bsrr<baseaddress>,
                               lckr<baseaddress>,
                               afrl<baseaddress>,
                               afrh<baseaddress>,
                               brr<baseaddress>>;

  constexpr auto gpiob = gpiob_t{};

} // namespace gpiob

namespace gpioc {

  constexpr std::uint32_t GPIOC_BASE = 0x4800'0800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gpioc_t = groov::group<name,
                               groov::mmio_bus<>,
                               moder<baseaddress>,
                               otyper<baseaddress>,
                               ospeedr<baseaddress>,
                               pupdr<baseaddress>,
                               idr<baseaddress>,
                               odr<baseaddress>,
                               bsrr<baseaddress>,
                               lckr<baseaddress>,
                               afrl<baseaddress>,
                               afrh<baseaddress>,
                               brr<baseaddress>>;

  constexpr auto gpioc = gpioc_t{};

} // namespace gpioc

namespace gpiod {

  constexpr std::uint32_t GPIOD_BASE = 0x4800'0c00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gpiod_t = groov::group<name,
                               groov::mmio_bus<>,
                               moder<baseaddress>,
                               otyper<baseaddress>,
                               ospeedr<baseaddress>,
                               pupdr<baseaddress>,
                               idr<baseaddress>,
                               odr<baseaddress>,
                               bsrr<baseaddress>,
                               lckr<baseaddress>,
                               afrl<baseaddress>,
                               afrh<baseaddress>,
                               brr<baseaddress>>;

  constexpr auto gpiod = gpiod_t{};

} // namespace gpiod

namespace gpioh {

  constexpr std::uint32_t GPIOH_BASE = 0x4800'1c00;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using gpioh_t = groov::group<name,
                               groov::mmio_bus<>,
                               moder<baseaddress>,
                               otyper<baseaddress>,
                               ospeedr<baseaddress>,
                               pupdr<baseaddress>,
                               idr<baseaddress>,
                               odr<baseaddress>,
                               bsrr<baseaddress>,
                               lckr<baseaddress>,
                               afrl<baseaddress>,
                               afrh<baseaddress>,
                               brr<baseaddress>>;

  constexpr auto gpioh = gpioh_t{};

} // namespace gpioh

namespace rcc {

  constexpr std::uint32_t RCC_BASE = 0x4002'1000;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using rcc_t = groov::group<name,
                             groov::mmio_bus<>,
                             cr<baseaddress>,
                             icscr<baseaddress>,
                             cfgr<baseaddress>,
                             pllcfgr<baseaddress>,
                             cier<baseaddress>,
                             cifr<baseaddress>,
                             cicr<baseaddress>,
                             ahb1rstr<baseaddress>,
                             ahb2rstr<baseaddress>,
                             ahb3rstr<baseaddress>,
                             apb1rstr1<baseaddress>,
                             apb1rstr2<baseaddress>,
                             apb2rstr<baseaddress>,
                             ahb1enr<baseaddress>,
                             ahb2enr<baseaddress>,
                             ahb3enr<baseaddress>,
                             apb1enr1<baseaddress>,
                             apb1enr2<baseaddress>,
                             apb2enr<baseaddress>,
                             ahb1smenr<baseaddress>,
                             ahb2smenr<baseaddress>,
                             ahb3smenr<baseaddress>,
                             apb1smenr1<baseaddress>,
                             apb1smenr2<baseaddress>,
                             apb2smenr<baseaddress>,
                             ccipr<baseaddress>,
                             bdcr<baseaddress>,
                             csr<baseaddress>,
                             crrcr<baseaddress>,
                             ccipr2<baseaddress>>;

  constexpr auto rcc = rcc_t{};

} // namespace rcc

namespace usb {

  constexpr std::uint32_t USB_BASE = 0x4000'6800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using usb_t = groov::group<name,
                             groov::mmio_bus<>,
                             ep0r<baseaddress>,
                             ep1r<baseaddress>,
                             ep2r<baseaddress>,
                             ep3r<baseaddress>,
                             ep4r<baseaddress>,
                             ep5r<baseaddress>,
                             ep6r<baseaddress>,
                             ep7r<baseaddress>,
                             cntr<baseaddress>,
                             istr<baseaddress>,
                             fnr<baseaddress>,
                             daddr<baseaddress>,
                             btable<baseaddress>,
                             lpmcsr<baseaddress>,
                             bcdr<baseaddress>,
                             count0_tx<baseaddress>,
                             count1_tx<baseaddress>,
                             count2_tx<baseaddress>,
                             count3_tx<baseaddress>,
                             count4_tx<baseaddress>,
                             count5_tx<baseaddress>,
                             count6_tx<baseaddress>,
                             count7_tx<baseaddress>,
                             addr2_tx<baseaddress>,
                             addr3_tx<baseaddress>,
                             addr4_tx<baseaddress>,
                             addr5_tx<baseaddress>,
                             addr6_tx<baseaddress>,
                             addr7_tx<baseaddress>,
                             addr0_rx<baseaddress>,
                             addr1_rx<baseaddress>,
                             addr2_rx<baseaddress>,
                             addr3_rx<baseaddress>,
                             addr4_rx<baseaddress>,
                             addr5_rx<baseaddress>,
                             addr6_rx<baseaddress>,
                             addr7_rx<baseaddress>,
                             count0_rx<baseaddress>,
                             count1_rx<baseaddress>,
                             count2_rx<baseaddress>,
                             count3_rx<baseaddress>,
                             count4_rx<baseaddress>,
                             count5_rx<baseaddress>,
                             count6_rx<baseaddress>,
                             count7_rx<baseaddress>>;

  constexpr auto usb = usb_t{};

} // namespace usb

namespace usart2 {

  constexpr std::uint32_t USART2_BASE = 0x4000'4400;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using usart2_t = groov::group<name,
                                groov::mmio_bus<>,
                                cr1<baseaddress>,
                                cr2<baseaddress>,
                                cr3<baseaddress>,
                                brr<baseaddress>,
                                gtpr<baseaddress>,
                                rtor<baseaddress>,
                                rqr<baseaddress>,
                                isr<baseaddress>,
                                icr<baseaddress>,
                                rdr<baseaddress>,
                                tdr<baseaddress>>;

  constexpr auto usart2 = usart2_t{};

} // namespace usart2

namespace usart3 {

  constexpr std::uint32_t USART3_BASE = 0x4000'4800;
  template <stdx::ct_string name, std::uint32_t baseaddress>
  using usart3_t = groov::group<name,
                                groov::mmio_bus<>,
                                cr1<baseaddress>,
                                cr2<baseaddress>,
                                cr3<baseaddress>,
                                brr<baseaddress>,
                                gtpr<baseaddress>,
                                rtor<baseaddress>,
                                rqr<baseaddress>,
                                isr<baseaddress>,
                                icr<baseaddress>,
                                rdr<baseaddress>,
                                tdr<baseaddress>>;

  constexpr auto usart3 = usart3_t{};

} // namespace usart3

} // namespace stm32
