#pragma once

#include <cstdint>
#include <groov/groov.hpp>

/* Intel groov for STM32G030 MCU, using CM0 cpu */
/* Generated by svd2groov */

namespace mcu {

using dbg_t = groov::group<
  "DBG",
  groov::mmio_bus<>,
  groov::reg<"IDCODE",
             std::uint32_t,
             0x4001'5800 + 0u,
             groov::read_only<groov::w::replace>,
             groov::field<"DEV_ID",
                          std::uint_fast16_t,
                          11u,
                          0u,
                          groov::read_only<groov::w::replace>>,
             groov::field<"REV_ID",
                          std::uint_fast16_t,
                          31u,
                          16u,
                          groov::read_only<groov::w::replace>>>,
  groov::reg<"CR",
             std::uint32_t,
             0x4001'5800 + 0x4u,
             groov::w::replace,
             groov::field<"DBG_STOP", bool, 1u, 1u, groov::w::replace>,
             groov::field<"DBG_STANDBY", bool, 2u, 2u, groov::w::replace>>,
  groov::reg<"APB_FZ1",
             std::uint32_t,
             0x4001'5800 + 0x8u,
             groov::w::replace,
             groov::field<"DBG_TIM2_STOP", bool, 0u, 0u, groov::w::replace>,
             groov::field<"DBG_TIM3_STOP", bool, 1u, 1u, groov::w::replace>,
             groov::field<"DBG_RTC_STOP", bool, 10u, 10u, groov::w::replace>,
             groov::field<"DBG_WWDG_STOP", bool, 11u, 11u, groov::w::replace>,
             groov::field<"DBG_IWDG_STOP", bool, 12u, 12u, groov::w::replace>,
             groov::field<"DBG_I2C1_STOP", bool, 21u, 21u, groov::w::replace>>,
  groov::reg<
    "APB_FZ2",
    std::uint32_t,
    0x4001'5800 + 0xcu,
    groov::w::replace,
    groov::field<"DBG_TIM1_STOP", bool, 11u, 11u, groov::w::replace>,
    groov::field<"DBG_TIM14_STOP", bool, 15u, 15u, groov::w::replace>,
    groov::field<"DBG_TIM16_STOP", bool, 17u, 17u, groov::w::replace>,
    groov::field<"DBG_TIM17_STOP", bool, 18u, 18u, groov::w::replace>>>;
constexpr auto dbg = dbg_t{};

} // namespace mcu
