/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace nvic {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using iser0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"setena", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using iser1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"setena", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using iser2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"setena", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using icer0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"clrena", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using icer1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"clrena", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using icer2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"clrena", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ispr0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"setpend", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ispr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"setpend", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ispr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"setpend", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using icpr0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"clrpend", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using icpr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"clrpend", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using icpr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"clrpend", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using iabr0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"active", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using iabr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"active", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using iabr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"active", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr0_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr1_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr2_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr3_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr4_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr5_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr6_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr7_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr8_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr9_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr10_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr11_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr12_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr13_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr14_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr15_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr16_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr17_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr18_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr19_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr20_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr21_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ipr22_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"ipr_n3", std::uint8_t, 31, 24>,
               groov::field<"ipr_n2", std::uint8_t, 23, 16>,
               groov::field<"ipr_n1", std::uint8_t, 15, 8>,
               groov::field<"ipr_n0", std::uint8_t, 7, 0>>;

} // namespace nvic
