/* File autogenerated with svd2groov */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>
namespace stm32 {

namespace ethernet_ptp {

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptptscr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 6, access::ro>,
               groov::field<"TSARU", bool, 5, 5>,
               groov::field<"TSITE", bool, 4, 4>,
               groov::field<"TSSTU", bool, 3, 3>,
               groov::field<"TSSTI", bool, 2, 2>,
               groov::field<"TSFCU", bool, 1, 1>,
               groov::field<"TSE", bool, 0, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptpssir_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"RESERVED0", std::uint32_t, 31, 8, access::ro>,
               groov::field<"STSSI", std::uint8_t, 7, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptptshr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"STS", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptptslr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::ro,
               groov::field<"STPNS", bool, 31, 31>,
               groov::field<"STSS", std::uint32_t, 30, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptptshur_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"TSUS", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptptslur_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"TSUPNS", bool, 31, 31>,
               groov::field<"TSUSS", std::uint32_t, 30, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptptsar_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"TSA", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptptthr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"TTSH", std::uint32_t, 31, 0>>;

  template <stdx::ct_string name,
            std::uint32_t   baseaddress,
            std::uint32_t   offset>
  using ptpttlr_tt =
    groov::reg<name,
               std::uint32_t,
               baseaddress + offset,
               access::rw,
               groov::field<"TTSL", std::uint32_t, 31, 0>>;

} // namespace ethernet_ptp
