/* File autogenerated with
 * svd2groov, version: 0.1.0, branch: dev, hash: ce7ae6e
 */
#pragma once

#include <groov/groov.hpp>

#include <stm32/common/access.hpp>
#include <stm32/common/bittypes.hpp>

namespace stm32 {

namespace crc {

  constexpr std::uint32_t CRC_BASE = 0x4002'3000;
  template <std::uint32_t baseaddress>
  using crc_t = groov::group<crc,
                             groov::mmio_bus<>,
                             dr_tt<"DR", baseaddress, 0>,
                             idr_tt<"IDR", baseaddress, 0x4>,
                             cr_tt<"CR", baseaddress, 0x8>,
                             init_tt<"INIT", baseaddress, 0xc>>;

  constexpr auto crc = crc_t{};

} // namespace crc

namespace gpiof {

  constexpr std::uint32_t GPIOF_BASE = 0x4800'1400;
  template <std::uint32_t baseaddress>
  using gpiof_t = groov::group<gpiof,
                               groov::mmio_bus<>,
                               moder_tt<"MODER", baseaddress, 0>,
                               otyper_tt<"OTYPER", baseaddress, 0x4>,
                               ospeedr_tt<"OSPEEDR", baseaddress, 0x8>,
                               pupdr_tt<"PUPDR", baseaddress, 0xc>,
                               idr_tt<"IDR", baseaddress, 0x10>,
                               odr_tt<"ODR", baseaddress, 0x14>,
                               bsrr_tt<"BSRR", baseaddress, 0x18>,
                               lckr_tt<"LCKR", baseaddress, 0x1c>,
                               afrl_tt<"AFRL", baseaddress, 0x20>,
                               afrh_tt<"AFRH", baseaddress, 0x24>,
                               brr_tt<"BRR", baseaddress, 0x28>>;

  constexpr auto gpiof = gpiof_t{};

} // namespace gpiof

namespace gpiod {

  constexpr std::uint32_t GPIOD_BASE = 0x4800'0c00;
  template <std::uint32_t baseaddress>
  using gpiod_t = groov::group<gpiod,
                               groov::mmio_bus<>,
                               moder_tt<"MODER", baseaddress, 0>,
                               otyper_tt<"OTYPER", baseaddress, 0x4>,
                               ospeedr_tt<"OSPEEDR", baseaddress, 0x8>,
                               pupdr_tt<"PUPDR", baseaddress, 0xc>,
                               idr_tt<"IDR", baseaddress, 0x10>,
                               odr_tt<"ODR", baseaddress, 0x14>,
                               bsrr_tt<"BSRR", baseaddress, 0x18>,
                               lckr_tt<"LCKR", baseaddress, 0x1c>,
                               afrl_tt<"AFRL", baseaddress, 0x20>,
                               afrh_tt<"AFRH", baseaddress, 0x24>,
                               brr_tt<"BRR", baseaddress, 0x28>>;

  constexpr auto gpiod = gpiod_t{};

} // namespace gpiod

namespace gpioc {

  constexpr std::uint32_t GPIOC_BASE = 0x4800'0800;
  template <std::uint32_t baseaddress>
  using gpioc_t = groov::group<gpioc,
                               groov::mmio_bus<>,
                               moder_tt<"MODER", baseaddress, 0>,
                               otyper_tt<"OTYPER", baseaddress, 0x4>,
                               ospeedr_tt<"OSPEEDR", baseaddress, 0x8>,
                               pupdr_tt<"PUPDR", baseaddress, 0xc>,
                               idr_tt<"IDR", baseaddress, 0x10>,
                               odr_tt<"ODR", baseaddress, 0x14>,
                               bsrr_tt<"BSRR", baseaddress, 0x18>,
                               lckr_tt<"LCKR", baseaddress, 0x1c>,
                               afrl_tt<"AFRL", baseaddress, 0x20>,
                               afrh_tt<"AFRH", baseaddress, 0x24>,
                               brr_tt<"BRR", baseaddress, 0x28>>;

  constexpr auto gpioc = gpioc_t{};

} // namespace gpioc

namespace gpiob {

  constexpr std::uint32_t GPIOB_BASE = 0x4800'0400;
  template <std::uint32_t baseaddress>
  using gpiob_t = groov::group<gpiob,
                               groov::mmio_bus<>,
                               moder_tt<"MODER", baseaddress, 0>,
                               otyper_tt<"OTYPER", baseaddress, 0x4>,
                               ospeedr_tt<"OSPEEDR", baseaddress, 0x8>,
                               pupdr_tt<"PUPDR", baseaddress, 0xc>,
                               idr_tt<"IDR", baseaddress, 0x10>,
                               odr_tt<"ODR", baseaddress, 0x14>,
                               bsrr_tt<"BSRR", baseaddress, 0x18>,
                               lckr_tt<"LCKR", baseaddress, 0x1c>,
                               afrl_tt<"AFRL", baseaddress, 0x20>,
                               afrh_tt<"AFRH", baseaddress, 0x24>,
                               brr_tt<"BRR", baseaddress, 0x28>>;

  constexpr auto gpiob = gpiob_t{};

} // namespace gpiob

namespace gpioa {

  constexpr std::uint32_t GPIOA_BASE = 0x4800'0000;
  template <std::uint32_t baseaddress>
  using gpioa_t = groov::group<gpioa,
                               groov::mmio_bus<>,
                               moder_tt<"MODER", baseaddress, 0>,
                               otyper_tt<"OTYPER", baseaddress, 0x4>,
                               ospeedr_tt<"OSPEEDR", baseaddress, 0x8>,
                               pupdr_tt<"PUPDR", baseaddress, 0xc>,
                               idr_tt<"IDR", baseaddress, 0x10>,
                               odr_tt<"ODR", baseaddress, 0x14>,
                               bsrr_tt<"BSRR", baseaddress, 0x18>,
                               lckr_tt<"LCKR", baseaddress, 0x1c>,
                               afrl_tt<"AFRL", baseaddress, 0x20>,
                               afrh_tt<"AFRH", baseaddress, 0x24>,
                               brr_tt<"BRR", baseaddress, 0x28>>;

  constexpr auto gpioa = gpioa_t{};

} // namespace gpioa

namespace spi1 {

  constexpr std::uint32_t SPI1_BASE = 0x4001'3000;
  template <std::uint32_t baseaddress>
  using spi1_t = groov::group<spi1,
                              groov::mmio_bus<>,
                              cr1_tt<"CR1", baseaddress, 0>,
                              cr2_tt<"CR2", baseaddress, 0x4>,
                              sr_tt<"SR", baseaddress, 0x8>,
                              dr_tt<"DR", baseaddress, 0xc>,
                              crcpr_tt<"CRCPR", baseaddress, 0x10>,
                              rxcrcr_tt<"RXCRCR", baseaddress, 0x14>,
                              txcrcr_tt<"TXCRCR", baseaddress, 0x18>,
                              i2scfgr_tt<"I2SCFGR", baseaddress, 0x1c>,
                              i2spr_tt<"I2SPR", baseaddress, 0x20>>;

  constexpr auto spi1 = spi1_t{};

} // namespace spi1

namespace spi2 {

  constexpr std::uint32_t SPI2_BASE = 0x4000'3800;
  template <std::uint32_t baseaddress>
  using spi2_t = groov::group<spi2,
                              groov::mmio_bus<>,
                              cr1_tt<"CR1", baseaddress, 0>,
                              cr2_tt<"CR2", baseaddress, 0x4>,
                              sr_tt<"SR", baseaddress, 0x8>,
                              dr_tt<"DR", baseaddress, 0xc>,
                              crcpr_tt<"CRCPR", baseaddress, 0x10>,
                              rxcrcr_tt<"RXCRCR", baseaddress, 0x14>,
                              txcrcr_tt<"TXCRCR", baseaddress, 0x18>,
                              i2scfgr_tt<"I2SCFGR", baseaddress, 0x1c>,
                              i2spr_tt<"I2SPR", baseaddress, 0x20>>;

  constexpr auto spi2 = spi2_t{};

} // namespace spi2

namespace pwr {

  constexpr std::uint32_t PWR_BASE = 0x4000'7000;
  template <std::uint32_t baseaddress>
  using pwr_t = groov::group<pwr,
                             groov::mmio_bus<>,
                             cr_tt<"CR", baseaddress, 0>,
                             csr_tt<"CSR", baseaddress, 0x4>>;

  constexpr auto pwr = pwr_t{};

} // namespace pwr

namespace i2c1 {

  constexpr std::uint32_t I2C1_BASE = 0x4000'5400;
  template <std::uint32_t baseaddress>
  using i2c1_t = groov::group<i2c1,
                              groov::mmio_bus<>,
                              cr1_tt<"CR1", baseaddress, 0>,
                              cr2_tt<"CR2", baseaddress, 0x4>,
                              oar1_tt<"OAR1", baseaddress, 0x8>,
                              oar2_tt<"OAR2", baseaddress, 0xc>,
                              timingr_tt<"TIMINGR", baseaddress, 0x10>,
                              timeoutr_tt<"TIMEOUTR", baseaddress, 0x14>,
                              isr_tt<"ISR", baseaddress, 0x18>,
                              icr_tt<"ICR", baseaddress, 0x1c>,
                              pecr_tt<"PECR", baseaddress, 0x20>,
                              rxdr_tt<"RXDR", baseaddress, 0x24>,
                              txdr_tt<"TXDR", baseaddress, 0x28>>;

  constexpr auto i2c1 = i2c1_t{};

} // namespace i2c1

namespace i2c2 {

  constexpr std::uint32_t I2C2_BASE = 0x4000'5800;
  template <std::uint32_t baseaddress>
  using i2c2_t = groov::group<i2c2,
                              groov::mmio_bus<>,
                              cr1_tt<"CR1", baseaddress, 0>,
                              cr2_tt<"CR2", baseaddress, 0x4>,
                              oar1_tt<"OAR1", baseaddress, 0x8>,
                              oar2_tt<"OAR2", baseaddress, 0xc>,
                              timingr_tt<"TIMINGR", baseaddress, 0x10>,
                              timeoutr_tt<"TIMEOUTR", baseaddress, 0x14>,
                              isr_tt<"ISR", baseaddress, 0x18>,
                              icr_tt<"ICR", baseaddress, 0x1c>,
                              pecr_tt<"PECR", baseaddress, 0x20>,
                              rxdr_tt<"RXDR", baseaddress, 0x24>,
                              txdr_tt<"TXDR", baseaddress, 0x28>>;

  constexpr auto i2c2 = i2c2_t{};

} // namespace i2c2

namespace iwdg {

  constexpr std::uint32_t IWDG_BASE = 0x4000'3000;
  template <std::uint32_t baseaddress>
  using iwdg_t = groov::group<iwdg,
                              groov::mmio_bus<>,
                              kr_tt<"KR", baseaddress, 0>,
                              pr_tt<"PR", baseaddress, 0x4>,
                              rlr_tt<"RLR", baseaddress, 0x8>,
                              sr_tt<"SR", baseaddress, 0xc>,
                              winr_tt<"WINR", baseaddress, 0x10>>;

  constexpr auto iwdg = iwdg_t{};

} // namespace iwdg

namespace wwdg {

  constexpr std::uint32_t WWDG_BASE = 0x4000'2c00;
  template <std::uint32_t baseaddress>
  using wwdg_t = groov::group<wwdg,
                              groov::mmio_bus<>,
                              cr_tt<"CR", baseaddress, 0>,
                              cfr_tt<"CFR", baseaddress, 0x4>,
                              sr_tt<"SR", baseaddress, 0x8>>;

  constexpr auto wwdg = wwdg_t{};

} // namespace wwdg

namespace tim1 {

  constexpr std::uint32_t TIM1_BASE = 0x4001'2c00;
  template <std::uint32_t baseaddress>
  using tim1_t =
    groov::group<tim1,
                 groov::mmio_bus<>,
                 cr1_tt<"CR1", baseaddress, 0>,
                 cr2_tt<"CR2", baseaddress, 0x4>,
                 smcr_tt<"SMCR", baseaddress, 0x8>,
                 dier_tt<"DIER", baseaddress, 0xc>,
                 sr_tt<"SR", baseaddress, 0x10>,
                 egr_tt<"EGR", baseaddress, 0x14>,
                 ccmr1_output_tt<"CCMR1_OUTPUT", baseaddress, 0x18>,
                 ccmr1_input_tt<"CCMR1_INPUT", baseaddress, 0x18>,
                 ccmr2_output_tt<"CCMR2_OUTPUT", baseaddress, 0x1c>,
                 ccmr2_input_tt<"CCMR2_INPUT", baseaddress, 0x1c>,
                 ccer_tt<"CCER", baseaddress, 0x20>,
                 cnt_tt<"CNT", baseaddress, 0x24>,
                 psc_tt<"PSC", baseaddress, 0x28>,
                 arr_tt<"ARR", baseaddress, 0x2c>,
                 rcr_tt<"RCR", baseaddress, 0x30>,
                 ccr1_tt<"CCR1", baseaddress, 0x34>,
                 ccr2_tt<"CCR2", baseaddress, 0x38>,
                 ccr3_tt<"CCR3", baseaddress, 0x3c>,
                 ccr4_tt<"CCR4", baseaddress, 0x40>,
                 bdtr_tt<"BDTR", baseaddress, 0x44>,
                 dcr_tt<"DCR", baseaddress, 0x48>,
                 dmar_tt<"DMAR", baseaddress, 0x4c>>;

  constexpr auto tim1 = tim1_t{};

} // namespace tim1

namespace tim3 {

  constexpr std::uint32_t TIM3_BASE = 0x4000'0400;
  template <std::uint32_t baseaddress>
  using tim3_t =
    groov::group<tim3,
                 groov::mmio_bus<>,
                 cr1_tt<"CR1", baseaddress, 0>,
                 cr2_tt<"CR2", baseaddress, 0x4>,
                 smcr_tt<"SMCR", baseaddress, 0x8>,
                 dier_tt<"DIER", baseaddress, 0xc>,
                 sr_tt<"SR", baseaddress, 0x10>,
                 egr_tt<"EGR", baseaddress, 0x14>,
                 ccmr1_output_tt<"CCMR1_OUTPUT", baseaddress, 0x18>,
                 ccmr1_input_tt<"CCMR1_INPUT", baseaddress, 0x18>,
                 ccmr2_output_tt<"CCMR2_OUTPUT", baseaddress, 0x1c>,
                 ccmr2_input_tt<"CCMR2_INPUT", baseaddress, 0x1c>,
                 ccer_tt<"CCER", baseaddress, 0x20>,
                 cnt_tt<"CNT", baseaddress, 0x24>,
                 psc_tt<"PSC", baseaddress, 0x28>,
                 arr_tt<"ARR", baseaddress, 0x2c>,
                 ccr1_tt<"CCR1", baseaddress, 0x34>,
                 ccr2_tt<"CCR2", baseaddress, 0x38>,
                 ccr3_tt<"CCR3", baseaddress, 0x3c>,
                 ccr4_tt<"CCR4", baseaddress, 0x40>,
                 dcr_tt<"DCR", baseaddress, 0x48>,
                 dmar_tt<"DMAR", baseaddress, 0x4c>>;

  constexpr auto tim3 = tim3_t{};

} // namespace tim3

namespace tim14 {

  constexpr std::uint32_t TIM14_BASE = 0x4000'2000;
  template <std::uint32_t baseaddress>
  using tim14_t =
    groov::group<tim14,
                 groov::mmio_bus<>,
                 cr1_tt<"CR1", baseaddress, 0>,
                 dier_tt<"DIER", baseaddress, 0xc>,
                 sr_tt<"SR", baseaddress, 0x10>,
                 egr_tt<"EGR", baseaddress, 0x14>,
                 ccmr1_output_tt<"CCMR1_OUTPUT", baseaddress, 0x18>,
                 ccmr1_input_tt<"CCMR1_INPUT", baseaddress, 0x18>,
                 ccer_tt<"CCER", baseaddress, 0x20>,
                 cnt_tt<"CNT", baseaddress, 0x24>,
                 psc_tt<"PSC", baseaddress, 0x28>,
                 arr_tt<"ARR", baseaddress, 0x2c>,
                 ccr1_tt<"CCR1", baseaddress, 0x34>,
                 or_tt<"OR", baseaddress, 0x50>>;

  constexpr auto tim14 = tim14_t{};

} // namespace tim14

namespace tim6 {

  constexpr std::uint32_t TIM6_BASE = 0x4000'1000;
  template <std::uint32_t baseaddress>
  using tim6_t = groov::group<tim6,
                              groov::mmio_bus<>,
                              cr1_tt<"CR1", baseaddress, 0>,
                              cr2_tt<"CR2", baseaddress, 0x4>,
                              dier_tt<"DIER", baseaddress, 0xc>,
                              sr_tt<"SR", baseaddress, 0x10>,
                              egr_tt<"EGR", baseaddress, 0x14>,
                              cnt_tt<"CNT", baseaddress, 0x24>,
                              psc_tt<"PSC", baseaddress, 0x28>,
                              arr_tt<"ARR", baseaddress, 0x2c>>;

  constexpr auto tim6 = tim6_t{};

} // namespace tim6

namespace tim7 {

  constexpr std::uint32_t TIM7_BASE = 0x4000'1400;
  template <std::uint32_t baseaddress>
  using tim7_t = groov::group<tim7,
                              groov::mmio_bus<>,
                              cr1_tt<"CR1", baseaddress, 0>,
                              cr2_tt<"CR2", baseaddress, 0x4>,
                              dier_tt<"DIER", baseaddress, 0xc>,
                              sr_tt<"SR", baseaddress, 0x10>,
                              egr_tt<"EGR", baseaddress, 0x14>,
                              cnt_tt<"CNT", baseaddress, 0x24>,
                              psc_tt<"PSC", baseaddress, 0x28>,
                              arr_tt<"ARR", baseaddress, 0x2c>>;

  constexpr auto tim7 = tim7_t{};

} // namespace tim7

namespace exti {

  constexpr std::uint32_t EXTI_BASE = 0x4001'0400;
  template <std::uint32_t baseaddress>
  using exti_t = groov::group<exti,
                              groov::mmio_bus<>,
                              imr_tt<"IMR", baseaddress, 0>,
                              emr_tt<"EMR", baseaddress, 0x4>,
                              rtsr_tt<"RTSR", baseaddress, 0x8>,
                              ftsr_tt<"FTSR", baseaddress, 0xc>,
                              swier_tt<"SWIER", baseaddress, 0x10>,
                              pr_tt<"PR", baseaddress, 0x14>>;

  constexpr auto exti = exti_t{};

} // namespace exti

namespace nvic {

  constexpr std::uint32_t NVIC_BASE = 0xe000'e100;
  template <std::uint32_t baseaddress>
  using nvic_t = groov::group<nvic,
                              groov::mmio_bus<>,
                              iser_tt<"ISER", baseaddress, 0>,
                              icer_tt<"ICER", baseaddress, 0x80>,
                              ispr_tt<"ISPR", baseaddress, 0x100>,
                              icpr_tt<"ICPR", baseaddress, 0x180>,
                              ipr0_tt<"IPR0", baseaddress, 0x300>,
                              ipr1_tt<"IPR1", baseaddress, 0x304>,
                              ipr2_tt<"IPR2", baseaddress, 0x308>,
                              ipr3_tt<"IPR3", baseaddress, 0x30c>,
                              ipr4_tt<"IPR4", baseaddress, 0x310>,
                              ipr5_tt<"IPR5", baseaddress, 0x314>,
                              ipr6_tt<"IPR6", baseaddress, 0x318>,
                              ipr7_tt<"IPR7", baseaddress, 0x31c>>;

  constexpr auto nvic = nvic_t{};

} // namespace nvic

namespace dma1 {

  constexpr std::uint32_t DMA1_BASE = 0x4002'0000;
  template <std::uint32_t baseaddress>
  using dma1_t = groov::group<dma1,
                              groov::mmio_bus<>,
                              isr_tt<"ISR", baseaddress, 0>,
                              ifcr_tt<"IFCR", baseaddress, 0x4>,
                              ccr1_tt<"CCR1", baseaddress, 0x8>,
                              cndtr1_tt<"CNDTR1", baseaddress, 0xc>,
                              cpar1_tt<"CPAR1", baseaddress, 0x10>,
                              cmar1_tt<"CMAR1", baseaddress, 0x14>,
                              ccr2_tt<"CCR2", baseaddress, 0x1c>,
                              cndtr2_tt<"CNDTR2", baseaddress, 0x20>,
                              cpar2_tt<"CPAR2", baseaddress, 0x24>,
                              cmar2_tt<"CMAR2", baseaddress, 0x28>,
                              ccr3_tt<"CCR3", baseaddress, 0x30>,
                              cndtr3_tt<"CNDTR3", baseaddress, 0x34>,
                              cpar3_tt<"CPAR3", baseaddress, 0x38>,
                              cmar3_tt<"CMAR3", baseaddress, 0x3c>,
                              ccr4_tt<"CCR4", baseaddress, 0x44>,
                              cndtr4_tt<"CNDTR4", baseaddress, 0x48>,
                              cpar4_tt<"CPAR4", baseaddress, 0x4c>,
                              cmar4_tt<"CMAR4", baseaddress, 0x50>,
                              ccr5_tt<"CCR5", baseaddress, 0x58>,
                              cndtr5_tt<"CNDTR5", baseaddress, 0x5c>,
                              cpar5_tt<"CPAR5", baseaddress, 0x60>,
                              cmar5_tt<"CMAR5", baseaddress, 0x64>,
                              ccr6_tt<"CCR6", baseaddress, 0x6c>,
                              cndtr6_tt<"CNDTR6", baseaddress, 0x70>,
                              cpar6_tt<"CPAR6", baseaddress, 0x74>,
                              cmar6_tt<"CMAR6", baseaddress, 0x78>,
                              ccr7_tt<"CCR7", baseaddress, 0x80>,
                              cndtr7_tt<"CNDTR7", baseaddress, 0x84>,
                              cpar7_tt<"CPAR7", baseaddress, 0x88>,
                              cmar7_tt<"CMAR7", baseaddress, 0x8c>>;

  constexpr auto dma1 = dma1_t{};

} // namespace dma1

namespace rcc {

  constexpr std::uint32_t RCC_BASE = 0x4002'1000;
  template <std::uint32_t baseaddress>
  using rcc_t = groov::group<rcc,
                             groov::mmio_bus<>,
                             cr_tt<"CR", baseaddress, 0>,
                             cfgr_tt<"CFGR", baseaddress, 0x4>,
                             cir_tt<"CIR", baseaddress, 0x8>,
                             apb2rstr_tt<"APB2RSTR", baseaddress, 0xc>,
                             apb1rstr_tt<"APB1RSTR", baseaddress, 0x10>,
                             ahbenr_tt<"AHBENR", baseaddress, 0x14>,
                             apb2enr_tt<"APB2ENR", baseaddress, 0x18>,
                             apb1enr_tt<"APB1ENR", baseaddress, 0x1c>,
                             bdcr_tt<"BDCR", baseaddress, 0x20>,
                             csr_tt<"CSR", baseaddress, 0x24>,
                             ahbrstr_tt<"AHBRSTR", baseaddress, 0x28>,
                             cfgr2_tt<"CFGR2", baseaddress, 0x2c>,
                             cfgr3_tt<"CFGR3", baseaddress, 0x30>,
                             cr2_tt<"CR2", baseaddress, 0x34>>;

  constexpr auto rcc = rcc_t{};

} // namespace rcc

namespace syscfg {

  constexpr std::uint32_t SYSCFG_BASE = 0x4001'0000;
  template <std::uint32_t baseaddress>
  using syscfg_t = groov::group<syscfg,
                                groov::mmio_bus<>,
                                cfgr1_tt<"CFGR1", baseaddress, 0>,
                                exticr1_tt<"EXTICR1", baseaddress, 0x8>,
                                exticr2_tt<"EXTICR2", baseaddress, 0xc>,
                                exticr3_tt<"EXTICR3", baseaddress, 0x10>,
                                exticr4_tt<"EXTICR4", baseaddress, 0x14>,
                                cfgr2_tt<"CFGR2", baseaddress, 0x18>>;

  constexpr auto syscfg = syscfg_t{};

} // namespace syscfg

namespace adc {

  constexpr std::uint32_t ADC_BASE = 0x4001'2400;
  template <std::uint32_t baseaddress>
  using adc_t = groov::group<adc,
                             groov::mmio_bus<>,
                             isr_tt<"ISR", baseaddress, 0>,
                             ier_tt<"IER", baseaddress, 0x4>,
                             cr_tt<"CR", baseaddress, 0x8>,
                             cfgr1_tt<"CFGR1", baseaddress, 0xc>,
                             cfgr2_tt<"CFGR2", baseaddress, 0x10>,
                             smpr_tt<"SMPR", baseaddress, 0x14>,
                             tr_tt<"TR", baseaddress, 0x20>,
                             chselr_tt<"CHSELR", baseaddress, 0x28>,
                             dr_tt<"DR", baseaddress, 0x40>,
                             ccr_tt<"CCR", baseaddress, 0x308>>;

  constexpr auto adc = adc_t{};

} // namespace adc

namespace usart1 {

  constexpr std::uint32_t USART1_BASE = 0x4001'3800;
  template <std::uint32_t baseaddress>
  using usart1_t = groov::group<usart1,
                                groov::mmio_bus<>,
                                cr1_tt<"CR1", baseaddress, 0>,
                                cr2_tt<"CR2", baseaddress, 0x4>,
                                cr3_tt<"CR3", baseaddress, 0x8>,
                                brr_tt<"BRR", baseaddress, 0xc>,
                                gtpr_tt<"GTPR", baseaddress, 0x10>,
                                rtor_tt<"RTOR", baseaddress, 0x14>,
                                rqr_tt<"RQR", baseaddress, 0x18>,
                                isr_tt<"ISR", baseaddress, 0x1c>,
                                icr_tt<"ICR", baseaddress, 0x20>,
                                rdr_tt<"RDR", baseaddress, 0x24>,
                                tdr_tt<"TDR", baseaddress, 0x28>>;

  constexpr auto usart1 = usart1_t{};

} // namespace usart1

namespace usart2 {

  constexpr std::uint32_t USART2_BASE = 0x4000'4400;
  template <std::uint32_t baseaddress>
  using usart2_t = groov::group<usart2,
                                groov::mmio_bus<>,
                                cr1_tt<"CR1", baseaddress, 0>,
                                cr2_tt<"CR2", baseaddress, 0x4>,
                                cr3_tt<"CR3", baseaddress, 0x8>,
                                brr_tt<"BRR", baseaddress, 0xc>,
                                gtpr_tt<"GTPR", baseaddress, 0x10>,
                                rtor_tt<"RTOR", baseaddress, 0x14>,
                                rqr_tt<"RQR", baseaddress, 0x18>,
                                isr_tt<"ISR", baseaddress, 0x1c>,
                                icr_tt<"ICR", baseaddress, 0x20>,
                                rdr_tt<"RDR", baseaddress, 0x24>,
                                tdr_tt<"TDR", baseaddress, 0x28>>;

  constexpr auto usart2 = usart2_t{};

} // namespace usart2

namespace usart3 {

  constexpr std::uint32_t USART3_BASE = 0x4000'4800;
  template <std::uint32_t baseaddress>
  using usart3_t = groov::group<usart3,
                                groov::mmio_bus<>,
                                cr1_tt<"CR1", baseaddress, 0>,
                                cr2_tt<"CR2", baseaddress, 0x4>,
                                cr3_tt<"CR3", baseaddress, 0x8>,
                                brr_tt<"BRR", baseaddress, 0xc>,
                                gtpr_tt<"GTPR", baseaddress, 0x10>,
                                rtor_tt<"RTOR", baseaddress, 0x14>,
                                rqr_tt<"RQR", baseaddress, 0x18>,
                                isr_tt<"ISR", baseaddress, 0x1c>,
                                icr_tt<"ICR", baseaddress, 0x20>,
                                rdr_tt<"RDR", baseaddress, 0x24>,
                                tdr_tt<"TDR", baseaddress, 0x28>>;

  constexpr auto usart3 = usart3_t{};

} // namespace usart3

namespace usart4 {

  constexpr std::uint32_t USART4_BASE = 0x4000'4c00;
  template <std::uint32_t baseaddress>
  using usart4_t = groov::group<usart4,
                                groov::mmio_bus<>,
                                cr1_tt<"CR1", baseaddress, 0>,
                                cr2_tt<"CR2", baseaddress, 0x4>,
                                cr3_tt<"CR3", baseaddress, 0x8>,
                                brr_tt<"BRR", baseaddress, 0xc>,
                                gtpr_tt<"GTPR", baseaddress, 0x10>,
                                rtor_tt<"RTOR", baseaddress, 0x14>,
                                rqr_tt<"RQR", baseaddress, 0x18>,
                                isr_tt<"ISR", baseaddress, 0x1c>,
                                icr_tt<"ICR", baseaddress, 0x20>,
                                rdr_tt<"RDR", baseaddress, 0x24>,
                                tdr_tt<"TDR", baseaddress, 0x28>>;

  constexpr auto usart4 = usart4_t{};

} // namespace usart4

namespace usart6 {

  constexpr std::uint32_t USART6_BASE = 0x4001'1400;
  template <std::uint32_t baseaddress>
  using usart6_t = groov::group<usart6,
                                groov::mmio_bus<>,
                                cr1_tt<"CR1", baseaddress, 0>,
                                cr2_tt<"CR2", baseaddress, 0x4>,
                                cr3_tt<"CR3", baseaddress, 0x8>,
                                brr_tt<"BRR", baseaddress, 0xc>,
                                gtpr_tt<"GTPR", baseaddress, 0x10>,
                                rtor_tt<"RTOR", baseaddress, 0x14>,
                                rqr_tt<"RQR", baseaddress, 0x18>,
                                isr_tt<"ISR", baseaddress, 0x1c>,
                                icr_tt<"ICR", baseaddress, 0x20>,
                                rdr_tt<"RDR", baseaddress, 0x24>,
                                tdr_tt<"TDR", baseaddress, 0x28>>;

  constexpr auto usart6 = usart6_t{};

} // namespace usart6

namespace usart5 {

  constexpr std::uint32_t USART5_BASE = 0x4000'5000;
  template <std::uint32_t baseaddress>
  using usart5_t = groov::group<usart5,
                                groov::mmio_bus<>,
                                cr1_tt<"CR1", baseaddress, 0>,
                                cr2_tt<"CR2", baseaddress, 0x4>,
                                cr3_tt<"CR3", baseaddress, 0x8>,
                                brr_tt<"BRR", baseaddress, 0xc>,
                                gtpr_tt<"GTPR", baseaddress, 0x10>,
                                rtor_tt<"RTOR", baseaddress, 0x14>,
                                rqr_tt<"RQR", baseaddress, 0x18>,
                                isr_tt<"ISR", baseaddress, 0x1c>,
                                icr_tt<"ICR", baseaddress, 0x20>,
                                rdr_tt<"RDR", baseaddress, 0x24>,
                                tdr_tt<"TDR", baseaddress, 0x28>>;

  constexpr auto usart5 = usart5_t{};

} // namespace usart5

namespace rtc {

  constexpr std::uint32_t RTC_BASE = 0x4000'2800;
  template <std::uint32_t baseaddress>
  using rtc_t = groov::group<rtc,
                             groov::mmio_bus<>,
                             tr_tt<"TR", baseaddress, 0>,
                             dr_tt<"DR", baseaddress, 0x4>,
                             cr_tt<"CR", baseaddress, 0x8>,
                             isr_tt<"ISR", baseaddress, 0xc>,
                             prer_tt<"PRER", baseaddress, 0x10>,
                             alrmar_tt<"ALRMAR", baseaddress, 0x1c>,
                             wpr_tt<"WPR", baseaddress, 0x24>,
                             ssr_tt<"SSR", baseaddress, 0x28>,
                             shiftr_tt<"SHIFTR", baseaddress, 0x2c>,
                             tstr_tt<"TSTR", baseaddress, 0x30>,
                             tsdr_tt<"TSDR", baseaddress, 0x34>,
                             tsssr_tt<"TSSSR", baseaddress, 0x38>,
                             calr_tt<"CALR", baseaddress, 0x3c>,
                             tafcr_tt<"TAFCR", baseaddress, 0x40>,
                             alrmassr_tt<"ALRMASSR", baseaddress, 0x44>,
                             bkp0r_tt<"BKP0R", baseaddress, 0x50>,
                             bkp1r_tt<"BKP1R", baseaddress, 0x54>,
                             bkp2r_tt<"BKP2R", baseaddress, 0x58>,
                             bkp3r_tt<"BKP3R", baseaddress, 0x5c>,
                             bkp4r_tt<"BKP4R", baseaddress, 0x60>>;

  constexpr auto rtc = rtc_t{};

} // namespace rtc

namespace tim15 {

  constexpr std::uint32_t TIM15_BASE = 0x4001'4000;
  template <std::uint32_t baseaddress>
  using tim15_t =
    groov::group<tim15,
                 groov::mmio_bus<>,
                 cr1_tt<"CR1", baseaddress, 0>,
                 cr2_tt<"CR2", baseaddress, 0x4>,
                 smcr_tt<"SMCR", baseaddress, 0x8>,
                 dier_tt<"DIER", baseaddress, 0xc>,
                 sr_tt<"SR", baseaddress, 0x10>,
                 egr_tt<"EGR", baseaddress, 0x14>,
                 ccmr1_output_tt<"CCMR1_OUTPUT", baseaddress, 0x18>,
                 ccmr1_input_tt<"CCMR1_INPUT", baseaddress, 0x18>,
                 ccer_tt<"CCER", baseaddress, 0x20>,
                 cnt_tt<"CNT", baseaddress, 0x24>,
                 psc_tt<"PSC", baseaddress, 0x28>,
                 arr_tt<"ARR", baseaddress, 0x2c>,
                 rcr_tt<"RCR", baseaddress, 0x30>,
                 ccr1_tt<"CCR1", baseaddress, 0x34>,
                 ccr2_tt<"CCR2", baseaddress, 0x38>,
                 bdtr_tt<"BDTR", baseaddress, 0x44>,
                 dcr_tt<"DCR", baseaddress, 0x48>,
                 dmar_tt<"DMAR", baseaddress, 0x4c>>;

  constexpr auto tim15 = tim15_t{};

} // namespace tim15

namespace tim16 {

  constexpr std::uint32_t TIM16_BASE = 0x4001'4400;
  template <std::uint32_t baseaddress>
  using tim16_t =
    groov::group<tim16,
                 groov::mmio_bus<>,
                 cr1_tt<"CR1", baseaddress, 0>,
                 cr2_tt<"CR2", baseaddress, 0x4>,
                 dier_tt<"DIER", baseaddress, 0xc>,
                 sr_tt<"SR", baseaddress, 0x10>,
                 egr_tt<"EGR", baseaddress, 0x14>,
                 ccmr1_output_tt<"CCMR1_OUTPUT", baseaddress, 0x18>,
                 ccmr1_input_tt<"CCMR1_INPUT", baseaddress, 0x18>,
                 ccer_tt<"CCER", baseaddress, 0x20>,
                 cnt_tt<"CNT", baseaddress, 0x24>,
                 psc_tt<"PSC", baseaddress, 0x28>,
                 arr_tt<"ARR", baseaddress, 0x2c>,
                 rcr_tt<"RCR", baseaddress, 0x30>,
                 ccr1_tt<"CCR1", baseaddress, 0x34>,
                 bdtr_tt<"BDTR", baseaddress, 0x44>,
                 dcr_tt<"DCR", baseaddress, 0x48>,
                 dmar_tt<"DMAR", baseaddress, 0x4c>>;

  constexpr auto tim16 = tim16_t{};

} // namespace tim16

namespace tim17 {

  constexpr std::uint32_t TIM17_BASE = 0x4001'4800;
  template <std::uint32_t baseaddress>
  using tim17_t =
    groov::group<tim17,
                 groov::mmio_bus<>,
                 cr1_tt<"CR1", baseaddress, 0>,
                 cr2_tt<"CR2", baseaddress, 0x4>,
                 dier_tt<"DIER", baseaddress, 0xc>,
                 sr_tt<"SR", baseaddress, 0x10>,
                 egr_tt<"EGR", baseaddress, 0x14>,
                 ccmr1_output_tt<"CCMR1_OUTPUT", baseaddress, 0x18>,
                 ccmr1_input_tt<"CCMR1_INPUT", baseaddress, 0x18>,
                 ccer_tt<"CCER", baseaddress, 0x20>,
                 cnt_tt<"CNT", baseaddress, 0x24>,
                 psc_tt<"PSC", baseaddress, 0x28>,
                 arr_tt<"ARR", baseaddress, 0x2c>,
                 rcr_tt<"RCR", baseaddress, 0x30>,
                 ccr1_tt<"CCR1", baseaddress, 0x34>,
                 bdtr_tt<"BDTR", baseaddress, 0x44>,
                 dcr_tt<"DCR", baseaddress, 0x48>,
                 dmar_tt<"DMAR", baseaddress, 0x4c>>;

  constexpr auto tim17 = tim17_t{};

} // namespace tim17

namespace flash {

  constexpr std::uint32_t FLASH_BASE = 0x4002'2000;
  template <std::uint32_t baseaddress>
  using flash_t = groov::group<flash,
                               groov::mmio_bus<>,
                               acr_tt<"ACR", baseaddress, 0>,
                               keyr_tt<"KEYR", baseaddress, 0x4>,
                               optkeyr_tt<"OPTKEYR", baseaddress, 0x8>,
                               sr_tt<"SR", baseaddress, 0xc>,
                               cr_tt<"CR", baseaddress, 0x10>,
                               ar_tt<"AR", baseaddress, 0x14>,
                               obr_tt<"OBR", baseaddress, 0x1c>,
                               wrpr_tt<"WRPR", baseaddress, 0x20>>;

  constexpr auto flash = flash_t{};

} // namespace flash

namespace dbgmcu {

  constexpr std::uint32_t DBGMCU_BASE = 0x4001'5800;
  template <std::uint32_t baseaddress>
  using dbgmcu_t = groov::group<dbgmcu,
                                groov::mmio_bus<>,
                                idcode_tt<"IDCODE", baseaddress, 0>,
                                cr_tt<"CR", baseaddress, 0x4>,
                                apb1_fz_tt<"APB1_FZ", baseaddress, 0x8>,
                                apb2_fz_tt<"APB2_FZ", baseaddress, 0xc>>;

  constexpr auto dbgmcu = dbgmcu_t{};

} // namespace dbgmcu

namespace usb {

  constexpr std::uint32_t USB_BASE = 0x4000'5c00;
  template <std::uint32_t baseaddress>
  using usb_t = groov::group<usb,
                             groov::mmio_bus<>,
                             ep0r_tt<"EP0R", baseaddress, 0>,
                             ep1r_tt<"EP1R", baseaddress, 0x4>,
                             ep2r_tt<"EP2R", baseaddress, 0x8>,
                             ep3r_tt<"EP3R", baseaddress, 0xc>,
                             ep4r_tt<"EP4R", baseaddress, 0x10>,
                             ep5r_tt<"EP5R", baseaddress, 0x14>,
                             ep6r_tt<"EP6R", baseaddress, 0x18>,
                             ep7r_tt<"EP7R", baseaddress, 0x1c>,
                             cntr_tt<"CNTR", baseaddress, 0x40>,
                             istr_tt<"ISTR", baseaddress, 0x44>,
                             fnr_tt<"FNR", baseaddress, 0x48>,
                             daddr_tt<"DADDR", baseaddress, 0x4c>,
                             btable_tt<"BTABLE", baseaddress, 0x50>,
                             lpmcsr_tt<"LPMCSR", baseaddress, 0x54>,
                             bcdr_tt<"BCDR", baseaddress, 0x58>>;

  constexpr auto usb = usb_t{};

} // namespace usb

namespace scb {

  constexpr std::uint32_t SCB_BASE = 0xe000'ed00;
  template <std::uint32_t baseaddress>
  using scb_t = groov::group<scb,
                             groov::mmio_bus<>,
                             cpuid_tt<"CPUID", baseaddress, 0>,
                             icsr_tt<"ICSR", baseaddress, 0x4>,
                             aircr_tt<"AIRCR", baseaddress, 0xc>,
                             scr_tt<"SCR", baseaddress, 0x10>,
                             ccr_tt<"CCR", baseaddress, 0x14>,
                             shpr2_tt<"SHPR2", baseaddress, 0x1c>,
                             shpr3_tt<"SHPR3", baseaddress, 0x20>>;

  constexpr auto scb = scb_t{};

} // namespace scb

namespace stk {

  constexpr std::uint32_t STK_BASE = 0xe000'e010;
  template <std::uint32_t baseaddress>
  using stk_t = groov::group<stk,
                             groov::mmio_bus<>,
                             csr_tt<"CSR", baseaddress, 0>,
                             rvr_tt<"RVR", baseaddress, 0x4>,
                             cvr_tt<"CVR", baseaddress, 0x8>,
                             calib_tt<"CALIB", baseaddress, 0xc>>;

  constexpr auto stk = stk_t{};

} // namespace stk

} // namespace stm32
